### ISSUE TITLE
Miner.PenalizeFundsInPriorityOrder: account for fromVesting greater than target

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#1003]
`PenalizeFundsInPriorityOrder` first pulls from the miner's unvested funds. If the amount taken from unvested funds is equal to the target penalty to apply, the method should end early without removing anything from the miner's unlocked balance:

https://github.com/filecoin-project/specs-actors/blob/810ab30d86305cbcb8b949b2919899b3f5338b7f/actors/builtin/miner/miner_state.go#L765-L767

Although `UnlockUnvestedFunds` should never return `fromVesting > target`, the above branch should handle this case - as the rest of the method would otherwise erroneously increase the miner's fee debt.

**Comment by anorth** [comment]
This code has changed with the fee debt refactor. It now asserts that `fromVesting <= st.FeeDebt`.

cc @ZenGround0
