### ISSUE TITLE
Miner: Treat initial pledge like precommit deposits

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#1007]
This issue proposes to treat the miner's `st.InitialPledgeRequirement` the same as `st.PreCommitDeposits`. 

When incurring penalties, the Miner's balance should never be reduced below the amount required to cover `st.LockedFunds + st.PreCommitDeposits + st.InitialPledgeRequirement`, with the remainder accumulated in `st.FeeDebt`.

Penalties are incurred via the method `st.PenalizeFundsInPriorityOrder`, which is invoked in 4 locations:
* `SubmitWindowedPoSt`: No changes required.
* `ReportConsensusFault`: Consensus fault penalties no longer come out of the miner's initial pledge. Although this may lower the possible reward for reporting a consensus fault, it also prevents miners from intentionally creating consensus faults in order to recover portions of their pledge.
* `processEarlyTerminations`: Removal of initial pledge requirement should come _before_ the termination penalty is applied: https://github.com/filecoin-project/specs-actors/blob/ca1b7724d3016313f76c583c4f1110fe1e58ef7d/actors/builtin/miner/miner_actor.go#L1612-L1622
* `handleProvingDeadline`: Penalties for ongoing faults and undeclared faults should be applied once, and only _after_ initial pledge is adjusted to account for expired sectors: https://github.com/filecoin-project/specs-actors/blob/ca1b7724d3016313f76c583c4f1110fe1e58ef7d/actors/builtin/miner/miner_actor.go#L1746-L1750

#### Changes Required

The following changes are already implemented in #1004:
* `GetUnlockedBalance` should additionally subtract `st.InitialPledgeRequirement`: https://github.com/filecoin-project/specs-actors/blob/ca1b7724d3016313f76c583c4f1110fe1e58ef7d/actors/builtin/miner/miner_state.go#L864
* `GetAvailableBalance` should no longer subtract `st.InitialPledgeRequirement`: https://github.com/filecoin-project/specs-actors/blob/ca1b7724d3016313f76c583c4f1110fe1e58ef7d/actors/builtin/miner/miner_state.go#L872-L873
* `AssertBalanceInvariants` should additionally assert that:
  * `st.InitialPledgeRequirement >= 0`
  * `rt.CurrentBalance() >= Sum(st.LockedFunds, st.PreCommitDeposits, st.InitialPledgeRequirement)`
* `MeetsInitialPledgeCondition` should return `false` IFF the miner has positive `FeeDebt`, as positive `FeeDebt` indicates that the miner is in "IP debt"

The following changes have yet to be implemented:
* `processEarlyTerminations`: Remove IP requirement for terminated sectors _before_ termination penalty is applied
* `handleProvingDeadline`: Apply penalties in bulk _after_ sector expiries are accounted for.

**Comment by wadeAlexC** [comment]
cc @ZenGround0 @anorth @acruikshank

**Comment by wadeAlexC** [comment]
The only open question for me is whether to handle debt repayment in `handleProvingDeadline`.

I think implementing a method `RepayAsMuchDebtAsPossible` (more succinctly named) would make sense to invoke during `handleProvingDeadline`, in order to handle the case brought up in #1004.

I'm not convinced it's necessary, though.

**Comment by wadeAlexC** [comment]
Also may be worth noting - I think it's necessary to have an order of operations for debt repayment / penalty calculation, in case these are ever in the same method (like the above idea to put debt repayment in `handleProvingDeadline`)

Debt repayment needs to happen first, and penalties calculated / applied last.

**Comment by Stebalien** [comment]
Note: this changes how we calculate total network pledge collateral.

cc @nicola and @irenegia.

**Comment by Stebalien** [comment]
> Note: this changes how we calculate total network pledge collateral.

This is wrong. When we burn from "pledge", we don't reduce total network pledge accounting.

**Comment by anorth** [comment]
There's currently a wider unsolved problem of how genesis miners will cover their initial pledge requirement. In the current code, we have a policy option that they _don't_ cover it: a genesis miner could have balance below the IP required by genesis sectors. Right now this isn't a practical option because we don't allow miners in IP debt to win blocks, so they couldn't win a reward in order to eventually meet the requirement. But if we change this, that option won't be possible at all.

**Comment by anorth** [comment]
The motivation is simplicity. We currently have three or four different concepts for ways that part of a balance can be locked or unlocked, covered or un-covered. This removes one of them while maintaining the same properties of restricting a miner from election, growth etc.

Rather than having both an IP debt and fee debt concepts, this removes the former. Rather than having both "required" and "locked" funds, this removes the former.

**Comment by anorth** [comment]
Done in #1004. Some follow-ups noted in #1032.
