### ISSUE TITLE
IsSingletonActor not containing Burnt Funds address

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#1029]
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/singletons.go#L32-L40

This list is missing Burnt Funds address 99.

In theory, if we assume that all address from 0 to 99 are reserved, I believe that this check could simply be `return if smaller than 100`

**Comment by Stebalien** [comment]
The burnt funds actor is just an account (i.e., code CID == account). The singletons are code CIDs that should only be instantiated once.
