### ISSUE TITLE
Miner: If a PoSt submission skips ONLY Unproven sectors, the partition is not added to the deadline's ExpirationsEpochs

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#1040]
#### Introduction

`Miner.SubmitWindowedPoSt` allows the miner to signal that certain sectors are faulty and are being excluded from the PoSt ("skipped"). In order to track this and update partition state accordingly, `partition.RecordSkippedFaults` is invoked:

https://github.com/filecoin-project/specs-actors/blob/45f3058a4160e10a0cc85c7a80ac79ee5d2a3306/actors/builtin/miner/deadline_state.go#L916-L920

The returned `newFaultPower` signifies the power that became faulty as a result of the skipped sectors. If this power is nonzero, we take this to mean that there were no new faults:

https://github.com/filecoin-project/specs-actors/blob/45f3058a4160e10a0cc85c7a80ac79ee5d2a3306/actors/builtin/miner/deadline_state.go#L925-L929

This is important, as if there were new faults, the partition must be added to the deadline's `ExpirationsEpochs` for future processing of partitions with expired/faulty-for-too-long sectors:

https://github.com/filecoin-project/specs-actors/blob/45f3058a4160e10a0cc85c7a80ac79ee5d2a3306/actors/builtin/miner/deadline_state.go#L960

#### The issue

`newFaultPower` can be zero even if we added new faults. This occurs if all of the faulty sectors were Unproven, as `partition.addFaults` will return a net zero "new faulty power:"

https://github.com/filecoin-project/specs-actors/blob/45f3058a4160e10a0cc85c7a80ac79ee5d2a3306/actors/builtin/miner/partition_state.go#L191-L198

While this makes sense on the surface (Unproven sectors have not had their power added yet, so their power is not technically "new faulty power"), it breaks the assumption that `newFaultPower.IsZero()` signifies "no new faults."

#### Recommendation

Have `RecordSkippedFaults` return an additional boolean signifying whether or not there were new faults added to the partition.

**Comment by Stebalien** [comment]
You know, I _knew_ that was going to be an issue when I wrote that code, and I still wrote it.

**Comment by wadeAlexC** [comment]
Pretty easy to miss given the 2-3 degrees of separation between the unproven power being removed from `newFaultPower`, and the result being checked / used.

I wonder if any slight refactoring / changes could be made to make it more clear.

**Comment by Stebalien** [comment]
Ah, wait, this isn't actually an issue (I thought I tested this case).

`newFaultPower` is the _total_ new faulty power, we track the power delta (which will be 0 in this case) separately.

However, I'm still going to fix this as it's confusing.

**Comment by wadeAlexC** [comment]
Oh, you're totally right. I missed that the unproven power was removed from the delta, not the total. Good catch
