### ISSUE TITLE
Paych voucher SecretPreimage name is backwards

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1059]
During update state we hash `params.Secret` to get `hashedSecret`.  We then compare and enforce equality on `hashedSecret` and the voucher's `SecretPreimage` field.  Its clear the secret is the preimage.  and the voucher contains the hash.  We should change the voucher name to `SecretHash`

**Comment by ZenGround0** [comment]
[This external document](https://www.evernote.com/shard/s10/client/snv?noteGuid=135ecd3b-b743-4f6d-8943-e9c381fbf7df&noteKey=51f2120ace7d6ed6&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs10%2Fsh%2F135ecd3b-b743-4f6d-8943-e9c381fbf7df%2F51f2120ace7d6ed6&title=Filecoin%2527s%2Bexisting%2Bpayment%2Bchannels%2B-%2BFilecoin%2BRetrieval%2BMarket%2B-%2BConfluence) also noticed that the names are backwards see "Other voucher features"

**Comment by ZenGround0** [comment]
I don't think this will change serialized state just the names used in code.

**Comment by laudiacay** [comment]
Merged into next.
