### ISSUE TITLE
Add log messages for significant events

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1060]
The runtime API exposes a logging hook, which we currently make scarce use of. Log messages could be extremely helpful when debugging actor behaviour in the wild, especially if something unexpected is happening.

Add informational log messages around significant events.

Note that the Runtime will know which the receiving actor is, so it's not necessary to add that information into the message body. The runtime will also know the method number, parameters etc.

Be very careful that log message formatting does not alter the actor behaviour (e.g. by dereferencing a `nil` that otherwise would be ignored).

**Comment by wadeAlexC** [comment]
#### Cron

* Log when an entry fails: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/cron/cron_actor.go#L38-L41

#### Market

* `OnMinerSectorsTerminate`:
  * Log when a deal isn't found: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/market/market_actor.go#L406-L410
  * Log when a deal is expired: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/market/market_actor.go#L414-L417
  * Log if a deal has been slashed: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/market/market_actor.go#L425-L428

#### Power

* `SubmitPoRepForBulkVerify`:
  * Log when `ProofValidationBatch` is created (expected once per epoch): https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L248-L250
* `processBatchProofVerifies`:
  * Log if `ProofValidationBatch` is `nil`: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L311-L313
  * Log if duplicate proof skipped: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L356-L359
  * Log if proof failed (`if !r`): https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L353
  * Log if `ConfirmSectorProofsValid` fails: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L366-L372
* `processDeferredCronEvents`: 
  * Log if no events are loaded (`if len(epochEvents) == 0`): https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/power/power_actor.go#L391-L394

#### VerifReg

* `RestoreBytes`: Log if this method is invoked

#### Miner

* `burnFunds`: Log if this method is invoked with nonzero `amt`
* `RepayDebtsOrAbort`: Log if this method is invoked and succeeds
* `SubmitWindowedPoSt`:
  * Log if all sectors are faults (`if len(sectorsInfos) == 0`): https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/miner/miner_actor.go#L392-L394
* `OnDeferredCronEvent`: Add a `default` case, and log if it's reached
* `processEarlyTerminations`:
  * Log if early terminations are empty: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/miner/miner_actor.go#L1595-L1600
  * Log if early terminations are empty, pt 2: https://github.com/filecoin-project/specs-actors/blob/bcd83e8eb0a98b684851e574a2bd8d4130e21a51/actors/builtin/miner/miner_actor.go#L1642-L1645
* `scheduleEarlyTerminationWork`: Log if this method is invoked

**Comment by ZenGround0** [comment]
#1288 can be done as part of this work.
