### ISSUE TITLE
Propagate penalty > reward from reward to miner actor

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1071]
From @Kubuxu: 
> @anorth @zenground0 We need to figure out how to not cap the Penalty to block reward (in other words 0) that is passed to Reward actor.
Currently if miner gets a lot of penalties they just get block reward of 0. This is really bad in some cases.
> If message FeeCap is too low then the miner pays the difference: BaseFee - message.FeeCap
> This means that if block reward is around 7FIL, and Base Fee is higher than 7e-10 it is worth for the miner to wipe out their block reward and include all of their messages.
In essence, it caps network fee at blockReward/10e9 for miners because then the whole reward is wiped, and they don't pay anything more.

The offending line is the penalty cap in the reward actor [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/reward/reward_actor.go#L100)

In order to penalize the full amount I am proposing we send the penalty and reward over to the miner actor and do a full ordered penalization dropping funds from the miner's account up to imposing fee debt.

1. `AddLockedFunds` --> `ApplyRewards`
2. Add a penalty field to the ApplyRewards params
3. ApplyPenalty(penalty) after adding locked funds
4. RepayPartialDebtInPriorityOrder at the end of method's state transaction

**Comment by anorth** [comment]
This brings more code (risk of bugs) into the reward payment flow, though it may be the right choice.

An alternative formulation:
- Reward actor reduces reward by penalty amount before sending as it does now. This will in practise catch ~all cases
- If penalty was greater than reward, attach remaining unpaid penalty amount to the ApplyRewards message
- Just add that number to FeeDebt directly

This alternative will usually fall back to just a simple transfer and lock-up (b/c as soon as we penalise this abuse properly, miners will stop doing it). When the penalty is too large, it does the simplest thing of just recording the debt. This will make a miner ineligible for election until they repay debts manually by calling some method that triggers it (note: DeclareFaultsRecovered with no faults is the only explicit call available to the worker address here). All taking effect after the election lookback, of course).

But, maybe this short path is not worth it. If the the debt is rare, it won't be well exercised, whereas the first proposal will exercise it every time. So it's a bit more complex, but there's just one way to do it. To clarify, I infer that in the first proposal, the reward actor will stop subtracting and burning the penalty amount itself, and just always transfer the full reward to the miner.

@ZenGround0 's approach is probably better.

This may change some chain-validation / test vector expectations cc @raulk

**Comment by ZenGround0** [comment]
A nice hybrid of the two would be to do (from my list above) 1, 2, 3 but not 4.  This way `AddLockedFunds` never burns anything, it just adds penalty to fee debt reducing the complexity of code reachable through the reward actor while still also avoiding the complexity of two code paths.  

I'm going to move forward with this hybrid!

**Comment by anorth** [comment]
I think that either: 
- the reward actor should pay fee with withheld reward, or
- the debt must be paid off in the miner 
(in either case, as far as reward/balance permits)

Otherwise, this immediately makes a miner ineligible for election. These penalties will sometimes happen through bad luck, rather than malicious behaviour. See also #1072
