### ISSUE TITLE
WARN	vm	vm/runtime.go:302	Abortf: all prove commits failed to validate

### ISSUE THREAD

**Issue by welabs1** [filecoin-project/specs-actors#1074]
2020-09-02T03:27:33.643+0800	WARN	vm	vm/runtime.go:302	Abortf: all prove commits failed to validate
0|lotus daemon  | 2020-09-02T03:27:33.643+0800	WARN	vm	vm/runtime.go:115	VM.Call failure: all prove commits failed to validate (RetCode=16):
0|lotus daemon  |     github.com/filecoin-project/specs-actors/actors/builtin/miner.Actor.ConfirmSectorProofsValid
0|lotus daemon  |         /home/jack/go_workspace/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.3/actors/builtin/miner/miner_actor.go:707
0|lotus daemon  | 2020-09-02T03:27:33.643+0800	WARN	vm	vm/runtime.go:354	vmctx send failed: to: t02514, method: 17: ret: [], err: all prove commits failed to validate (RetCode=16)
0|lotus daemon  | 2020-09-02T03:27:33.653+0800	WARN	vm	vm/runtime.go:302	Abortf: all prove commits failed to validate
0|lotus daemon  | 2020-09-02T03:27:33.653+0800	WARN	vm	vm/runtime.go:115	VM.Call failure: all prove commits failed to validate (RetCode=16):
0|lotus daemon  |     github.com/filecoin-project/specs-actors/actors/builtin/miner.Actor.ConfirmSectorProofsValid

**Comment by ZenGround0** [comment]
This means that all sectors you passed to prove failed to activate their deals.  The state machine call StorageMarketActor.ActivateDeals failed for each one of the proofs being confirmed in ConfirmSectorProofsValid.

**Comment by ZenGround0** [comment]
We'll need more information from you on the reason for filing.  As it stands this looks like everything is working as intended, this is what we would expect when deals in all pre commits under proof confirmation do not pass market validation for activation.

If you want help debugging this in space race head over to the filecoin slack channel (I couldn't find your handle there or I would have pinged you)

Please reopen if you have more information to share and believe this goes beyond a debugging request.
