### ISSUE TITLE
Miner: Declaring a replaced CC sector faulty can result in a sector existing in an expiration queue twice

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#1100]
Replaced CC sectors get their expiration rescheduled in `ConfirmSectorProofsValid`:

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/miner_actor.go#L770-L772

This means that, within the replaced sectors' partitions, they are removed from `partition.ExpirationsEpochs` at their "on-time expiry," and re-added at a `newExpiration` (the end of their next deadline window):

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/expiration_queue.go#L177-L190

Note that replaced CC sectors cannot be faulty at the time they are replaced. However, they can be declared faulty after the fact. When a replaced CC sector is declared faulty, `expiration_queue.RescheduleAsFaults` is invoked, which iterates over fault declarations by on-time expiration. For each expiration, the queue is queried for a corresponding `ExpirationSet`:

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/expiration_queue.go#L201-L207

The sectors in question may, or may not exist in this `ExpirationSet`; no existence check is made.

#### Results

If the now-faulty sector's on-time expiration is less than or equal to the fault expiration, the expiration set's active and faulty power totals are adjusted erroneously:

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/expiration_queue.go#L208-L214

If the now-faulty sector's on-time expiration would come _after_ the fault expiration, this method reschedules the sector for expiration at the fault expiration epoch. This rescheduling is done by first removing the sector from `ExpirationSet.OnTimeSectors` (note that this doesn't do anything - the sector isn't there):

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/expiration_queue.go#L216-L222

Then, the sector is re-added to the queue at the fault expiry epoch:

https://github.com/filecoin-project/specs-actors/blob/b1153df2ab47c2db86b46b04fa94592d4adf0599/actors/builtin/miner/expiration_queue.go#L234-L241

In this case, the sector ends up in the expiration queue twice: at the end of its next deadline window, and at the fault expiry epoch. This should never happen and may have several unintended consequences - improper power accounting, cron callback aborts, and more.

#### Conclusion

This method of inserting a replaced CC sector into an expiration queue twice is possible via `Miner.DeclareFaults` as well as `Miner.SubmitWindowedPoSt` (where the sector is marked "skipped"). 

The primary cause of the issue is a failure to check for the existence of referenced sectors within `expiration_queue.RescheduleAsFaults`.

I did not find any other miner methods that handle replaced CC sectors incorrectly, but **further investigation is warranted.** In particular, the expiration queue implementation often performs operations without making checks to ensure that certain invariants are maintained. Consider reviewing the file as a whole and adding checks like those mentioned in #1064, as well as existence checks throughout.

**Comment by acruikshank** [comment]
It seems a reasonable first pass at this is to remove sectors not in the OnTimeSectors expiration set from the fault expiration group. So we would not update power and pledge for these sectors and would not add them to the new expiration queue.

I think this means miner could get a little free power because the cc replaced sector could live past the point where it should have faulted out (but not by much if any).
