### ISSUE TITLE
Miner eligibility check does not check for min miner size

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#1102]
As I explain in this comment https://github.com/filecoin-project/lotus/issues/3378#issuecomment-687526380, there are three checks to be done by lotus:

- Check that miner is valid at current epoch
- Check that miner is eligible at current epoch
- Check that miner had min miner size at WinningPoStSectorSet lookback

Check 1 and 3 are currently already integrated in lotus, check 2 must be added (https://github.com/filecoin-project/lotus/issues/3378 is tracking this addition).

Check 2 should not check min miner size (hence these lines should be removed)

Why? Eligibility and validity check are not related to power accounting, but to debts and faults. Anything related to power accounting must happen with the lookback.

**Comment by anorth** [comment]
@nicola expresses this slightly differently to how I think we should implement it. We want to abstract the details of which checks are required at which epoch. I don't understand the difference between "validity" and "eligibility", and suggest that there isn't one worth making.

Implement two functions:
- `MinerEligibleForElection` that tests all the predicates relevant at the epoch of the election
    - Remove the call to `MinerNominalPowerMeetsConsensusMinimum`
    - Add a check that the miner has a non-empty claim
    - Retain checks on debt, consensus-fault-free etc
- `MinerEligibleAtElectionLookback` that tests all predicates relevant at the WinningPoSt lookback
    - Implement a new function
    - Call `MinerNominalPowerMeetsConsensusMinimum`

See also this [spec draft](https://github.com/filecoin-project/specs/blob/light/content/protocol/_index.md#mining-requirements).
