### ISSUE TITLE
paych voucher channel addr is robust address but is compared to ID address

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/specs-actors#1120]
```
// A voucher is sent by `From` to `To` off-chain in order to enable
// `To` to redeem payments on-chain in the future
type SignedVoucher struct {
	// ChannelAddr is the address of the payment channel this signed voucher is valid for
	ChannelAddr addr.Address
       ...
```

The payment channel [`SignedVoucher.ChannelAddr`](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/paych/paych_actor.go#L96) field is a robust address, however it is [compared to message receiver](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/paych/paych_actor.go#L174), which is an ID address:
```
	pchAddr := rt.Message().Receiver()
	if pchAddr != sv.ChannelAddr {
		rt.Abortf(exitcode.ErrIllegalArgument, "voucher payment channel address %s does not match receiver %s", sv.ChannelAddr, pchAddr)
	}
```

Until now this was working because of [a bug in lotus VM](https://github.com/filecoin-project/lotus/pull/3589) whereby Runtime `Receiver()` was returning a robust address instead of an ID address.

Because
- the voucher is long-lived
- the voucher is sent off-chain from a voucher creator to a voucher receiver
- the voucher receiver submits the voucher on-chain

I believe that it makes sense for `SignedVoucher.ChannelAddr` to be a robust address.

If that assumption is correct then I'd suggest comparing `rt.Message().Receiver()` against the ID address of `SignedVoucher.ChannelAddr`.

Suggested fix: https://github.com/filecoin-project/specs-actors/pull/1121

**Comment by anorth** [comment]
The only reason not to use an ID-address for `ChannelAddr` is if the channel has been created very recently and so the ID-address may not be stable. The voucher longevity and off-chain nature don't make a difference.

It does still seem reasonable to resolve it, though.

**Comment by dirkmc** [comment]
Great, thanks for the quick review + merge 🙏
