### ISSUE TITLE
Failed to withdraw balance from market actor

### ISSUE THREAD

**Issue by xuanyan0x7c7** [filecoin-project/specs-actors#1123]
When sending message of type `WithdrawBalance` to market actor, it always throws `Method must validate caller identity exactly once`, because `ValidateImmediateCallerxx` is called twice in
https://github.com/filecoin-project/specs-actors/blob/v0.9.7/actors/builtin/market/market_actor.go#L73-L110

**Comment by ZenGround0** [comment]
Thanks for the report.  We filed the same bug a week ago here: https://github.com/filecoin-project/specs-actors/issues/1075 and this is now fixed on master.
