### ISSUE TITLE
Move (most of) runtime/proof into go-state-types

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#1125]
These types are used in runtime interfaces and FFI. For now, it's likely possible to just rely on type aliases and use the "v2" types everywhere but:

1. It would be cleaner to have these types live in an different package.
2. That won't help us if we actually need to add new fields to these types (unlikely?).

Specifically, the types referenced in "sector-storage":

* SealVerifyInfo
* WinningPoStVerifyInfo
* SectorInfo
* PoStProof

~In terms of network upgrades, we should be able to just add fields as needed to these types, and change the proof type itself as necessary.~

**Comment by Stebalien** [comment]
We won't be able to easily add fields to `SectorInfo` and `PoStProof` because these types are serialzed to CBOR. However:

1. `SectorInfo` and `PoStProof` shouldn't ever _need_ additional fields, as far as I can tell, and we can cross that bridge later if necessary.
2. While `SealVerifyInfo` and `WinningPoStVerifyInfo` support serialization to CBOR, lotus appears to build just fine after removing CBOR support. I haven't run the tests but these appear to be ephemeral types used by the runtime.

As far as I know, the main concern with this change would be runtime API "semantics". That is, if the runtime "semantically" takes bytes as inputs, and we just happen to not be serializing to bytes for convenience, this change could be problematic.

If necessary, we can introduce additional types inside lotus, and just copy between types as necessary. However, I'd prefer not to if at all possible.

**Comment by Stebalien** [comment]
Ok, so, apparently I should have run the tests instead of relying on type checks. `SubmitPoRepForBulkVerify` uses `SealVerifyInfo` (serialized).

**Comment by Stebalien** [comment]
For now, I'm going to use different types inside lotus.

**Comment by ZenGround0** [comment]
Alright, let us know if anything changes and you end up wanting these in go-state-types

**Comment by anorth** [comment]
I discussed a little with @Stebalien too. Since they're not changing, I don't think we need this now. And there might be better longer term options if we want to accomodate change here, perhaps adjusting the runtime interface to be more abstract.

**Comment by Stebalien** [comment]
Agreed. Closing for now.
