### ISSUE TITLE
Multisig tx ret code is ignored

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/specs-actors#113]
Here https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L311. 

Return code and tx status are ignored. I propose add method `getTxStatus(TxId)` that returns `[Pending, Cancelled, InvocationOutput]`

**Comment by Alexey-N-Chernyshov** [comment]
Also I want to pay attention that Lotus implementation doesn't ignore error
https://github.com/filecoin-project/lotus/blob/master/chain/actors/actor_multisig.go#L217

**Comment by anorth** [comment]
The spec actor differs from Lotus in that completed transactions are removed from state. Your proposed getStatus is thus impossible. What's missing here is propagating the transaction status in the return value (and hence message receipt) of the call to Approve.

**Comment by Alexey-N-Chernyshov** [comment]
Yes, I see. But I don't understand what stands for the removal of completion status from transaction status in this spec. Does it have any benefits?
As for propagating the transaction status in the return method of the call to Approve. Now Approve returns EmptyValue. If it is changed to InvocationOutput, it would return to only the last approver, isn't it? And how can caller distinguish return code from the underlying transaction and approve call?

**Comment by anorth** [comment]
Removing completed transactions reduces the size of chain state, which decreases the cost of maintaining it by all nodes. If transactions were not removed after completion, we would need an explicit clean-up mechanism, which opens questions about who should pay the gas fees for that cleanup. This is a considered approach.

The return value of transactions is not generally present in the state, it's present in the blockchain blocks/messages/receipts. The multisig is consistent with all other transactions here: if a party wants to know the exit code or return value it must generally replay the transaction, or have maintained a full blockchain history (which includes receipts).

We can choose to distinguish multisig exit codes from the delegated call exit codes in the not-yet-implemented return value from Approve.

**Comment by Alexey-N-Chernyshov** [comment]
Thanks for exhaustive answer, now I got it.

**Comment by anorth** [comment]
Work to be done here remains to add a return value to Approve, containing the nested transaction's exit code and return value. Probably also add the same to `Propose`, to handle the case of a single-signer multisig.
