### ISSUE TITLE
MultiSig automatic threshold decrease ignores input parameter

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/specs-actors#114]
When `removeSigner` called with `decrease` parameter set as `false` and number of signers after removal is greater than threshold, the `decrease` parameter is ignored and threshold decreased implicitly. I think error ErrIllegalArgument should be raised.

https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L212

Test
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_test.go#L687

**Comment by anorth** [comment]
The existing code seems like a reasonable design choice to me. It's well-defined, conscious, and I don't see an error.

If you have a good argument for why rejecting the call rather than implicitly decreasing would be superior (technical or user), let's hear it. Otherwise we'll leave this as-is.

**Comment by Alexey-N-Chernyshov** [comment]
I quote from Python Zen:
> Explicit is better than implicit.
> “This aphorism is self-explanatory,” that would be a terrible explanation for any aphorism. Similarly, it’s better for code to be verbose and explicit. You should avoid hiding code’s functionality behind obscure language features that require familiarity to fully understand.
