### ISSUE TITLE
Runtime.CreateActor can only be used by the init actor?

### ISSUE THREAD

**Issue by alanshaw** [filecoin-project/specs-actors#1143]
I noticed that `Runtime.CreateActor` should only be used by the init actor:

https://github.com/filecoin-project/specs-actors/blob/c9027ee0393a0b76c3185f99f61a506f09e1a5cf/actors/runtime/runtime.go#L103-L106

There are no checks in lotus that this happens ([see here](https://github.com/filecoin-project/lotus/blob/c017d0fbafca5722d2768ac05c0a5f424df57f40/chain/vm/runtime.go#L227-L253)) and it looks like [go-filecoin did not check either](https://github.com/filecoin-project/go-filecoin/blob/master/internal/pkg/vm/internal/vmcontext/invocation_context.go#L500-L533).

Should there be an assertion within `Runtime.CreateActor` that the caller is the init actor?...and should there be a test in [test-vectors](https://github.com/filecoin-project/test-vectors) to verify this is the case?

If yes to the above then we have a problem right now with the chaos actor because it has a `CreateActor` method that calls `Runtime.CreateActor` directly to test other behaviours and it's only able to do so because of a bug 😱.

cc @filecoin-project/oni

**Comment by anorth** [comment]
Yes, there should be a check in Lotus (aborting with `SysErrIllegalActor`).
