### ISSUE TITLE
Adjust Minimum Miner Size to 10TiB RawBytePower

### ISSUE THREAD

**Issue by momack2** [filecoin-project/specs-actors#1153]
Currently, Space Race is using 10TiB QA Power for block mining eligibility. Based on observations from the competition and security/cryptoecon analysis so far, we should adjust the mainnet parameter for Minimum Miner Size (aka eligibility to earn block rewards) from 100 TiB QA power --> **10 TiB RawBytePower**. 🎉

This helps increase network diversity and ensure many miners big and small can successfully participate in Filecoin mining.

**Comment by acruikshank** [comment]
Currently consensus minimum power is a function of proof type, where we've decided to double the 100TiB QA limit for miners using 64GiB sectors. It sounds like security is not the primary concern here and we don't have a lot (any?) 64GiB miners, so I'm just going to go ahead and make the minimum 20TiB for 64GiB miners (raw power) unless someone gives me a better number.

**Comment by momack2** [comment]
@nicola can you comment on that?

**Comment by nicola** [comment]
Min power is 10TiB raw power for 32GiB SDR and 20TiB raw power for 64GiB SDR.
