### ISSUE TITLE
Implement actor state invariant checks (slow version) for other actors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1165]
The `states/check.go` file is an entry point for exhaustive actor state verifications, for use in tests and migrations. A couple of actors have checks defined, but we need the rest too.

- [x] account
- [x] cron
- [x] init
- [x] market
- [x] miner
- [x] multisig
- [x] paych
- [x] power
- [x] reward
- [x] verifreg

**Comment by anorth** [comment]
@acruikshank @ZenGround0 do you think we're all done here after #1240?

**Comment by acruikshank** [comment]
@anorth Yes. We'll have a good base. From here we should probably add when we discover problems that could be recast and broken invariants.
