### ISSUE TITLE
Implement cross-actor consistency checks

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1166]
Following #1165, implement consistency checks between actor states, such as consistency between the power, market, and miner actors' sector, power and deal state.

**Comment by ZenGround0** [comment]
@acruikshank do you have ideas for what remains after your miner-market and miner-power cross check PRs?

**Comment by acruikshank** [comment]
I'm pretty sure everything else gets pretty deep into cryptoeconomics. Like we might be able to put some bounds on a miner's initial pledge based on current reward actor state, or bound reward actors state values based on power actor stats, but I can't explain how to do that. I don't think there are any more simple relationships like the ones between miners and power or miners and market.

**Comment by ZenGround0** [comment]
Closing this, we can open a new issue to advance to the next level of paranoia
