### ISSUE TITLE
Method to change miner actor owner address

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/specs-actors#1176]
This is to allow to transfer miner to another owner address.

https://github.com/filecoin-project/lotus/issues/3951

**Comment by anorth** [comment]
@nicola @whyrusleeping could you comment on the desirability of this?

This is a high security area, so I'm guessing that the mechanism will be at least as complicated as changing the worker address (with a time-delay, etc).

**Comment by nicola** [comment]
Pending confirmation from @irenegia and myself: my initial intuition is that since the owner key is never used for signing randomness (e.g. in the election VRF), this seems and it seems that it could be treated as the control keys. I will have to look at all the references of the owner key in the code.

Who can change the owner key? only the owner key?

**Comment by anorth** [comment]
Maybe it can be simpler than I thought, which is great. Let's hypothesize a `ChangeOwnerAddress` method that takes immediate effect. (I don't think we should combine with the existing `ChangeWorkerAddress`).

An operator can get in real trouble with a mistake here. *Assuming* that only the owner address can change the owner address, changing to a bad address that the operator does not in fact control would be irreversible and cause loss of all vesting rewards. A safe-to-use mechanism should require confirming control of the new address. 

This could be either of:
1. `ChangeOwnerAddress` method params include a signature from the new key over something
    - This signature would be validated on-chain via the `VerifySignature` syscall
    - What can we sign? The old address? The miner address? Must be something accessible to actors.
    - No state changes
1. `ChangeOwnerAddress` method be two steps, first staging the new owner address in actor state, and then requiring the method to be called again _by the new address_ to confirm it.
    - The signature validation is "off-chain", implicit in the message validity
    - The thing signed by the new key is the confirmation message, but it doesn't need to be directly accessible within actors
    - Requires new state

... or maybe something else.

**Comment by anorth** [comment]
@whyrusleeping points out that we want to permit the owner to be a multisig. This rules out option 1 above, leaving the two-stage alternative. I don't like changing state this late in the game, but it's simple enough.

**Comment by nikkolasg** [comment]
Why does this rules out option 1 ? A multisig key can still produce a signature,

But I'm not even sure we need to prove the operators controls the new owner key. That's user level security that wallets and such should take care of: there are plenty of reasons why you could loose all your rewards, including this reason, but should the chain be the one that prevents some of those reasons, or the actual user & wallet ?

**Comment by nicola** [comment]
@nikkolasg multisig do not produce signature, the parties in the multisig contract each individually sign things and then the actor executes the proposed transaction (in my understanding).

**Comment by nicola** [comment]
@anorth why can we not just update the address in the same way we do for control addresses?

**Comment by anorth** [comment]
@nicola we can do that.

**Comment by nicola** [comment]
I really like your second idea, but maybe we should just make it simple first and then improve it. I agree with the risk of the miners making mistakes, we should make sure that the client won't make mistakes or that will ask twice, or will ask them to produce a test signature before submitting on chain.

**Comment by anorth** [comment]
I am going to attempt to implement the two stage version, but if it proves at all more complicated than we expect, I'll fall back to the direct one.
