### ISSUE TITLE
Repair state of miners broken by upgrade/fault collision #1100

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1177]
On testnet, a few miner actors have been broken when they encountered the condition described in #1100. They account for about 6PiB of testnet power.

While delicate, we believe it's possible to repair these miners' states so they can resume operation, assuming the operators have retained their sectors. This repair involves a state migration, implemented alongside an epoch-triggered network upgrade. The repair does not require changing actor code, so could be performed in-place before the network upgrades all the way to v2 (though we might want to run it again at that time to catch any new cases).

Decision about whether to resolve this with an in-place upgrade or with v2 is pending, but doesn't affect the work of creating and testing the algorithm.

**Comment by anorth** [comment]
@acruikshank done?

**Comment by acruikshank** [comment]
Yep it's done and tested. Seems to work.
