### ISSUE TITLE
Multisig actor review

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#1185]
Currently:

* `InitialBalance` can be set to be _greater_ than the current balance, both in the constructor and in `LockedBalance`. This isn't a huge issue, but is a bit funky. Effectively, it acts as a funky alternative to `StartEpoch` and delays vesting.
* If `StartEpoch > 0` but `UnlockDuration == 0`, vesting is not enabled. Personally, I'd expect all funds to vest immediately on the `StartEpoch` in this case.
* We remove the pending transaction, even if it fails to apply. I assume this is intentional, right?

**Comment by Stebalien** [comment]
cc @anorth

**Comment by anorth** [comment]
Thanks.
- The first item is by design, so that vesting can be configured before balance is deposited with the actor
- Yeah, `UnlockDuration == 0` as a sentinel is a bit unfortunate, may be worth changing, but could be tricky to change safely
- Yes, that is intentional

**Comment by Stebalien** [comment]
Ok, makes sense. It's probably not worth touching anything at this point.
