### ISSUE TITLE
Runtime interface is unclear on error handling

### ISSUE THREAD

**Issue by frrist** [filecoin-project/specs-actors#12]
The comment on the below methods state that an error should be "thrown".
https://github.com/filecoin-project/specs-actors/blob/9cb147a6275ae0688c434ee7c603bbdd743dc96a/actors/runtime/runtime.go#L35-L50

I believe the intent here is to use go's `panic()` and `recover()` methods as an exception mechanism, this is a break from traditional error handling in go. Due to this, I propose we instead follow a pattern like the [`ActorErrors`](https://github.com/filecoin-project/lotus/blob/75db4576f58471adbdf1214b9c66a512b5bbe0aa/chain/actors/aerrors/error.go) one used by lotus.
cc @anorth

**Comment by anorth** [comment]
The interface is now more clear, with only a single `Abort` mechanism and better documentation.

I'm closing this issue. It remains possible for us to change from this mechanism to explicit error propagation in the future, but is not urgent.
