### ISSUE TITLE
Multithreaded Migration test

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1214]
We should exercise the multiple worker goroutines case for a state migration in unit or scenario tests.  The current scenario test blockstore is not threadsafe so we expect upping the worker count there to panic.

**Comment by anorth** [comment]
@ZenGround0 done?

**Comment by ZenGround0** [comment]
Yes.  Note that in addition to running with multiple threads we also run multiple *migrations* concurrently to demonstrate the MigrateStateTree call is threadsafe (important for lotus operations).  And we're running the race detector during tests and as part of CI to guard against issues.
