### ISSUE TITLE
correctForCCUpgradeThenFaultIssue can set negative deadlines

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/specs-actors#1216]
Strictly looking at the code [here](https://github.com/filecoin-project/specs-actors/blob/bdd876b3bbe9f0558b7ef97190750103adbdd463/actors/migration/miner_corrections.go#L80-L84), it certainly seems like we can try to run `expectedDeadlline := uint64((epoch - st.ProvingPeriodStart) / miner.WPoStChallengeWindow)` with `epoch <  st.ProvingPeriodStart`, which would lead to bad things.

I don't know if some higher-level structure would prevent this from happening in the live network, but I ran into this in a devnet.

**Comment by ZenGround0** [comment]
@arajasek @Stebalien's recent change introduced [this](https://github.com/filecoin-project/specs-actors/blob/bdd876b3bbe9f0558b7ef97190750103adbdd463/actors/migration/miner_corrections.go#L35) check which should always prevent this from running when `epoch < st.ProvingPeriodStart`

**Comment by arajasek** [comment]
Nice, thanks! I was running a couple commits behind `master`. Probably safe to close this.
