### ISSUE TITLE
Power actor deleteClaim does not decrement MinerCount

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/specs-actors#1228]
StoragePowerActor stores the number of miners in its `MinerCount` field. This number can also be derived (inefficiently) by counting all entries in its `Claims` lookup. When a miner's cron errors, we delete the miner's claim from `Claims` to prevent the miner from taking further actions that might cause additional state corruption. We do not decrement the `MinerCount` in this case even though we have one less active miner.

This issue is low impact. `MinerCount` is not used in any actor calculation (`MinerAboveMinPowerCount` is updated appropriately), and it will only deviate from the number of claims if something unexpected goes wrong in a cron task (something we'd very much like to avoid). Checking that MinerCount matches the size of Claims would be a nice consistency check, but we can't rely on it without this.

**Comment by anorth** [comment]
@acruikshank should the fix for this be accompanied by a migration function to fix any inconsistent state?

- Fix `deleteClaim`
- Migration to recalculate `MinerCount` from claims
- State validation to check that `MinerCount` matches count of claims

**Comment by acruikshank** [comment]
The power state correction migration is #1265. This should either be combined with that or it should be run before. #1265 could be run before and after if migration timing necessitated it, but hopefully they can be run together.
