### ISSUE TITLE
power.CreateMiner does not update MinerAboveMinPowerCount for test proofs

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/specs-actors#1232]
When power actor updates claims, it increments/decrements the MinerAboveMinPowerCount if the power has crossed the ConsensusMinerMinPower threshold for the actor's seal proof type. Power actor does not do this when it creates the initial claim as it creates the miner. The initial claim has zero power, so this is only an issue if the miner has a seal proof type that has zero ConsensusMinerMinPower. Currently this is only true for the test proof type `RegisteredSealProof_StackedDrg2KiBV1` which is generally not permitted.

Potential solutions:

1. Update MinerAboveMinPowerCount in create miner if the value is above the threshold.
2. Choose a non-zero ConsensusMinerMinPower for RegisteredSealProof_StackedDrg2KiBV1.

**Comment by anorth** [comment]
Thanks, let's do (1).
