### ISSUE TITLE
Add batched SectorPreCommit (FIP-0008)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1241]
When a miner is going to commit many sectors in a small span of epochs, much gas usage could be saved by a batched invocation.

Note that in order to be effective, nodes will need to group pre-commit invocations, perhaps across a few epochs.

This is described in [FIP-0008](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0008.md) (discussion #25)

**Comment by anorth** [comment]
I'm splitting this in half to separate pre-commit and prove-commit. We already have a form of prove-commit batching, though we currently verify proofs charge gas as if proof verifications were not in fact batched.

**Comment by anorth** [comment]
The FIP is being drafted in https://github.com/filecoin-project/FIPs/pull/27.

**Comment by anorth** [comment]
Update: this work needs to wait for a batched prove commit first.

**Comment by BigLep** [comment]
@anorth @ZenGround0 : given the PRs are merged, I'm closing this issue.  Please reopen if there is more work.
