### ISSUE TITLE
Make state validation checks robust to errors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1244]
State validation checks are typically used in tests or by manual operation on network state. If there's an error because some part of state is unreadable (e.g. corrupted bitfield or HAMT node), then we want to know this but don't want it to prevent getting any other information about unrelated state. So treating these errors in the standard Go way by propagating them immediately isn't so helpful.

Re-arrange existing state checks to avoid returning errors at all. Translate errors from low-level functions into messages, skipping dependent checks where necessary.

**Comment by ZenGround0** [comment]
@anorth how is this doing after #1242? Anything remaining?

**Comment by anorth** [comment]
I did this only for the miner actor. I think the pattern is good, and should be replicated to the other ones.
