### ISSUE TITLE
Add b̶a̶t̶c̶h̶e̶d̶ aggregated SectorProveCommit endpoint

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1257]
Sector prove-commits are already batched and processed at the end of each epoch via a cron call in the power actor. This might not be the best solution, though. It's complicated, can't reliably batch across epochs, and each ProveCommit invocation still mutates state etc.

It might be simpler and more effective to expose a ProveCommitBatch method, giving miners explicit control over batch size and direct exposure to the true gas cost.

**Comment by ZenGround0** [comment]
This has mutated into the very similar "Aggregated PoRep".  Prototype PR #1381
