### ISSUE TITLE
epochsPerYear definition problem

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/specs-actors#1264]
https://github.com/filecoin-project/specs-actors/blob/4baf4d4b44d0ba6d9c78f95d5e20a4c95ee07fd1/actors/builtin/sector.go#L16
should be:
const epochsPerYear = 365 * EpochsInDay
https://github.com/filecoin-project/specs-actors/blob/4baf4d4b44d0ba6d9c78f95d5e20a4c95ee07fd1/actors/builtin/network.go#L23
should be:
const EpochsInDay = 24 * EpochsInHour

**Comment by ZenGround0** [comment]
Closed in #1259 yay!
