### ISSUE TITLE
Add gas accounting to scenario test VM

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1266]
Gas is mostly a thing that happens outside the direct control of the actor code, in the VM, so the gas table etc are not part of actor code. However, gas usage is the critical resource that actor code execution consumes, so we should have good tooling to inspect, benchmark, and profile it. We expect to be putting quite significant effort into improving and optimising gas performance in the near term, so should be able to quantify our changes.

To this end, let's add gas tracking to the VM used for scenario tests so that we can replicate and analyse gas usage traces.

Scenario tests might then include an assertion about total gas usage, forcing explicit recognition and review of any changes.

**Comment by anorth** [comment]
The scenario VM now has accounting for puts, gets, and bytes written/read, from which the storage-related parts of gas cost can be computed. It would still be good to go all the way, but we have a good part of the benefit already now.

**Comment by ZenGround0** [comment]
We are mostly there but will need to go all the way to unlock test vector generation and conformance testing

**Comment by BigLep** [comment]
@ZenGround0 : when we pick this work up, I assume we'll update it with the work plan.  This is what we captured last week:

Generation side (what we share with implementation)
1. Modify reference VM to deal with gas. (5 days)
 - Need the gas costs for all of the operations.
 - This is a module in Lotus that needs to be extracted (at least the constants)
2. Generate test vectors from the spec actors VM.  Add a new call to the VM and modify the internals to include the before/after of the state. Needs to include runtime like the epoch (5 days)
3. Test flags variable which would would cause VM to generate these.
4. Modify existing tests to call in the special way. (2 days)
5. Every time generate and store the hash.  This is hooked into CI. (1 days)
