### ISSUE TITLE
there can be problemsadd  in addFaults 

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/specs-actors#1272]
Comparing the following code 
L869 add   **test Error!**

     if len(newFaultSectors) == 0 {
              return NewPowerPairZero(), NewPowerPairZero(), NewPowerPairZero(), false, nil
     }

https://github.com/filecoin-project/specs-actors/blob/903e84f2245c703829b21171356a7fc9d9d7bba3/actors/builtin/miner/partition_state.go#L870-L873
https://github.com/filecoin-project/specs-actors/blob/903e84f2245c703829b21171356a7fc9d9d7bba3/actors/builtin/miner/partition_state.go#L259-L265

**Comment by zgfzgf** [comment]
--- FAIL: TestDeadlines (0.12s)
    --- FAIL: TestDeadlines/post_with_unproven,_faults,_recoveries,_and_retracted_recoveries (0.01s)
        bitfield_test.go:26: 
            	Error Trace:	bitfield_test.go:26
            	            				bitfield_test.go:30
            	            				deadline_state_test.go:612
            	Error:      	Should be empty, but was [1]
            	Test:       	TestDeadlines/post_with_unproven,_faults,_recoveries,_and_retracted_recoveries
            	Messages:   	unexpected bits set
        deadline_state_test.go:616: 
            	Error Trace:	deadline_state_test.go:616
            	Error:      	Should be true
            	Test:       	TestDeadlines/post_with_unproven,_faults,_recoveries,_and_retracted_recoveries
--- FAIL: TestWindowPost (0.34s)
    --- FAIL: TestWindowPost/skipped_recoveries_are_penalized_and_do_not_recover_power (0.04s)
        mockrt.go:662: unexpected PoSt verification
                    : {[10 11 12 13] [{5 [112 114 111 111 102 48]}] [{0 107 bagboea4b5abcbmvmmvwiq55tk2dk4qmq5msqnov4j6ky2hulmtaksatrny6jonhl} {0 108 bagboea4b5abcbmvmmvwiq55tk2dk4qmq5msqnov4j6ky2hulmtaksatrny6jonhl}] 1000}
            expected: {[10 11 12 13] [{5 [112 114 111 111 102 48]}] [{0 108 bagboea4b5abcbmvmmvwiq55tk2dk4qmq5msqnov4j6ky2hulmtaksatrny6jonhl} {0 108 bagboea4b5abcbmvmmvwiq55tk2dk4qmq5msqnov4j6ky2hulmtaksatrny6jonhl}] 1000}
        mockrt.go:662: goroutine 245 [running]:
            runtime/debug.Stack(0xc0001d9800, 0xa8d3b9, 0x36)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).failTest(0xc001900f00, 0xa8d3b9, 0x36, 0xc0000d2ee0, 0x2, 0x2)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:1093 +0x98
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).VerifyPoSt(0xc001900f00, 0xc0000c1ea0, 0x4, 0x4, 0xc0000bff80, 0x1, 0x1, 0xc00006bc40, 0x2, 0x2, ...)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:662 +0x24a
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.verifyWindowedPost(0xb2bda0, 0xc001900f00, 0xc08, 0xc00931f8f0, 0x2, 0x2, 0xc0000bff80, 0x1, 0x1)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_actor.go:2061 +0x375
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1()
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_actor.go:471 +0xa2b
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).StateTransaction(0xc001900f00, 0xb1eb40, 0xc007f32e00, 0xc009211c70)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:542 +0xb8
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt(0xb2bda0, 0xc001900f00, 0xc00006c480, 0xa6b940)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_actor.go:375 +0x1f4
            reflect.Value.call(0x9c7940, 0xc0000ce090, 0x13, 0xa6c947, 0x4, 0xc0001a7708, 0x2, 0x2, 0x9df1c0, 0xc0000c84c0, ...)
            	/usr/local/go/src/reflect/value.go:475 +0x8c7
            reflect.Value.Call(0x9c7940, 0xc0000ce090, 0x13, 0xc0001a7708, 0x2, 0x2, 0x60, 0x58, 0xa32340)
            	/usr/local/go/src/reflect/value.go:336 +0xb9
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).Call(0xc001900f00, 0x9c7940, 0xc0000ce090, 0x9df1c0, 0xc00006c480, 0x0, 0x0)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:1062 +0x293
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner_test.(*actorHarness).submitWindowPoSt(0xc007f32540, 0xc001900f00, 0xc00e578900, 0xc009211b30, 0x1, 0x1, 0xc00904bca0, 0x2, 0x2, 0xc0001a7df0)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_test.go:4897 +0x11af
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner_test.TestWindowPost.func6(0xc0001d9800)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_test.go:2027 +0x6d0
            testing.tRunner(0xc0001d9800, 0xc00908e7c0)
            	/usr/local/go/src/testing/testing.go:1127 +0xef
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1178 +0x386
        mockrt.go:323: unexpected send to: t04 method: 3, value: 0, params: &{2048 2048}
        mockrt.go:323: goroutine 245 [running]:
            runtime/debug.Stack(0xc0001d9800, 0xa8dfd0, 0x38)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).failTestNow(0xc001900f00, 0xa8dfd0, 0x38, 0xc00006bd00, 0x4, 0x4)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:1100 +0x98
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).Send(0xc001900f00, 0xc00002754c, 0x2, 0x3, 0xb18b60, 0xc00931f980, 0xc0000d3160, 0xb1e980, 0xe369e8, 0x0)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:323 +0xcff
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.requestUpdatePower(0xb2bda0, 0xc001900f00, 0xc0000d2900, 0xc0000d2920)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_actor.go:1988 +0x13e
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt(0xb2bda0, 0xc001900f00, 0xc00006c480, 0xa6b940)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_actor.go:484 +0x22e
            reflect.Value.call(0x9c7940, 0xc0000ce090, 0x13, 0xa6c947, 0x4, 0xc0001a7708, 0x2, 0x2, 0x9df1c0, 0xc0000c84c0, ...)
            	/usr/local/go/src/reflect/value.go:475 +0x8c7
            reflect.Value.Call(0x9c7940, 0xc0000ce090, 0x13, 0xc0001a7708, 0x2, 0x2, 0x60, 0x58, 0xa32340)
            	/usr/local/go/src/reflect/value.go:336 +0xb9
            github.com/filecoin-project/specs-actors/v2/support/mock.(*Runtime).Call(0xc001900f00, 0x9c7940, 0xc0000ce090, 0x9df1c0, 0xc00006c480, 0x0, 0x0)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/support/mock/mockrt.go:1062 +0x293
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner_test.(*actorHarness).submitWindowPoSt(0xc007f32540, 0xc001900f00, 0xc00e578900, 0xc009211b30, 0x1, 0x1, 0xc00904bca0, 0x2, 0x2, 0xc0001a7df0)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_test.go:4897 +0x11af
            github.com/filecoin-project/specs-actors/v2/actors/builtin/miner_test.TestWindowPost.func6(0xc0001d9800)
            	/home/zgf/gopath/src/github.com/filecoin-project/specs-actors/actors/builtin/miner/miner_test.go:2027 +0x6d0
            testing.tRunner(0xc0001d9800, 0xc00908e7c0)
            	/usr/local/go/src/testing/testing.go:1127 +0xef
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1178 +0x386
FAIL
FAIL	github.com/filecoin-project/specs-actors/v2/actors/builtin/miner	34.787s

**Comment by ZenGround0** [comment]
Thanks for filing, taking a look now

**Comment by ZenGround0** [comment]
@zgfzgf your add test code is incorrect because it short circuits which prevents p.removeRecoveries from ever running.  The tests are correctly catching your bug.

The correct way to skip adding faults when newFaultSectors is nil is like this:

```golang
// Record new faults
	powerDelta = NewPowerPairZero()
	newFaultPower = NewPowerPairZero()
	if len(newFaultSectors) != 0 {
		powerDelta, newFaultPower, err = p.addFaults(store, newFaults, newFaultSectors, faultExpiration, ssize, quant)
		if err != nil {
			return NewPowerPairZero(), NewPowerPairZero(), NewPowerPairZero(), false, xerrors.Errorf("failed to add skipped faults: %w", err)
		}
	}
```

And this causes all miner tests to pass.

Meta note -- thanks for taking the time to file issues, it is awesome to get more eyes on this code and to be alerted to possible errors.  However it is not helpful if the errors you report consistently turn out to be simple misunderstandings.  Please spend a bit more time understanding the code and making sure that the bugs you report are legitimate.  This way we will continue to take your reports seriously and can respond rapidly when you find real bugs.

**Comment by zgfzgf** [comment]
@ZenGround0 
I see.
Thank you very much.

**Comment by anorth** [comment]
Please do ping us on slack if you have questions about how things work, maybe we can resolve them with less effort for everyone. filecoin.io/slack
