### ISSUE TITLE
Pre Migrations

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1285]
We need to reduce migration times during upgrade epochs.  A nice idea from @Stebalien is to migrate actors in the background in the node during the hours leading up to the upgrade epoch.  Then when the actual migration runs it can read from a cache and skip migrating actors which have not changed since they were premigrated.

This will involve making MigrateState tree aware of caching and potentially writing another endpoint for premigration.  Since it is threadsafe we can likely just use two invocations of MigrateStateTree aware of caching.

**Comment by ZenGround0** [comment]
@anorth @Stebalien some thoughts on premigrations

## Simple solution

A simple first solution is to do per actor caching. To do this we could add a new argument to `MigrateStateTree`.  This argument will be an interface representing a per actor cache. Conceptually (and maybe concretely) it is a map from actor address to a pair of cids: the actor's state Head before and after the migration. The migration code checks an actor address before migrating. If it is in the cache migration code checks the pre-migration head cid. If it matches that actor's head in the current tree then the migration code just writes the second cid from the cache entry into the actor's Head field in the new tree.  Actors not found in the cache or that have a stale pre-migration head in the cache run through a full migration and then write back the pre and post migration state heads to the cache.

With this cache approach the lotus caller can run a long pre-migration to completion and populate a cache and then during the migration itself run another migration using the cache to use previously migrated actor cids to speed up the migration.

I'm expecting the lotus caller to implement the cache and handle resource management and persistence. There are about 100,000 actors in the filecoin state tree currently.  ID addresses are around 4 bytes, cids around 38 bytes putting the cache at (38*2+4)*100000 = 8MB which should be reasonable to keep entirely in memory during the main migration.  To avoid lots of memory overhead we might want to adapt a strategy of persisting the cache after populating it at first and then only loading it to memory soon before the migration starts.

# Feasibility Evaluation

We should investigate the feasibility of this approach. We should do this once we have the next migration written and we have profiled it on mainnet state.  One problem I foresee preventing this simple approach from working well is that all of the interesting actors with the most data to migrate will be constantly churning. Past migrations saw the majority of runtime taken up by loading all sectors in active miner actors. These are a small number of actors making up ~1% of all actors.  In the best case they will all update their `CurrentDeadline` index 60 epochs before the migration. In practice these minimal updates will be spread evenly among the 60 epochs before migration. Also the biggest miners with the most sectors data to migrate will likely be churning with other operations (i.e. precommit and prove commit) up to the migration.

## More advanced solution

If we verify that churning actors cause the majority of migration time we could extend the caching idea to try to isolate large subtrees of actor state with less churn.  If the Sectors AMT is the bottleneck we could add another cache object for miner actor sectors AMT roots.  Conceptually this cache would be a map from unmigrated AMT root cid to migrated AMT root cid. When a miner actor address is not found in the actor cache and we migrate the miner actor the migration code will perform a look up on the Sectors AMT root cid cache to attempt to use work from a pre migration.

We could extend this approach to all actor subtrees that take a significant portion of migration time assuming that they churn less frequently then top level actor state. It is unclear if this is a good assumption. It might be the case that miners with the most sectors in their sectors AMTs are expected to be prove committing right up to the migration epoch in which case this would not work.

**Comment by anorth** [comment]
Done in #1346
