### ISSUE TITLE
Deprecating DeclareFaults

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1287]
DeclareFaults is "rationally deprecated" because calling it will result in more fees for a miner than just missing one post over the partitions with faults. It would be great to explicitly remove fault declaration code.  Some things to consider before doing this.

1. Do we anticipate wanting to reintroduce fault declaration as a concept in the protocol in the near to medium term for other reasons @nicola @zixuanzh? My guess is no but if there is some chance of this we should just keep the status quo.
2. What is the best approach for deprecating a method number? We have an opportunity to figure deprecation out generally working towards a full policy to close #346. A first idea here is to map the DeclareFaults method number to nil in a new actors major version and leave a comment on the actors export table that this is a deprecated method number.  This prevents method number reshuffling which we really want to avoid. And when the node receives a message attempting to invoke this method after upgrade the nil check [here](https://github.com/filecoin-project/lotus/blob/master/chain/vm/invoker.go#L76) will result in a SysErrInvalidMethod error.  @Stebalien any reasons this wouldn't work or other preferences here?

**Comment by zixuanzh** [comment]
No, I think we should keep Declare Faults to not overly penalize miners who need to migrate their clusters, swap out their disks, or perform other operational tasks. FIP2 rationally deprecated DeclareFault as a tradeoff to increase tolerance for honest WindowPoSt failures with minimal code changes. In the medium and long term, there should still be the ability for a miner to honestly declare faults.

**Comment by zixuanzh** [comment]
I think we should keep Declare Faults to not overly penalize miners who need to migrate their clusters, swap out their disks, or perform other operational tasks. FIP2 rationally deprecated DeclareFault as a tradeoff to increase tolerance for honest WindowPoSt failures with minimal code changes. In the medium and long term, there should still be the ability for a miner to honestly declare faults.

**Comment by anorth** [comment]
I think there's a reasonable chance of re-introducing fault declarations as rational in the medium term.
