### ISSUE TITLE
/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.12/actors/builtin/sector.go:88:14: p.RegisteredSealProof undefined (type abi.RegisteredPoStProof has no field or method RegisteredSealProof)

### ISSUE THREAD

**Issue by oldkingclub** [filecoin-project/specs-actors#1300]
/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.12/actors/builtin/sector.go:88:14: p.RegisteredSealProof undefined (type abi.RegisteredPoStProof has no field or method RegisteredSealProof)

**Comment by anorth** [comment]
Please use [v0.9.13](https://github.com/filecoin-project/specs-actors/releases/tag/v0.9.13).
