### ISSUE TITLE
Allow publishing deals using control addresses

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/specs-actors#1317]
Currently PublishStorageDeals requires deals to be published from miner worker address:

https://github.com/filecoin-project/specs-actors/blob/51482ab9f7aeb57bc778ad607046b04f41792cfa/actors/builtin/market/market_actor.go#L184-L185

We could also allow control addresses here to give miners more flexibility

**Comment by anorth** [comment]
Sounds good.

The market actor restricts one other action to the worker address: withdrawing funds. The recipient of the withdrawal is always the miner owner address, but the worker is allowed to trigger it. Should we also allow control addresses to request withdrawal? Let's file a new issue if so.
