### ISSUE TITLE
Publish valid deals in PublishStorageDeals message

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/specs-actors#1375]
Currently the market actor [validates each deal](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_actor.go#L203), if one of the deals fails validation, [the whole message fails](https://github.com/filecoin-project/specs-actors/blob/57195d8909b1c366fd1af41de9e92e11d7876177/actors/builtin/market/market_actor.go#L756). One of the validation is checking if the deal's [start epoch has already passed](https://github.com/filecoin-project/specs-actors/blob/57195d8909b1c366fd1af41de9e92e11d7876177/actors/builtin/market/market_actor.go#L756) and due to network's mpool congestion issue, it is possible that by the time a _PublishStorageDeals_ message lands on-chain, the deal has already expired even though the message was sent beforehand.

It would be nice to only fail the invalid deals and have the valid one to be published successfully.

**Comment by jennijuju** [comment]
@dkkapur Could you please add the link to the FIP discussion or FIP itself once created?

**Comment by ZenGround0** [comment]
FIP discussion happening here: https://github.com/filecoin-project/FIPs/issues/142

**Comment by ZenGround0** [comment]
Closed by https://github.com/filecoin-project/specs-actors/pull/1487
