### ISSUE TITLE
Why need a ConsensusFaultElapsed?

### ISSUE THREAD

**Issue by hoplover** [filecoin-project/specs-actors#1393]
In `ReportConsensusFault`, there exist a `ConsensusFaultElapsed` that protect the miner not to be slashed during this time. And the time lasts for a whole `ChainFinality`, does it make sense? On one hand, a bad miner can mine lots of blocks during this duration, he will never be punished, which causes a safety problem. On another hand, it's not hard to just record slashed epoch to avoid a double slash problem in tech.

**Comment by Stebalien** [comment]
That actually defines the period of time in which the miner _cannot_ mine. This restriction is enforced in lotus, not specs-actors.

> On one hand, a bad miner can mine lots of blocks during this duration, he will never be punished, which causes a safety problem.

Note: The safety/correctness analysis of Filecoin doesn't actually rely on slashing. My understanding is that this feature mostly helps the chain converge faster.
