### ISSUE TITLE
Update v5 params

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1433]
## Finalized

Change max aggregate batch size to ~800
Change MaxProveCommitDuration to 30 days
Max aggregate proof size --  aggregate proof size for 819 sectors * 2 = 40,980*2 = 81,960
Change max precommit batch size to 256

## Unfinalized

Min aggregate batch size -- waiting on gas estimations to determine smallest batch size with gas savings compared to multiple ProveCommits

**Comment by BigLep** [comment]
Related to https://github.com/filecoin-project/FIPs/pull/100

**Comment by BigLep** [comment]
For tracking, we also recently adjusted parameters here: https://github.com/filecoin-project/specs-actors/issues/1415
