### ISSUE TITLE
Add more logs

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/specs-actors#1500]
More add-on logging suggestion to https://github.com/filecoin-project/specs-actors/pull/1477

- Log the reason why a burn was taken. (would be nice to have sector id as well)
- Log the deal id and the reason why it failed validation in `validateDeal`

**Comment by jennijuju** [comment]
- balance movement between miner states balances like  vesting, locked, available balance and fee debt.

**Comment by ZenGround0** [comment]
> Log the deal id and the reason why it failed validation in validateDeal

This is already on master with latest publish storage deals error handling fip.  Only miner balance movements are left.

**Comment by laudiacay** [comment]
merged 👯‍♀️
