### ISSUE TITLE
ProveCommitReplicaUpdate implementation for SnapDeals

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/specs-actors#1511]

**Comment by ZenGround0** [comment]
## Description

specs-actors needs a new miner actor method for triggering a snap deals update on an empty sector.  The specification for this is found in the above link.  At a high level this method needs to take in and validate an input specifying snap deals updates and proofs that they have been done successfully.  It then needs to carefully change the miner actor state to account for updated sector information and power.

## Done criteria

1. The minimal done criteria is the `ProveCommitReplicaUpdate` method being written to spec and past review.
2. Ideally one test checking the happy path should accompany this PR.  Further tests of many edge cases can follow along.

## Dependencies

This PR has no dependencies.

## Ongoing work

In review here: https://github.com/filecoin-project/specs-actors/pull/1529
