### ISSUE TITLE
Actors Testing -  that will  be used to validate changes we made for SnapDeals implementation

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/specs-actors#1513]

**Comment by arajasek** [comment]
Add a test for insufficient pledge when it goes up

**Comment by arajasek** [comment]
Check that in the happy path, your sector still gets faulty if post missed, and still gets recovered and such

**Comment by arajasek** [comment]
Add a test that actually has a batch -- some sectors in the same partition, others not.

**Comment by arajasek** [comment]
Test that sectors are still extensible and terminatable.

**Comment by arajasek** [comment]
@jennijuju asks:

now seems like we removed ReplaceCapacity  completely, what will happen if:
having aa sectors thats a replacement for a cc upgraded sector
done precommit
network upgraded
what will have for proveupgrade?
will the sectorkeyinfo be added to this new sector during migration?

**Comment by arajasek** [comment]
Add to `TestFullPathSuccess`


	// TODO: miss a post, lose power
	// miss another, get slashed
	// submit post, recover

	// TODO: update another sector, and immediately miss post, lose power
	// submit post, recover

**Comment by arajasek** [comment]
More for TestUnhealthySectorFailure

More variants: testing that unproven, and terminated sectors fail.

**Comment by anorth** [comment]
@Kubuxu do you have testing points to contibute?

**Comment by arajasek** [comment]
Closed in #1552, though more tests welcome
