### ISSUE TITLE
Alias structs from previous actors versions

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/specs-actors#1524]
We should go through gen/gen.go and alias those structs from previous versions that we can. This applies to v7, as well as some stragglers from earlier versions.

**Comment by ZenGround0** [comment]
This is all about rolling over from v6 to v7 and not so much snap deals.  For this reason I am removing from the board.  This will still be important for the final upgrade releasing snap deals, however it falls in the same category as other ongoing work currently being merged into `next`

**Comment by arajasek** [comment]
VerifyDealsForActivationParams is one such
