### ISSUE TITLE
SnapDeals SectorKey

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1530]
## Description
The complete implementation of snap deals involves adding a "sector key" to the sector info on chain.  This new field is responsible for tracking the commR of the original sealed replica of the sector.  Maintaining this onchain will unlock the future capability for multiple snap deals updates using the same committed capacity space.  This is important for maintaining an upgrade path for future snap deals updates that is uniform across all sectors and therefore simple to design and code.

## Done criteria
* A PR passes review that adds this new field to the sector info and does the required recording of the original commR during snap deals updates.

Non-criteria
* the migration needed to enable this in networks upgrading from v6 is tracked elsewhere
## Dependencies
* https://github.com/filecoin-project/specs-actors/pull/1529

## Ongoing work

Not yet started

**Comment by arajasek** [comment]
Closed in #1529
