### ISSUE TITLE
multisig approve transaction failed.

### ISSUE THREAD

**Issue by dengpan1** [filecoin-project/specs-actors#1569]
under  the calibration network, with 2-3 multisig addresses, proposal and approval can succeed, the transaction information is as follows:
[create a multisig address](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzaceanmquqz3zgvljuvf5mnauo5qrampmyagm74paqekjfs2yzbxlvse
), [proposal transaction](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzaceaczgb4cotx2yap54mxwgqnosjpeztxw52ptywtxtwijob3fx6zys), [approval transaction
](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzacecbvfvdds6ka2yzs33rsfe6crc26zr2b6mme2qkglxqwattwtpkiu)

but when I try to use 9-9 multi-signature addresses, the proposal transaction succeeds ,but the approval transaction fails. the transaction information is as follows:
[create a multisig address](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzacedn73lnp2myzvge7mvvuwb7xqhbd6wmh4vs527sbd6i6s7peru7ts), [proposal transaction](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzacecmh3y36rmqo7ua3nurxrt2ttrc32erebpdgjjts3zwm5ybohc466), [approval transaction](https://calibration.filscan.io/tipset/message-detail?cid=bafy2bzaceauxskaurief55qcqhqzswm3lh3uolyss72ww5jxycgq7sgo5er3i) (It failed.).

error message is: `hash does not match proposal params (ensure requester is an ID address) (RetCode=16)`,
2-3 can succeed, 9-9 why failed, my code is the same.

**Comment by Stebalien** [comment]
This issue tracker is not actively monitored for questions. Please ask on Filecoin Slack or in the lotus discussions: https://github.com/filecoin-project/lotus/discussions.
