### ISSUE TITLE
Make Go context available to actor methods

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#16]
Because Go, we will need to provide a context.Context to some method calls (e.g. HAMT library), so we should at least use a consistent one that could possibly be useful. Two options:
- provide as first argument to all actor methods
- provide one from the Runtime interface

The latter is less noise. Not canonical Go, but I think a VM presents a reasonable case for deviating.

**Comment by anorth** [comment]
And should require that context as an argument to calls like IpldGet/Put and Send()? Probably.

**Comment by Kubuxu** [comment]
The primary reason for adding context to Runtime for us in Lotus was tracing.
In all the other cases you are fine passing `context.Background()` or any other context.
All of these context steam from the fact that HAMT can be backed by for example bitswap.

**Comment by anorth** [comment]
Sure, tracing is a great reason. I think we should do something useful since we have to do something.

**Comment by whyrusleeping** [comment]
putting it in the runtime seems fine to me

**Comment by anorth** [comment]
Closed in #21
