### ISSUE TITLE
Are `System` and `BurntFunds` a special address, or special actors

### ISSUE THREAD

**Issue by icorderi** [filecoin-project/specs-actors#165]
Meaning, are they just a well-known address or do they need a corresponding special code CID too?

**Comment by icorderi** [comment]
cc: @anorth

**Comment by whyrusleeping** [comment]
They should just be normal account actors, no need for anything special here.

**Comment by anorth** [comment]
We ended up with a system actor code, but burnt funds is just an account at a known address.
