### ISSUE TITLE
Signed integral type for ChainEpoch

### ISSUE THREAD

**Issue by igor-egorov** [filecoin-project/specs-actors#167]
Hi

It looks like there is no need to have `ChainEpoch` be defined as `int64` since it is not going to be set to a negative number.

I would like to hear from specs maintainers if we could safely change this to `uint64` in the specs-actors repo?

https://github.com/filecoin-project/specs-actors/blob/5ea8e57dba25ae0fddbce89c6b6ca1bdf0ab2c1a/actors/abi/primitives.go#L13

**Comment by anorth** [comment]
At present this is an explicit decision, though we acknowledge that there are advantages and disadvantages of each approach.

The reasons for `int64` for both chain epoch and a clock-time type (in block header):
- We don't need all 64 bits
- It is common to use subtraction when doing arithmetic with measures of time, and signed numbers "just work" here while unsigned need easy-to-forget underflow checks (e.g. [here](https://github.com/filecoin-project/specs-actors/blob/74b45ccaaff95ad6b19c481d972cc5c453aa2c2b/actors/builtin/market/market_state.go#L395))
- Allows the use of -1 as an undefined value (but see https://github.com/filecoin-project/specs/issues/874)
- non-negative values serialize the same in CBOR anyway

We do use uint64 in many places where we don't expect any arithmetic (i.e. enums), or at least no use of subtraction (sector size).

**Comment by igor-egorov** [comment]
Thanks for the detailed answer!

I agree - easily enabled arithmetic seems the definite advantage of the current approach.

A potential issue could happen when a negative number different from -1 gets transmitted over the network. Probably we can treat any x where x < -1 as -1 when it comes from the net.
