### ISSUE TITLE
Committed Capacity Upgrading

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/specs-actors#173]
Given that before we have upgrade-able proof in Filecoin, upgrading a CC sector will have to go through the same InteractivePoRep. To reuse much of the machinery we currently have, here are the steps to upgrade a CC sector,

- PublishStorageDeals as usual
- PreCommit/ProveCommit as usual with an additional associated CC sector specified to convert into a regular sector with deals (through sector number)
- Pledge collateral for the CC sector remains unchanged. However, more pledge collateral might be required from deal reward for mainnet. For interop, pledge collateral remains unchanged but it is likely that pledge collateral requirement here will go up.

**Comment by whyrusleeping** [comment]
Let's do this one after we get the new pledge stuff merged in

**Comment by ianjdarrow** [comment]
FWIW, we're gearing up to include this in testnet incentives if it's available. We need it operational by 15 May to have enough time to add it to the incentive leaderboard tooling & give miners enough time to operationalize it.

**Comment by anorth** [comment]
Implemented in #398, but untested.
