### ISSUE TITLE
TokenAmount Improvments

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#175]
1. Helper functions that allow easy conversion between whole FIL and attoFIL values.
2. Helper functions for pretty printing and parsing attoFIL and whole FIL string representations.
3. Consider renaming `TokenAmount` to `AttoFIL` which has the functional benefit of immediately describing the units of the value without needing to look it up.  If there are strong dissenting opinions then at least we should change the documentation to describe that TokenAmount is an AttoFIL representation.  cc @anorth and @whyrusleeping for any weigh in here.

**Comment by anorth** [comment]
I do *not* think we should add helper functions for conversion to whole FIL units in this repo (tho implementations may well do so in their UI). The "FIL" idea lives purely at the human level and has no fundamental place in the protocol. Including any code for it opens up room for error, which I think we can simply avoid.

I have the same feelings (but weaker) about pretty-printing in human-friendly terms, and also about renaming it, for the same reasons.

**Comment by ZenGround0** [comment]
First paragraph + pretty printing sounds 👌 to me.

I disagree that these reasons applies to naming because the units of measure are semantically essential to the meaning of the type as used by the specs actors code.  The unit of measure needs to be consistent across callers.  The protocol recognizes 1 token (fil) and 1 indivisible unit of token (attofil) and callers of the actor code must treat `TokenAmount` as the second one.

**Comment by anorth** [comment]
Ah, my mind natively equates "token" with "indivisible". We shouldn't call 10^18 tokens a token.

**Comment by anorth** [comment]
@ZenGround0 what are your thoughts now, a few months later?

**Comment by ZenGround0** [comment]
@anorth looks like 1 and 2 don't belong here since we do everything in terms of attoFIL.  I still prefer changing the type name. 
 While I agree 10^18 tokens shouldn't be called a token from first principles it is everywhere in the crypto-currency space and removing confusion about monetary units for people new to this repo is only positive from my perspective.

That said this hasn't been an issue for developing in this repo since its a pretty easy convention to learn.

With that I'll leave the decision up to you.

**Comment by anorth** [comment]
I'm closing this now, primarily because a rename would be a significant burden to our consumers, and it's not causing us any problems at the moment.
