### ISSUE TITLE
Remove MinerCount from StoragePowerActor state

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/specs-actors#181]
Hi,
StoragePowerActor defines [MinerCount](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/power/power_state.go#L19) to be stored in the state. It seems to be redundant since it can be get with HAMT from Claims or EscrowTable. At least there is [ForEach in map interrface](https://github.com/filecoin-project/specs-actors/blob/master/actors/util/adt/map.go#L97) which can be used to iterate all records to count them.

**Comment by Alexey-N-Chernyshov** [comment]
Also it seems that there are `TotalNetworkPower` and `NumMinersMeetingMinPower` variables in the state that are not being set anywhere.

**Comment by anorth** [comment]
The miner count seems logically redundant, but the HAMT doesn't export a `Size()` or `Count()` method. @whyrusleeping would this be something easy to add, and compute in constant time? We don't want to iterate the values to count them.

The total power and miners meeting min power are more complicated (see #266).

**Comment by anorth** [comment]
I think we'll leave this here (in fact, possibly add another)  #266.
