### ISSUE TITLE
Add 'CheckSectorProved' method to miner actor 

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs-actors#189]
In order to allow for a trustless PoRep outsourcing market, we only need a single method on the miner actor that returns exit code 0 if the referenced sector is proven, and returns a nonzero exit code if the sector has not been proven.

This will also require that 'ProveCommitSector' can be called by anyone (which is fine) so that the prover can submit the proof on their own.

The final choice in the design space is a timeout, we can add the timeout as a parameter to the method we're adding here (which is fine because the prover cannot change the method parameters since they are signed over by the payer) or we can generalize it and add a timeout field to the payment channel itself. I'm actually a fan of having the payment channel have a timeout field, as this is also needed for cross chain atomic swaps.

cc @magik6k @jbenet @arajasek

**Comment by anorth** [comment]
Closed by #199
