### ISSUE TITLE
Restrict init actor exec's ability to create singleton actors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#219]
#218 relaxed the init actor's constraints on what actors can be instantiated freely too much, e.g. allowing user-creation of reward actor, system actor etc. Switch to either an explicit capability list (rather than exclusion list), or more exhaustively enumerate the exclusions such that it won't rot in the future.

**Comment by whyrusleeping** [comment]
appears to be properly handled here: https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/init/init_actor.go#L88

**Comment by whyrusleeping** [comment]
Ah, I see, its just missing some entries.
