### ISSUE TITLE
Seal randomness must include miner address as entropy

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#260]
The miner actor computes seal randomness with no entropy. It must use the miner address according to   https://github.com/filecoin-project/specs/pull/883

cc @sternhenri @magik6k

**Comment by sternhenri** [comment]
This would be to prevent miners with the same worker key from sharing the seal though I actually assume some of the details of how sealing works could make this unnecessary (it certainly wouldn’t hurt though). 

Can you confirm/deny @whyrusleeping ? I’ll amend specs PR accordingly or PR specs-actors (depending).

**Comment by whyrusleeping** [comment]
Not sure *why* this is really needed, the randomness doesnt really have to be unique, just has to be not known before some point in time. But if the spec says it, its easier to implement than to argue at this point.
