### ISSUE TITLE
Publish successive deals fails (possible incorrect assertion in SMA market_state)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/specs-actors#265]
Issue: Publishing deals fails because market.State.updatePendingDealStatesForParty fails, if a miner has an existing deal that has been sealed but has not reached the StartEpoch in the proposal.

Steps to reproduce:
1. Publish a deal for a miner, put StartEpoch far in future, activate storage deal after sealing, but before StartEpoch.
2. Publish a second deal for the miner, which calls market.State.updatePendingDealStatesForParty which fails on the assertion here: https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_state.go#L110 -- which seems incorrect -- a sector may be proved and activated before the StartEpoch?

Lotus experiences has assembled a failing test based on this issue: https://github.com/filecoin-project/lotus/pull/1481

**Comment by whyrusleeping** [comment]
I think this was fixed in #309, but need to confirm

**Comment by aarshkshah1992** [comment]
@whyrusleeping @anorth 

This code path dosen't exist anymore (`updatePendingDealStatesForParty`) and I don't see any code in the current master that would cause a failure like this.

I've written a test for this in #560. Please can you take a look ?
