### ISSUE TITLE
Change to open-ended faults rather than up-front duration.

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#272]
In the current spec/actors, temporary faults are declared along with an expiration epoch at which the fault is automatically considered repaired. a miner should be able to extend a fault declaration by submitting a new, overlapping one, though the actor code doesn't currently allow that.

- the neat thing about this approach is that the fault fee is paid in advance, and so unavoidable (although quite likely to be over-paid).
- the rough thing is that it's very difficult for miner code to predict how long a fault should generally last. while there will be some real world cases like migrations, more code will be written for the less obvious cases. right now, I think both impls are just making a wild-ass guess, which will then require delicate monitoring logic to ensure the fault is re-declared as it approaches expiry.

Both the node operational code and the actor code will be simpler, and hence more likely correct, if fault durations are not required up-front. This would require a miner to explicitly declare a sector as recovered. I predict this would be less chain traffic than the re-declaration of extended faults.

The catch is to ensure that fees are actually paid in order that an indefinitely-long faulted sector eventually costs more than just declaring it terminated. The easy thing would be to pay the fee on fault recovery, but that's not quite enough. So instead we could perhaps calculate and burn fees on every windowed PoSt?

Since we have to re-write the fault representation anyway to make it efficient, and the testnet has already been running with open-ended faults, I propose we make this change.

**Comment by sternhenri** [comment]
> The catch is to ensure that fees are actually paid in order that an indefinitely-long faulted sector eventually costs more than just declaring it terminated. 

well doesn't a sector get terminated after x proving periods anyway? In that case, we don't need "indefinitely-long faulted sector", just for x PPs. After that, termination happens.

**Comment by anorth** [comment]
Resolved by #286.
