### ISSUE TITLE
ADTs should support multiple operations between flushing

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#278]
The ADT wrappers around HAMT, AMT flush on every mutation. This is much more expensive than necessary for repeated mutations.

We should change their interfaces to support batch operations, either through explicit flushing or a batching construction.

**Comment by anorth** [comment]
See also #539 about using a cheaper hash function for intermediate updates.

**Comment by anorth** [comment]
If taking this on, please circulate a proposal and seek some ideas before turning to code.

**Comment by aarshkshah1992** [comment]
@Stebalien Would the IPFS data store batching API be an inspiration here ?

**Comment by Stebalien** [comment]
We already have buffers although I guess we could have a write buffer? (not sure).

The real issue here is that we're serializing/deserializing intermediate IPLD blocks when we don't need to.

**Comment by aarshkshah1992** [comment]
@ZenGround0 @acruikshank @Stebalien I'd like to this up. Any concerns ?

**Comment by aarshkshah1992** [comment]
Update:

Changes have been made to the Market, Multisig, VerifReg and Power actors for this.
Other actors save the Miner actor don't have this problem.

@anorth @ZenGround0 Should we consider closing this issue ?

**Comment by anorth** [comment]
Yes. There are more gains to be had, but they generally involve diving into the HAMT/AMT internals, or just using different structures or access patterns at a higher level.
