### ISSUE TITLE
Actors near-term development plan

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#33]
This issue describes our near-term plan for spec actor development. The goal is an executable and tested set of actors to run in the next major testnet release. This functionality is expected to be our candidate for mainnet, with the exception of some parameter choices.

The code in this repo has been extracted from https://github.com/filecoin-project/specs, where it was incomplete and not executable. It implements some different (generally more complicated/sophisticated) behaviour than those in the current testnet. We expect to import some testnet learnings and simplify this code while completing the implementation and tests.

*Plan overview*
1. [x] Extract the code from specs to actor-code repo.
1. [x] Package as a module suitable for import into Go implementations
1. [x] Clean up runtime API between actors + implementations (initially written without implementation costs/constraints in mind)
1. [x] Fill in gaps
    - [x] Relatively mechanical stuff like HAMTs, etc.
    - [x] Design gaps and unspecified behaviour
1. [ ] Change (simplify) some behaviours, in discussion with the implementation teams
1. [ ] Develop test harness & write extensive tests

This list is not strictly sequential. In particular testing will be concurrent with completing and modifying the implementation.

**Comment by mishmosh** [comment]
| Actor  | Code Complete? | Tests Complete? | Integrated to gfc? | Integrated to lotus? | People & Notes |
|---|---|---|---|---|---|
| SystemActor |   |   |   |   |   |
| InitActor |   |   |   |   |  |
| RewardActor |   |   |   |  |   |
| CronActor |   |   |   |   |  |
| StoragePowerActor |   |  |   |   |   |
| StorageMarketActor |   |  |   |   |   |
| BurntFundsActor |   |   |  |   |   |
