### ISSUE TITLE
Extend Deal Expiration

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/specs-actors#330]
We currently allow for sector expiration extension in miner_actor but we should also allow for extension of deals in the sector. Will work on the specification.

**Comment by anorth** [comment]
This isn't actionable here at the moment. Deal extension should come as a FIP. I'm closing this until we have a concrete proposal with some agreement.

The concept of deal extension is not new. It's likely that we can achieve the same product goals by making a new deal for the same data.
