### ISSUE TITLE
zero BlockReward to following blocks in a tipset  

### ISSUE THREAD

**Issue by steven004** [filecoin-project/specs-actors#358]
# Description:
Miners got 0 block rewards when their blocks are not the first ones in tipsets. 
For example, this can be seen in [filscan.io](https://filscan.io/#/tipset?height=7555)  
![image](https://user-images.githubusercontent.com/10411723/81470947-5f145c00-9220-11ea-921f-56c4510f5093.png)

# Possible Cause: 
- `AwardBlockReward` method of RewardActor is invoked when each block in a tipset is applied, and every time `computePerEpochReward` is invoked, in which `st.SimpleSupply` and `st.BaselineSupply` are set; 
- When there are two blocks in one tipset, the second block will re-compute EpochReward, but it will subtract the previous one, which is exactly the same as this one since there are at the same epoch, then the second block get 0 block reward. 

# Suggestion: 
1. For each epoch, only need to compute blockReward once;
2. st.SimpleSupply and st.BaselineSupply might be wrong when re-org happens, there should be a mapping, and do calculation when necessary.

**Comment by anorth** [comment]
Fixed in https://github.com/filecoin-project/specs-actors/pull/366
