### ISSUE TITLE
PostSubmissions in MinerActor should change the type

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/specs-actors#396]
Now [PostSubmissions](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_state.go#L79) records successful PoSt submission in the current proving period by partition number.

but here:
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_actor.go#L1095

the result of  failRecovery  will not  not match the real failRecovery

so,`PostSubmissions *abi.BitField` shoud change to `PostSubmissions [WPoStPeriodDeadlines]*abi.BitField`

**Comment by magik6k** [comment]
You have to prove all partitions within a deadline successfully, this field only records successful posts per deadline.

I'm not sure if there are any security implications to changing this, but if there aren't then it's definitely something we'd want

**Comment by waynewyang** [comment]
@magik6k I think we should record all sectors successful posts,If not, there will be such a phenomenon. A certain deadline  contains some faults sectors ,but the miner will obtain all the power of all sectors

**Comment by anorth** [comment]
I don't fully understand the request, but I think there may be a misinterpretation of the state.

- We don't record PoSt success per sector (it would be too large), only per partition. PoSt can only succeed when the state also records any declared faulty sectors in those partitions, so power is accounted correctly.
- Partitions are numbered sequentially per-miner, not per deadline. A miner with enough sectors has a single partition numbered 2, they do not have a partition 2 in deadline 0 and a different partition 2 in deadline 1. There is only one partition 2. The partitions are numbered left-to-right across the deadlines.

The change proposed in #397 seems to be interpreting the partition numbers as being per-deadline, but that's not the intention. Given that understanding, can you re-state the problem you see, if it's still there?

Separately, while investigating this, I discovered an error I made in #388 that messes up the partition-numbering logic: #404.

**Comment by anorth** [comment]
@waynewyang could you please indicate if there's still a problem here, given the interpretation I described above? If not, let's close this issue.

**Comment by waynewyang** [comment]
@anorth no problem.
