### ISSUE TITLE
Partition assignment logic is buggy

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs-actors#402]
Somehow miners are getting more sectors than the limit assigned to a given deadline. For example, in block bafy2bzaceamzy2qpoanxusxwzorsz2kp4zjrn43mfkgi7me2ickyuyyoi6vgk of the testnet, miner t0212888 has 2386 sectors in deadline 0.

**Comment by GFZRZK** [comment]
I think that's happened in place which issue #396 mentioned, just use randomness in this function can quickly fix it

**Comment by GFZRZK** [comment]
> Your sectors are supposed to get all assigned to the same deadline, up until the limit, which is 2349. This is by design. The bug here is that its assigning more than 2349 to the same deadline.

I think we're talking about the same thing. if you check the function I mentioned there carefully, you will find that If you can't create more than 2349 sectors in a period, there will never ever sector be assigned to any other deadline.

**Comment by GFZRZK** [comment]
think about the first time you fill the limit, then your code will come to https://github.com/filecoin-project/specs-actors/blob/8ab252fac3b79e5555d246f21151b45c8937a328/actors/builtin/miner/deadlines.go#L214
It will assign remain sectors into the first deadline, then you can find that you will never get any sectors to be assigned to other deadlines.

**Comment by anorth** [comment]
Yes, I think I see this. If you had more than a whole partition worth of `newSectors` then some of them would go to the second deadline, but generally each time round this will fill a new partition in the first deadline. As the comment immediately above that line says, the intention is to fill less-full deadlines first. Without fully solving the problem, a simple sort of the deadlines by partition count, and round-robin over _that_ sequence, would practically solve what you're observing here.

**Comment by anorth** [comment]
Closed in error, PR #426 fixes a different issue.
