### ISSUE TITLE
Add an "addresses" field to the MinerInfo data structure

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#403]
This would reduce reliance on the DHT to find miners. Miners could include addresses like `/dnsaddr/super-big-miner.me`, or even direct IP addresses like `/ip4/a.b.c.d/tcp/1234` if their IP doesn't change frequently.

**Comment by Stebalien** [comment]
Specifically,

```go
type MinerInfo struct {
	PeerId peer.ID
 	Addresses []ma.Multiaddr
...
}
```

**Comment by whyrusleeping** [comment]
Implementer note: This also requires methods to set the addresses field.

**Comment by frrist** [comment]
Cbor-gen doesn't support slices of interfaces yet ([code here](https://github.com/whyrusleeping/cbor-gen/blob/64967432584da50b86d78fc9bc343c7c7afa50d2/gen.go#L398-L453)). Would a slice of strings be appropriate?

**Comment by Stebalien** [comment]
It should be a slice of byte arrays for minimal encoding.

**Comment by Stebalien** [comment]
Or we can use a custom type:

```go
type Multiaddr struct {
  ma.Multiaddr
}
// implement decoding logic.
```

**Comment by frrist** [comment]
@Stebalien I can't add you as a review in this repo, but the PR is here if you wanna give it a look: https://github.com/filecoin-project/specs-actors/pull/427
