### ISSUE TITLE
Tie PoRep and PoSt proofs to a single chain

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#407]
This is a placeholder issue for work to be done to ensure that proofs cannot be valid on more than one chain (because DRAND randomness is shared by all forks). A probable solution is to add a signature over a block header to proof submissions (which requires a runtime mechanism to validate that signature, etc).

**Comment by anorth** [comment]
I'm removing this from the Feature Freeze milestone for now because we have no action, and it seems at least moderately possible that the underlying issues will be solved a different way than using a block header signature.

FYI @nicola @whyrusleeping

**Comment by nicola** [comment]
Although we are looking at the alternatives, they are not looking positive at the moment, will update here asap.

**Comment by nicola** [comment]
This is currently being done here: https://github.com/filecoin-project/specs-actors/pull/680/files

**Comment by anorth** [comment]
Closed by #908
