### ISSUE TITLE
Use chain-height rather than epoch based lookbacks for things related to finality

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#408]
Add a `CurrentChainHeight` call to the runtime (a peer of `CurrentEpoch`), and use this for lookbacks that are logically related to finality (e.g. for sampling randomness).

Note a possible follow-on to also define the progress of Window PoSt proving periods similarly.

**Comment by whyrusleeping** [comment]
@nicola mind weighing in here? This is a fairly significant change that I havent seen a proposal for yet, i'm thinking that at this point its not going to happen.

**Comment by anorth** [comment]
@whyrusleeping @nicola do you have any update here? I am considering removing this from our Feature Freeze milestone since we can't act on it, but want to hold it here if you think this is still the direction we'll move.

**Comment by nicola** [comment]
We did not have time to look into this. I know that @whyrusleeping has a specific reason for which this is already happening, but I did not understand it. From the doc in the research issue, this is still a valid concern.

**Comment by anorth** [comment]
We're not doing this any time soon, so I'm closing this issue for now.
