### ISSUE TITLE
Power/penalty calculation for large fault sets or termination is too expensive

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#411]
The penalty for a sector missing a PoSt depends on per-sector state (specifically, sector quality/deal weight). When a miner goes AWOL and misses many PoSts, calculating the penalty for thousands or millions of sectors is an unreasonable performance cost and blows out block validation time. This is similarly a problem if a large number of sectors terminate at the same epoch, which is a likely, even desired outcome otherwise, since expiries are constrained to proving period boundaries (see #357).

A similar problem happens when miner is terminated. Also similarly, power calculations depend on the same information. While detected faults are the scariest case, this also limits ability to declare faults.

- Recording the per-partition quality/power on chain may help
- For termination, there may be some amortization possible to spread the load.

**Comment by davidad** [comment]
I discussed with @nicola and others in Slack on April 16 a solution approach based on a (relatively) straightforward modification to the PoSt aggregation SNARK. Essentially, the faulting miner does the work of calculating how much power they've lost (rather than all the chain verifiers doing that computation independently), and SNARKing it makes it easy to verify without digging through lots of data.
> Currently the verifier is getting from the SNARK a bitmap of which sectors were proven, and you want to do a popcnt and multiply by a fixed fee per sector. The upgrade would be to (also) get from the SNARK a total power number, and multiply by a fixed fee per unit power.

**Comment by nicola** [comment]
Possible ideas: bundle sectors with similar expiration with the same deadline and slash an entire deadline even if there is a single fault (very aggressive ideas here - do not consider if not useful)

**Comment by Stebalien** [comment]
Discussed with @anorth in a call:

Observation: Faults will usually cover a few sectors, a few partitions, or an entire miner.

Proposal: Therefore, we can memoize per-sector, per-partition, and per-miner power and update these powers whenever the miner faults:

* When a miner declares a fault for a sector (or a few sectors), we can load state for those specific sectors. At the end of the proving period, we'll need to load `NUM_BAD_SECTORS * NUM_PARTITIONS` to update each partition's power.
* When a miner fails to submit a proof, we can fault the entire partition without loading the power for each sector.
* When a miner fails to submit _any_ proofs for the day, we can simply fault the entire miner's power without loading any additional state.

However, I'm going to need to dig a bit more. I assume we need to remove power immediately, but we also need to keep faulting these sectors some number of times before declaring them faulty, right?

**Comment by davidad** [comment]
> Faults will usually cover a few sectors, a few partitions, or an entire miner.

I recall thinking about something similar when this problem was first raised, but someone pointed out that a miner _could_ (intentionally?) fault all but a sparse handful of sectors in every partition, and that ought not to DoS chain sync. I don't have much of an opinion about how much this possibility matters, but wanted to make sure it isn't forgotten.

**Comment by Stebalien** [comment]
That should be fine as long as we can limit the number of simultaneous faults (charge miners gas for every N faults).

**Comment by nicola** [comment]
(Note that ongoing proposal may require some faults handling (skipped and declared and some termination faults) to happen at wpost submission.)

**Comment by anorth** [comment]
Moving this out of the queue in favour of #599, which should resolve it.
