### ISSUE TITLE
Power actor EnrollCronEvent doesn't handle enrolments for events in the past

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#413]
The `EnrollCronEvent` method does no validation of the epoch for which an event is enrolled. If it's at or prior to the recorded `LastEpochTick` then the event will never be executed and will remain in state forever. Events are stored in a HAMT keyed by epoch, which does not support ordered traversal.

A simple solution might be to require the registered epoch to be after the current epoch. However at present it is possible for a registration to be in "the past" when there is a long chain halt (greater than a proving period) from the miner actor, which steps its proving period marker forward one period at a time via cron events.

A workaround-style solution might be to change how the miner actor registers for proving period callbacks, ensuring registrations are always in the future, even when catching up from a long halt. This seems brittle, though, and easy to accidentally introduce a new case that might require an in-the-past registration (I haven't audited other cases yet).

Another possible path out is switching all such callback mechanisms to use chain height (#408), which will never have gaps or null rounds.

I think a robust solution would be to change the cron events table representation to an AMT, and always traverse it in order from beginning up to the current epoch. The event callbacks must then be robust to being called at an epoch later than they registered, but that's necessary anyway to handle empty tipsets.

**Comment by acruikshank** [comment]
Another solution would be to to rename `power.State.LastEpochTick` to something like `power.State.EarliestCronTask` and lower it when a cron task gets set in the past. We already iterate the epochs between this and `currEpoch` to make lookups in the HAMT. It could mean some more wasted reads in the worst case, but is simple to implement.

I'm concerned that an AMT will quickly become unbalanced with when we're mostly deleting off the front of it. Whether this would be better or worse than the wasted reads will depend on how many null blocks and enrollments in the pat we expect.

**Comment by acruikshank** [comment]
#659 is a draft of the proposed solution above (actually ready to go if approved).
