### ISSUE TITLE
Defer power reduction on declared faults to WPoSt deadline

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#414]
At present, when a miner declares a fault they lose power immediately. This introduces an incentive to defer declaration as late as possible, but not so late as to risk missing the fault declaration cutoff.

It would be better for the fault declaration to simply register the declaration, and process it (cutting power) only when the Window PoSt deadline for the sectors in question arrives. This would likely simplify fault declaration overall, though require some additional accounting in state.

**Comment by irenegia** [comment]
fine with the windowPoSt analysis 
CC @nicola

**Comment by nicola** [comment]
(we are tracking this here in parts: https://github.com/filecoin-project/research-private/issues/240)

**Comment by ZenGround0** [comment]
@anorth DeclareFaults is deprecated from an incentive perspective with actors v2 behavior of no penalty for first missed post.  If miners follow incentives and just miss a post for any partition with faulted sectors their power will be removed on deadline anyway.  Do you think we can close this?

**Comment by anorth** [comment]
Yes, we can re-open if it becomes relevant again.

**Comment by irenegia** [comment]
>DeclareFaults is deprecated from an incentive perspective with actors v2 behavior of no penalty for first missed post.
This is not 100% true. Because of how much power it is removed, it is still rational for a miner who has a partition with < 30% sectors faulty to declare all the faults (less power lost compensates for the higher penalty). 

(It is fine to close this issue, I was just nitpicking to avoid the spreading of partially wrong intuitions) :)
