### ISSUE TITLE
Implement verification of locked pledge requirements on PoRep and PoSt

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#415]
A miner must maintain locked pledge collateral equal to the sum of the initial pledge for all sectors (to cover potential fees from failing all PoSts and having sectors terminated, though because block reward is dynamic, this isn't a strong guarantee).  The pledge requirement should be checked upon the explicit miner worker messages of ~submitting a PoSt and~ proving a new sector commitment, and withdrawing unlocked balance.

There's a placeholder function unimplemented for this. Note that the call site for sector commitment was jumbled in the implementation of batched porep verifications, and should probably move back to be in the explicit miner-initiated call path (PreCommitSector), rather than in cron.

**Comment by davidad** [comment]
IIUC, the current plan is _not_ to verify pledge collateral requirements on every PoSt. I'm not against it, just want to have clarity about whether this is a forgotten requirement, an outdated stub, or (effectively, at least) a still-open design parameter.

**Comment by zixuanzh** [comment]
Yes, I am not against it either but I believe it this came from a requirement in previous pledge design. We only need to verify that a miner has sufficient total locked fund that is greater than the sum of initial pledges for all active sectors when they declare recovery. When a miner is slashed with insufficient locked funds to cover the slash, the miner will be terminated and removed.

We only need to check that the miner is putting up the right amount of InitialPledge for a sector during Commit.

**Comment by anorth** [comment]
> the sum of initial pledges for all active sectors

We don't actually record the initial pledge for each sector in state, but I am inferring that maybe we should.

There's an unanswered (un-asked) question here: are fees for a sector fault in terms of _that sector'_s initial pledge, or in terms of initial pledge that would be calculated if that power was committed at the epoch of the fault. The latter could be either larger or smaller, since they are calculated in terms of instantaneous block reward which can move in either direction.

Doing everything in terms of _that sector's_ initial pledge makes it much easier to ensure that the pledge would in fact cover all fees to be paid.

> We only need to verify that a miner has sufficient total locked fund that is greater than the sum of initial pledges for all active sectors when they declare recovery

A recovery actually takes effect during the PoSt submission, so I think we still need to check this on PoSt. Maybe this means that the required locked balance is only that of the non-faulty sectors? But that probably isn't right, b/c then if all sectors faulted once, the required balance would go to zero but there are still lots of fees to be paid.

**Comment by anorth** [comment]
Resolutions:
- No need to verify locked pledge requirements on Window PoSt
- Do need to verify when committing a new sector
- Must verify before withdrawing unlocked balance too

**Comment by anorth** [comment]
Implementation will need to add a miner state variable that is the sum of initial pledge for all sectors, to avoid traversing all sectors to calculate it. Add when the pledge is locked up after successful proof, and subtract on termination.
