### ISSUE TITLE
Quantize sector pre-commit expiry epochs to avoid per-sector cron registration

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#417]
When each sector is pre-committed, a cron event is registered for the expiry of that precommit, which penalises a miner for failing to follow through. This creates a huge load of cron registrations in state, and processing in the tipset cron handler. For high-scale miners, many events per epoch. Most of the events are for naught, but can't be unregistered when the proof arrives on time.

This load could reduced by quantizing the epochs at which expiries are processed, and using a single cron event per miner per quanta which checks all the pre-commits due for proof before the event. The existing proving-period event might be a suitable entry point. It doesn't matter much if it's quite infrequent: a late-arriving proof is already rejected. This is just cleaning up state.

The precommit sector IDs for processing could be stored either in a queue-like `AMT[epoch]Bitfield`, perhaps quantized (like `FaultEpochs`)

**Comment by whyrusleeping** [comment]
We could just keep a bitfield of the sectors we need to check in the miner state, and check it on that miners proving period tick. Since its just cleanup, it seems fine to have this happen only once per day.

Additionally, this lets us remove items from that bitfield as the precommits actually get proven, minimizing the work we have to do here.

**Comment by anorth** [comment]
If we only store the ids, we'll have to load the corresponding precommit infos to check the expiry, while the queue structure avoids that until we know they will expire. If the allowed delay is long (how long is it?), we'd load the same precommits frequently only to have no action. 

A day's worth of sectors can be large (limited to 128K at present), so if we load them, we really want to be able to expire them. It's  too many to load in an only-daily cron.

So I think the bitfield approach is limited by:
- If the pre-commit delay is long, then many precommits can accumulate without expiring
	- If we check them frequently, we load them many times redundantly
    - If we check them infrequently, too many accumulate to be reasonable to load in a single cron call

If the delay is short, it's probably ok. But it would be better not to bake in performance assumptions on that. A future proof algo may have a much larger allowed delay. I think the queue avoids both of those problems, and allows us to tune the frequency of checking to trade batch size against queue length.

Removing precommits when proven is great, and we can do that in any case.

Note that the cron tick is likely to move to per-deadline (#552), but that should hopefully only make things better.

**Comment by anorth** [comment]
@whyrusleeping, @aarshkshah1992 will take this over. I trust you don't have code WIP for it yet.
