### ISSUE TITLE
Miner actor MinerInfo filed should be a CID.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/specs-actors#423]
This change requires making `Miner#State#Info` a cid of the miner Info struct so it's not re-written when other fields change. A TODO for this change exists here: https://github.com/filecoin-project/specs-actors/blob/155bd9fef33d170c783c72fe7ab14951ce8a6741/actors/builtin/miner/miner_state.go#L29

**Comment by anorth** [comment]
@ZenGround0 just beat you to it. Duplicate of #422
