### ISSUE TITLE
Fix CC upgrade not to double-count power, avoid fault penalties, or expire early

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#430]
The implementation of committed-capacity sector upgrading [missed some things](https://github.com/filecoin-project/specs-actors/pull/398#pullrequestreview-424052116).

- Update the sector expiration queue (see also #429)
- Terminate old power before adding new power
- Handle the pre-upgrade sector being faulty
- Don't add to NewSectors unless sector is removed from existing deadline (which is probably not an option)

**Comment by anorth** [comment]
Now that I've had a little time to think about this implementation, I think a different approach would be simpler and better.

The current attempt is structured as upgrading a sector in place. Most of the errors inadvertently introduced are the result of not handling the termination of the "old" CC sector before introducing the new one to replace it. It also interacts poorly with the batch PoRep verification optimization, which defers many checks like deal validity and pledge balance to an end-of-epoch cron callback rather than the miner's call path (#431), which makes handling them very difficult.

We could do a bunch of refactoring to structure the upgrade code to effectively follow the termination and then new commitment flows, but with special handling e.g. to avoid adding to NewSectors again. But I think it would be simpler to _actually just use another sector_. We can treat the "upgrade" as a license to terminate an empty sector before due without paying any penalties. This results in
- only one sector lifecycle flow, with no cycles
- static correspondence between sector id and CommR/CommP, deals, and on-disk data

In implementation, I think this would amount to attaching the ID of a CC sector to terminate when a new deal-ful sector is PreCommitted, and actually terminating that sector as an on-time expiry when the new PoRep is verified.

One minor downside of this approach is that allocating new sectors ids will make it slightly harder for miners to get good bitfield packing in proving sets. Replacing a contiguous run of already-committed sectors IDs in-place would give slightly better packing than removing them and appending a new run for the new sectors.

FYI @zx @nicola

**Comment by magik6k** [comment]
I like this approach a lot.

> One minor downside of this approach is that allocating new sectors ids will make it slightly harder for miners to get good bitfield packing in proving sets

I can modify the miner software to use separate ID ranges for CC sectors and for sectors with deals. This way when performing a CC upgrade, it's fairly easy to keep ranges continuous

**Comment by anorth** [comment]
Thanks. In that case, I will roll back the upgrade-in-place PR and we'll prepare to re-do it with this approach.
