### ISSUE TITLE
The mining power is permanently dropped but there are no expired faulty sectors

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/specs-actors#448]
We detect a serious power drop issue. The mining power is permanently dropped but there are no expired faulty sectors. This issue can happen when: 
1. The miner once had some faulty sectors. And these sectors should be expired now. If he has recovered all of these sectors, this issue still happens.
2. The miner has some faulty sectors now.

### Issue A
In RemoveFaults() of actors/builtin/miner/miner_state.go, these code removes sector numbers from faults and fault epochs.

```
	for i, field := range changed {
		if err = arr.Set(i, field); err != nil {
			return err
		}
	}
```

If faulty sectors are all recovered, then the corresponding entry of AsArray have no sectors any more, but it is not removed.

### Issue B
Several days later, these faulty sectors are expired. Since they have been recovered, the expiration is not related to them.  However, in popExpiredFaults() of actors/builtin/miner/miner_actor.go, Code line A & B are still called because of Issue A.
```
	err := st.ForEachFaultEpoch(store, func(faultStart abi.ChainEpoch, faults *abi.BitField) error {
		if faultStart <= latestTermination {
			expiredFaults = append(expiredFaults, faults) // A
			expiredEpochs = append(expiredEpochs, faultStart) // B
		} else {
			ongoingFaults = append(ongoingFaults, faults)
		}
		return nil
	})
```
So expiredFaults are appended some empty values. In theory, it should be empty.  
But there is another issue. Let us see ForEachFaultEpoch().
```
// Iterates faults by declaration epoch, in order.
func (st *State) ForEachFaultEpoch(store adt.Store, cb func(epoch abi.ChainEpoch, faults *abi.BitField) error) error {
	arr, err := adt.AsArray(store, st.FaultEpochs)
	if err != nil {
		return err
	}

	bf := abi.NewBitField()
	return arr.ForEach(bf, func(i int64) error {
		return cb(abi.ChainEpoch(i), bf)
	})
}
```
 A BitField is made by abi.NewBitField(). It is allocated once but may be used several times in the following loop. This is a problem. If non-empty faults are appended to ongoingFaults, we can also see that faults are also appended to expiredFaults. However, currently there are not any expired fault sectors!

### Possible Solutions

For Issue A, we modify RemoveFaults() and delete empty fault sectors of the corresponding epochs in time.

```
	for i, field := range changed {
		fcount, err := field.Count()
		if fcount == 0 {
			if err = arr.Delete(i); err != nil {
				return err
			}
		} else {
			if err = arr.Set(i, field); err != nil {
				return err
			}
		}
	}

```
For Issue B, we modify popExpiredFaults() and use the below code to have a test. And then we can't see such issues any more.
```
		sbf := bitfield.New()
		faults.ForEach(func(snum uint64) error {
			// TODO: Performance & checking return values
			(&sbf).Set(snum)
			return nil
		})
		if faultStart <= latestTermination 
			expiredFaults = append(expiredFaults, &sbf)
			expiredEpochs = append(expiredEpochs, faultStart)
		} else {
			ongoingFaults = append(ongoingFaults, &sbf)
		}
```

**Comment by anorth** [comment]
Thanks for the report, I will investigate.

**Comment by marco-storswift** [comment]
// Iterates faults by declaration epoch, in order.
func (st *State) ForEachFaultEpoch(store adt.Store, cb func(epoch abi.ChainEpoch, faults *abi.BitField) error) error {
	arr, err := adt.AsArray(store, st.FaultEpochs)
	if err != nil {
		return err
	}

	bf := abi.NewBitField() 
       **//all the out faults is the same object. and the ForEach function just change the value**
	return arr.ForEach(bf, func(i int64) error {
		return cb(abi.ChainEpoch(i), bf)
	})
}

**Comment by anorth** [comment]
Got it, I will fix this by changing `ForEachFaultEpoch` to return distinct bitfields for each callback, since that's what all the call sites want anyway.

**Comment by coder-lb** [comment]
Great.

In ForEachSectorExpiration(), there are the similar usage. Will it be fixed, too?
