### ISSUE TITLE
Standard method for embedding CBOR-encoded objects inside others

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#453]
We have a few places where a CBOR object embeds another one where the inner object has varying type, and so can't be represented as a plain old struct. If we were talking about a language with generics, a field with generic type.

How should we encode the nesting?
- One way, currently in use for actor constructor params passed to `InitActor.Exec` and for the method parameters to `MultiSig.Propose`, is to represent the inner object as a `[]byte` in the outer. The outer thus has a consistent CBOR schema, but the nested object is opaque unless you know to interpret it as CBOR. Simple CBOR decoders and viewers should never have a problem with this, but probably won't automatically decode the nested object. We use the `CBORBytes` wrapper just to pass this already-encoded object to `Send`, avoiding redundant double-encoding.
- Another way, proposed in #434 for propagating the return value from a multisig actor's delegated transaction, is to embed the nested result _directly_ in outer struct. This means that the outer structure has a different CBOR schema depending on what the return value is. The `CBORBytes` object can then be used to decode the outer while ignorant of the inner structure. CBOR inspectors/viewers will probably traverse this embedded structure naturally. This is one byte cheaper than the first way.

In either case in practise, decoding will happen in two stages, once for the envelope, and then for the nested object. See also @ZenGround0's [description](https://github.com/filecoin-project/specs-actors/pull/434#discussion_r436100879), on which my notes above are based.

If deciding now, I would chose the first option, as the most natural, least surprising, and already implemented option, even though it costs a byte and misses out on auto-magic decoding by inspection-based CBOR viewers. In any case, I wish that we consistently use a single approach here across all such uses, so if we change, we change all of them.

@whyrusleeping your opinion would be valued here. 
cc @frrist

**Comment by anorth** [comment]
The real question is what bytes do we want on the wire. Using the deferred type is a specific coding approach to handling the second option above, where the nested object is embedded directly, rather than represented as a byte array.

Can I take from your comment that:
- you favour direct embedding rather than encoding the serialized nested object as a byte array?
- you concur with using this consistently everywhere we nest CBOR objects, including `InitActor.Exec` and `MultiSig.Propose`?

**Comment by whyrusleeping** [comment]
Are there cases other than Exec and Propose? Both of those feel slightly off to me in that their parameters are 'method arguments', which we have been treating as opaque byte arrays thus far. If we change those to be embedded objects, then the argument could be made to make the message type have embedded objects too, which I don't entirely like due to wanting to separate things inside the VM from things outside the VM

**Comment by ZenGround0** [comment]
> Are there cases other than Exec and Propose? 

This has come up while designing the encoding of the return value for the `Propose` message which we want to embed the return value of the proposed message.  So instead of 'method arguments' it is 'method return values', but it fits within the method call framework.

> If deciding now, I would chose the first option

> If we change those to be embedded objects ...  I don't entirely like due to wanting to separate things inside the VM from things outside the VM

This sounds like 2 votes for consistently encoding varying type objects as cbor bytes at least as long as they are objects used for I/O with other methods.  I prefer this too.

We should follow up on this issue with all the other places if any we encode varying type structures to understand why their types vary (anything other than method I/O?) and if we are consistently byte array encoding these types.

**Comment by anorth** [comment]
Ok great. @frrist could you please take this and alter #434 appropriately?

I checked all other usages of `CBORBytes` or `cbg.Deferred`, but they are all:
- when passing already-encoded parameters to `Send`
- when forced by use of HAMT `ForEach`, which exposes the `Deferred` used internally

**Comment by frrist** [comment]
I can. Just to make sure I understand the above -- the ask is to represent the inner object (called `Ret` in #434) as a `[]byte`, correct?

**Comment by ZenGround0** [comment]
> the ask is to represent the inner object (called Ret in #434) as a []byte, correct?

to my understanding yes

> Which, based on Zens comment, is a break from the protocol.

looks like our wires got crossed, using the cbg.Deferred is a break from the current convention, using a cbor byte array is standard.

**Comment by ZenGround0** [comment]
Clearing up some confusion I had: `cbg.Deferred` is the only way to do option 2 in the original comment.  The `CBORBytes` type actually does option 1.  Please see [this gist](https://gist.github.com/ZenGround0/18e8ffcab6e47af7eb6e21e76620940d) for more details. 
 Apologies for asserting the behavior of `CBORBytes` in PR without looking into it all the way.  Thanks @frrist for looking into this.

Note that none of this changes the outcome of the discussion above, it just clarifies some incorrect statements made along the way.
