### ISSUE TITLE
Enforce sector maximum lifetime, dependent on seal proof type

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#454]
Sectors have a maximum lifetime, governed by security of the PoRep. `ExtendSectorExpiration` does not yet enforce this.

- The sector maximum lifetime should be made a function of the seal proof (as is window post partition size).
- Initial committed lifetime should have a maximum value, for now = 1 year (in epochs)
- Each extension should also have a maximum of 1 year, bounded by the sector maximum lifetime.

This is probably an appropriate moment to refactor the "things that depend on seal proof" into a structure, rather than maintain many parallel mappings.

**Comment by acruikshank** [comment]
> Each extension should also have a maximum of 1 year, bounded by the sector maximum lifetime.

Is this saying that a sector can never live for > 1 year? Specifically given a .5 year old sector:

1. A .51 year extension fails but a .49 year extension succeeds.
2. A 1.01 year extension fails but a .99 year extension succeeds?

Sounds like 1 but I want to be clear.

cc @anorth

**Comment by acruikshank** [comment]
`PreCommitSector` doesn't seem to be making this assertion. Should it as part of this issue?

**Comment by anorth** [comment]
This is saying that:
1. For a 0.5yo sector, 1.01 year extension fails but a .99 year extension succeeds
2. For a 4.5yo sector, a 0.51y extension fails but 0.49 year extension succeeds

So a sector can live for at most the per-seal-proof-maximum, but be extended in at most 1y increments.

Yes, please add the same checks to PreCommitSector.
