### ISSUE TITLE
Enforced static analysis of probable bugs (e.g. ignored errors)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#456]
The linting currently enforced on the project is too weak. For example, there are a bunch of cases of ignored error return values which are easy to miss in development and review (e.g. #309, with no fewer than three approvals).

Implement much stricter static analysis and enforce increasing strictness in CI.

**Comment by ZenGround0** [comment]
I'm reproducing the lack of err check.  The weird thing is that CI appears to think it is doing the right thing: `Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck] `

**Comment by ZenGround0** [comment]
aha: things in directories called "builtin" are [skipped by default](https://github.com/golangci/golangci-lint/issues/343).

**Comment by anorth** [comment]
🤦
