### ISSUE TITLE
Assess removing DealState LastUpdatedEpoch field

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#463]
From builtin/market_actor.go:CronTick:

```golang
	// TODO: can we avoid having this field?
	state.LastUpdatedEpoch = rt.CurrEpoch()
```

Remove this if we can, otherwise note why it's necessary and close this issue.

**Comment by anorth** [comment]
Doing #421 would almost certainly mean we could remove it.

**Comment by aarshkshah1992** [comment]
@anorth 

We use the `LastUpdatedEpoch ` as a moving pointer to keep track of deal payments. An alternative is to maintain this particular information on the Market State itself as a H/AMT of [dealId]LastUpdatedEpoch. But, I'm not sure if that's a better way.

My suggestion is to remove this TODO and keep things as they are unless you disagree.

**Comment by anorth** [comment]
Ok, thanks. Please remove the TODO and close this issue.

**Comment by aarshkshah1992** [comment]
This is done in master.
