### ISSUE TITLE
Assess replacing SectorStorageWeightDesc by Power

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#466]
builtin/power_actor.go has the following TODO decorating four method params:
`// TODO: replace with power if it can be computed by miner` in reference to the params containing the type `[]SectorStorageWeightDesc`.  The methods are `OnSectorTerminate`, `OnFaultBegin`, `OnFaultEnd`, and `OnSectorModifyWeightDesc`.

From the TODO it is ambiguous if this is possible or the right thing to do.  Needs further investigation

**Comment by ZenGround0** [comment]
Potential duplicate of #419

**Comment by anorth** [comment]
Duplicate of #419
