### ISSUE TITLE
Sector Confirmation batch miner pledge updates

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#476]
From builtin/miner/miner_actor.go:ConfirmSectorProofsValid

```
// Add sector and pledge lock-up to miner state
// TODO: do this all at once after the loop
```

There is a lot going on underneath this code block so it's not obvious how much can be batched.  I think it is referring to the `notifyPledgeChanged` call which currently happens per sector and invokes a method on the storage power actor.  Perhaps it is also possible/good to batch the persector miner state mutations in the code block under this TODO.

**Comment by anorth** [comment]
Everything inside that loop should be batch-able, with appropriate batch functionality exposed on the state mutation methods.
