### ISSUE TITLE
Improve performance of miner.AddLockedFund, serialize as array

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#502]
Rough profiling indicates that the AddLockedFund method is the most significant sink of execution time outside of syscalls.

See this [profile snippet](https://gist.github.com/anorth/7e632d95518e9ae975f843b723380c23) from a devnet.

And from a different one
```
Average time spent in outside of syscalls per actor method:
t05-7 0.000111405
t04-11 9.31141e-05
t05-8 0.000307631
t04-13 0.000194394
t04-4 0.000269679
t01000-14 0.00131454
t02-2 0.000121549
t02-3 4.98606e-05
t01000-17 0.00367811
t02-4 0.000311329
t01000-4 0.000763825
t04-9 0.000201034
t01000-6 0.000491067
t05-5 0.000187442
t01000-7 0.000385646
t03-2 9.50445e-05
t04-10 0.000229153
```

FYI @whyrusleeping 

See also #464

**Comment by anorth** [comment]
Batching of updates from sector proof verification will probably reduce the impact of this quite a bit: #476

**Comment by anorth** [comment]
#445 may have some inspiration.

**Comment by ZenGround0** [comment]
Hey do we have a set of standard workloads (messages / chain data) for regenerating these traces?  I would love to be able to close this issue with a new performance report showing how the numerical improvements we've made.

Until we have a reference VM we'll need to run a full lotus node.  If someone points me in the direction of how to setup lotus network / chain car for generating perf traces I will gladly work through the details and write something up so the team can run performance tests while we develop.

cc @Kubuxu who I know has run these profiles in the past, @anorth @whyrusleeping

**Comment by Kubuxu** [comment]
@ZenGround0 I've used import bench (as Why shown your on slack) and then following script in bash:
```bash
jq '.[] |.Trace[] | .ExecutionTrace | recurse(.Subcalls[]?) | {To: .Msg.To, Method: .Msg.Method} as $call | [.GasCharges[] | select(.Name == "OnActorExec") | .tt] | add | "\($call.To)-\($call.Method) \(.)"' -r import-bench.json | grep -v null | awk '{seen[$1]+=$2; count[$1]++} END{for (x in seen)p2rint x, seen[x]/count[x]/1e9}
```

**Comment by Stebalien** [comment]
This has just gotten significantly (~48x) worse now that we unlock funds every deadline instead of once per proving period.

**Comment by Stebalien** [comment]
> This has just gotten significantly (~48x) worse now that we unlock funds every deadline instead of once per proving period.

This was wrong. We _have_ increased the vesting period, but we didn't change the quantization.

**Comment by anorth** [comment]
There are two quantities that vest: block reward and sector initial pledge. In a growing network, we expect many more sector commitments than blocks per epoch, so the initial pledge probably matters much more. That's also the value that's implicated in the original profile.

- There's some chance that requirements will/can change such that the initial pledge doesn't vest at all, but is just locked like the precommit deposit. That would immediately solve most of this problem.
- Otherwise, a coarse way to make this hurt less is to make the vesting less frequent

Some software engineering ideas we could apply to the problem, if we had time
- Accumulate all initial pledge lock-ups for a deadline and add them just once during deadline cron
- Fix AMT internals that write out too much data when few values are actually changed

**Comment by anorth** [comment]
Another idea: maybe an AMT isn't a great structure for this. Since keys are quantized and, when adding a new vesting value we usually re-write all of them, maybe it would be cheaper to use an array of tuples `(epoch, amount)`.

**Comment by anorth** [comment]
Plan for resolution:
- #757 for removing initial pledge from vesting.
- Serialize as an array of tuples instead of AMT
- Increase reward vesting quantization quite a bit, e.g. to 10-20 days (possibly shorten vesting cliff, which will implicitly increase by this amount)

**Comment by Stebalien** [comment]
> Serialize as an array of tuples instead of AMT
Can we serialize into an array and a start time? (save half the space?)
