### ISSUE TITLE
Sector expiration doesn't handle already-terminated sectors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#513]
The miner actor maintains a queue of sector expirations by epoch. This queue is processed in the proving period cron callback, where the sector numbers to terminate are popped from the queue and passed to `terminateSectors`. The latter call expects the terminating sectors to exist in state, and will abort if they don't.

There are a number of ways that a sector might have been removed from state before expiring:
- terminated for being faulty for too long
- terminated by explicit request of the miner
- committed capacity sector replaced by a new one (#485)

To resolve this, either 
- all paths which remove sectors from state must also remove them from the expiration queue (which requires loading the sector info to look up the expiration), or
- termination of sectors must handle a sector already being gone

The second way seems more robust. Some defensive programming is not out of place here, though callers will need to be careful not to assume that the termination implies the sectors previously existed. In the case of very large sets of long-faulty sectors, loading all the sector-infos in order to know the expiration epochs from which to deregister the sectors is exactly the kind of thing we're trying to avoid in #411.

**Comment by Stebalien** [comment]
> termination of sectors must handle a sector already being gone

We'd also need to handle sectors with changed deadlines (e.g., reused).
