### ISSUE TITLE
FaultEpochs representation is inefficient

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#519]
We're using an AMT for an array that can have at most 14 entries. Ideally, we'd use a `map[int -> bitfield]`, but we can probably just serialize to an array of index/bitfield tuples (because, IIRC, IPLD doesn't support integer keys in maps).

**Comment by anorth** [comment]
Note #357 that this representation probably has to change anyway, because the bitfields will get too large. See #411
