### ISSUE TITLE
Re-calculate sector initial pledge and defer activation until prove-commit

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#522]
#516 implements the initial pledge calculation and moves it to `SectorPreCommit`, because that is the requested pre-commit deposit amount. The initial pledge requires knowing the sector epoch, so that's changed to be the pre-commit epoch. This effectively means that the sector's power is locked in at this point too. See the discussion and resolutions with a string of 👍 in #424.

However, the winds have changed and now there are requests to return sector activation epoch to prove-commit and re-calculate the power and pledge using the later activation epoch and updated block reward estimate.

From [Slack](https://filecoinproject.slack.com/archives/C015KQQLQQ1/p1592943826132100?thread_ts=1592865896.126300&cid=C015KQQLQQ1)
>  Ideally we would like to keep InitialPledge calculation in ProveCommit and PreCommitDeposit calculation a distinct concept in PreCommit. It's so happened that PreCommitDeposit uses the same formula as InitialPledge with the current PoRep. They might be different values when a new algorithm is used.
> Another complication here is that TerminationFee is also higher (since SectorAge is longer with an earlier ActivationEpoch). The main thing here is that Activation at ProveCommit is the cleanest conceptually, the sector has now been activated and its lifetime begins.

This issue tracks a decision about and implementation of re-calculating the pledge at prove-commit time.

**Comment by nicola** [comment]
Since #516 is merged, is this now closed?

**Comment by anorth** [comment]
We might be able to compute precommit deposit separately, but with a very similar calculation. So long as we can ensure it comes out not larger than the initial pledge recalculation, which might be tricky.

**Comment by anorth** [comment]
Now that the initial pledge has changed to include a portion of money-supply lockup, in addition to pledge covering potential penalties, we definitely want to do this. It's likely that we can reduce the pre-commit deposit to be much smaller than the pledge.

Since we have to recalculate anyway, revert to considering the sector activated on prove commit, rather than precommit (the sectors ActivationEpoch).

**Comment by ZenGround0** [comment]
> For now, set IP = 20*BR(t)

@anorth do you meant Precommit deposit = 20*BR(t) ?
