### ISSUE TITLE
Deal not found by market when terminating sector in miner cron

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#529]
Reported from Lotus. Here's the execution traces of [miner](https://ipfs.io/ipfs/QmUkeq4p7TNh9A73MTXUBgMrb1S6y53smgtVHnXnBYEaRU/exec.html#bafy2bzacednhgynrysnxavsjl3speafkrjcii7dhzcwnlegr4glma2wxxzovo-bafy2bzacebehebh5suaib574cpglh42koal2rcs4ovgmpyr3mslqnb5duzvs2-bafy2bzacecahyrcyy67oces4pr4hl7zezc5qchcgvrk54xvimbn3ayegb6zmm) and [market](https://ipfs.io/ipfs/QmUkeq4p7TNh9A73MTXUBgMrb1S6y53smgtVHnXnBYEaRU/exec.html#bafy2bzacednhgynrysnxavsjl3speafkrjcii7dhzcwnlegr4glma2wxxzovo-bafy2bzacebehebh5suaib574cpglh42koal2rcs4ovgmpyr3mslqnb5duzvs2-bafy2bzacecahyrcyy67oces4pr4hl7zezc5qchcgvrk54xvimbn3ayegb6zmm-bafy2bzacebzybfajffcs3ytfvwpyajdmk46zxtmbd7ckahjisbithzjprizwy) actors.

Either the wrong deal ID was stored, or a deal was removed from the market actor before the sector ended. Maybe that latter case is expected somehow and should not cause an abort.

**Comment by aarshkshah1992** [comment]
@anorth I think I get why this is happening.

1. In `MarketActor.CronTick` we remove deals that have time out (not activated till now/ not appeared in a proven sector till now) OR deals that have expired (current epoch > deal end epoch).
2. However, the miner actors asks the Market actor to remove ALL deals belonging to an expired/faulty sector when the miner actor gets the corresponding cron callbacks.

Hence, it is possible that the market actor gets a request to delete a deal that it has already expired or timed-out and subsequently removed earlier. I think the easiest solution here is to not abort when we can't find deals.

The other option is to not delete any deal from the state unless the entire sector is terminated but that would mean keeping more state around for longer.

**Comment by anorth** [comment]
Right, sounds good. We should continue to remove deals when they are finished, and it should not be an error for the miner to request termination of those deals when the sector terminates.
