### ISSUE TITLE
Keep track of TotalDealCollateral in actors

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/specs-actors#531]
To compute TotalFILCirculatingSupply, we will also need to keep track of TotalDealCollateral in market actor (similar to TotalPledgeCollateral).

**Comment by aarshkshah1992** [comment]
@anorth 

I think we mean the funds that are locked here and not just the `ClientCollateral` + `ProviderCollateral`. 
This means that we should also add the storage fee that is locked for the Client to `TotalDealCollateral ` every time we publish a deal and subtract from `TotalDealCollateral` every time any funds are unlocked in the Market Actor(could also be when payment is made from client to provider).

Does this make sense ?

**Comment by anorth** [comment]
I think that makes sense, and for flexibility let's track all three separately:
- Total deal provider collateral
- Total deal client collateral
- Total deal payments in escrow
