### ISSUE TITLE
Increase termination fee for sector replacing a committed-capacity sector

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#532]
When a new sector replaces a committed capacity sector, its termination fee is initially very low, because the sector has not accumulated any reward. This mechanism can be abused to reduce a large termination fee for an old sector.

The new sector's termination fee should be somehow increased so that terminating it is at least as expensive as terminating the sector it replaces.

Tentative calculation:
- oldAge = age in days of the old sector (actual duration, from oldprovecommit to upgrade provecommit)
- newAge = age in days of the new sector (actual duration, from upgrade provecommit to now)
- if 6months > newAge+oldAge: computedTF(now) = oldBR * oldAge + newBR * newAge +newIP
- otherwise: computedTF(now) = oldAge * oldBR + (6months-oldAge) * newBR +newIP
- newTF=max{SP(now), computed_newTF(now)}

**Comment by davidad** [comment]
The above calculation is incorrect in case oldAge > 6mo. Here's another attempt:
* AgeAccountedFor = 0
* computedTF = newIP
* computedTF += newBR*min{newAge, 6months-AgeAccountedFor}
* AgeAccountedFor += min{newAge, 6months-AgeAccountedFor}
* computedTF += oldBR*min{oldAge, 6months-AgeAccountedFor}
* newTF=max{SP(now), computedTF}

**Comment by anorth** [comment]
Since this was written, the normal sector termination fee is not it's initial pledge, but just the 20BR block-reward-related portion of it, excluding the share-of-money-supply portion. So we should use 20BR in place of IP above

**Comment by anorth** [comment]
Also six months should be 70 days

**Comment by anorth** [comment]
@zixuanzh confirmed that we're ok to use the new 20BR, even though it might be smaller than the old 20BR, thus reducing the total penalty a little.
