### ISSUE TITLE
Sector termination mutates proving deadline mid-period

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#535]
The window post mechanism maintains a property that sector deadline/partition assignments change only at the proving period boundary. This is broken by the `TerminateSectors` method, which mutates them immediately. This will cause problems for miners by re-allocating sectors to partitions mid-deadline, but also very likely messes up some accounting that is otherwise maintained only at the PP boundary.

A quick solution to this would be to change TerminateSectors to instead request sector termination at the end of the current proving period. Pay the termination fee now, and then re-register the sector's expiry for the current proving period.

An alternative, more invasive, but probably better solution is to change termination to a two-phase thing as in #551.

FYI @Stebalien

**Comment by Stebalien** [comment]
Sounds like I'll need to tackle this before #411. The bitfield solution seems like the way to go.

**Comment by Stebalien** [comment]
(assigning this to myself for now, we can discuss this in your AM)

**Comment by Stebalien** [comment]
I assume "new" sectors would just be removed from the new sector list, instead of being marked as terminated, right?

**Comment by Stebalien** [comment]
Discussed with @anorth, it's already broken so we'll punt.

**Comment by anorth** [comment]
I've discovered another reason for two-phase termination. Sector power is calculated from lifespan, but when performing a CC upgrade we shorten the replaced sector's expiration. This would be a problem because it would change the sector's calculated power from the calculation when the sector was added.

It just so happens that we get away with it because we know the replaced sector has no deals, so its power is constant with lifetime. But that's a very fragile state.

One solution would be to store the calculated power in the sector on-chain info, but the less we store there the better.

Two-phase termination would solve the problem, because we could deduct power immediately, mark terminated, and _then_ change the expiration.

**Comment by anorth** [comment]
I have broken out discussion of two-phase termination to #551, preserving this issue just for resolving the mid-period mutation of deadlines that we currently have.

**Comment by anorth** [comment]
I think we should do the quick solution now, assuming two-phase termination isn't coming.

We have more important sector lifecycle rework than two-phase termination, and can reconsider it after making those changes.

**Comment by Stebalien** [comment]
The downside here is that we're putting more load on the cron actor. But, honestly, most terminations should be handled by the cron actor anyways (due to sector expirations).

**Comment by Stebalien** [comment]
Plan: When the miner terminates:
  * Remove sector power, pay penalty.
  * Re-schedule termination for the end of the epoch.
  * Mark the sector as faulty so we don't try to prove the sector, or try to discount the power again.

**Comment by anorth** [comment]
Moving this out of the queue in favour of #599, which should resolve it.

**Comment by Stebalien** [comment]
What if we update the expiration in the partition, but leave the expiration in the sector info alone? That would avoid messing with the sectors power.
