### ISSUE TITLE
Consider refusing to unlock funds rather than requiring top-up

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#537]
Currently, each miner actor has:

* PreCommitDeposits - funds locked for future sectors
* LockedFunds - other locked funds (pledges, vesting rewards, etc.)
* VestingFunds - a vesting schedule for unlocking locked funds.

There's also a concept of initial pledges that will be enforced in https://github.com/filecoin-project/specs-actors/pull/528. If the miner's "locked funds" falls below this minimum, the miner will need to intentionally lock funds to fix the situation. Apparently miner's should receive block rewards fast enough that this shouldn't be a problem. But it would be nice if it were impossible.

I'd like to propose simplifying this a bit:

* VestingFunds - the total amount of funds currently vesting (not the schedule).
* LockedFunds (InitialPledges, PreCommits, etc...) - funds that cannot be spent for various reasons.
  * Could be stored in separate fields.
* VestingSchedule - The schedule at which funds in VestingFunds vest.

VestingFunds and LockedFunds would act as _independent_ thresholds. When attempting to withdraw funds, the total miner's funds would never be allowed to drop below either of these thresholds. But other than that, these thresholds wouldn't interact.

This way, the miner would never need to intentionally lock up funds, only to have them vest over time again. Instead, if the miner somehow drops below the minimum locked and/or vesting threshold, they'd simply need to send money to the actor to revive it.

**Comment by Stebalien** [comment]
cc @acruikshank

**Comment by anorth** [comment]
I don't think this works, but it's difficult to describe why. Let me try to explain the requirements and current state.

The pre-commit deposits are funds that are locked up on sector pre-commit, and released on proof (or burnt if it never comes). These don't vest. This value cannot be used as security collateral for other sectors.

The other bucket of locked funds is those that are vesting. These locked funds secure (or over-secure) the sectors the state variable called LockedFunds is just the cached sum of the unvested funds here.

The code must maintain an invariant that the miner's balance is not less than the sum of precommit deposits and locked funds.

Separately, there is a requirement that the vesting funds (excl pre-commit deposits) covers the sum of the initial pledge requirements for active sectors. Funds vest (unlock) over time so this property may cease to hold.  This is not an _invariant_, but a _requirement_ for continued participation. The initial pledge posted by the miner isn't "locked" forever. There's a distinction between the funds actually locked, and the funds required to be locked to cover initial pledges for continued participation.

So to speak to some points of your proposal:
- locked funds securing the sector initial pledge must not include the precommit deposits, they must be accounted separately
- vesting funds and locked (ex-precommit) funds are the same concept, not independent
- sending money to the actor without locking it up doesn't affect any of these things

**Comment by anorth** [comment]
> the miner would never need to intentionally lock up funds

Perhaps the way we could acheive this more directly is to refuse to vest funds past the initial pledge requirement. At present, we vest them but then require the miner to re-lock if they vest too much. This does cause such funds to be released much later than if we just held up the vesting queue. @zixuanzh would something like this meet your needs?

**Comment by zixuanzh** [comment]
Yes, I think this should work too, as long as a miner's total LockedFunds >= sum of initial pledges for all active sectors. cc @davidad

**Comment by davidad** [comment]
Refusing to unlock LockedFunds if they would undercollateralize the miner seems _great_ from my perspective (though it’s not obvious to me how it would be implemented).

Note that a miner could still become undercollateralized if they get slashed while near the threshold. I think in this case we would still want to require them to put up funds.

**Comment by anorth** [comment]
Redundant if we do #757

**Comment by Stebalien** [comment]
This has been addressed by FeeDebt and #747.
