### ISSUE TITLE
Market Actor: Slashed funds are not considered in WithdrawBalance

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/specs-actors#541]
@anorth 

In `WithdrawBalance`, we have an `amountSlashedTotal` variable but we ONLY ever initialise it to 0. We are definitely doing something wrong here. 

We need to think about how to solve this. Consider this case:

1. A call to `OnMinerSectorsTerminate` for a deal  leads to the `SlashEpoch` field for that `DealState` to be set i.e. we "mark" it for being slashed during the next `CronTick`. Note that no funds have actually been slashed in this.
2. The provider calls `WithdrawBalance` before the next `CronTick`.Since the slashing in **1** has still NOT been processed, the provider could withdraw all funds and escape from the slashing.

Would it make sense to have a `ToBeSlashed`(or something) field in the Market Actor State that's updated when `OnMinerSectorsTerminate` is called. We can refer this in `WithdrawBalance` and clear it in the `CronTick` after the slashing,

I've marked this as a P1 because it sounds like one, but please remove it if you think otherwise.

**Comment by anorth** [comment]
I think this is a legacy from when deal payments were processed on-demand. They're now done every 100 epochs. I'm moderately confident we can just remove this, although some tests would help.

The funds to be slashed should be held in collateral/escrow - withdrawal should not allow getting at them. If a deal is terminated in between payment updates, the result should be that the miner can withdraw slightly less of their funds than they would be able to if they waited for the final payment (but won't get their collateral back in any case).

**Comment by aarshkshah1992** [comment]
After discussing offline with @anorth , this is not a bug as the slashed funds will be locked. Closing this in favour of #465 as we still need to write the tests to prove this.
