### ISSUE TITLE
Verified Registry needs to resolve addresses

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/specs-actors#556]
The Verified Registry currently only works if the `Address` provided in `AddVerifierParams` is always an ID-address. If a pubkey address is sent, that address won't actually be able to add verified clients, since it won't be found in `GetVerifier`, which will be called with its ID address (since `rt.Message().Caller()` always returns an ID address).

Assuming this isn't okay, we need to do similar address resolution as the multisig's `resolve()`. It'll be a little trickier in this case, since we probably want to overwrite pubkey addresses with ID addresses in `st.Verifiers` when they first become available lest we run the risk of having two different entries in the map for the same "conceptual" address.

**Comment by arajasek** [comment]
I marked this a bug, but if we're okay saying `AddVerifier` should always get ID addresses as its params, then we can just document that and close this (we shouldn't be okay with that, IMO).

**Comment by anorth** [comment]
We can enforce the verifier is an ID address, rather than just document it.

@whyrusleeping can you speak to the reasonableness of requiring the verifier account to exist in the state tree?

**Comment by whyrusleeping** [comment]
It might be more user friendly if we use the stable address instead of the ID address. that way things don't fail weirdly if the user hasnt sent funds to their account yet.

That said, i'm fine with either way here

**Comment by anorth** [comment]
If a verifier is constrained to be an account, then we can fetch its stable address from the actor and normalize to that. If it's not so constrained (e.g. can be multisig), there's no general mechanism to get the stable address of an actor.

**Comment by Schwartz10** [comment]
I think the same pattern applies to verifying clients too (not just adding verifiers) - i.e. - if you use a `t1` or `t3` address as a verified client, that address will not be able to make verified deals. Right now, you must use its ID address.

Forcing the use of an ID address for a verified client is not ideal for most users (they can't verify brand new addresses), and not ideal for most application developers either (even though v few might actually run into this exact issue).

**Comment by anorth** [comment]
See #729 for an enumeration of the resolution points.

**Comment by anorth** [comment]
Rather than handle unresolved addresses, an attractive alternative is to create the account actor for a public key with a zero-value send, thus ensuring it has an ID address (#730). When taking this issue, I think that should be the preferred approach (and we can do the same in the multisig).

**Comment by Schwartz10** [comment]
Just so I'm clear @anorth - the creation of a new account actor would happen internally inside Lotus right? I.e. - we won't actually need to send a message with 0 value over the network to create the new account actor?

**Comment by anorth** [comment]
I don't know what you mean by "inside Lotus", but I mean the multisig actor would send an internal message to create a new account actor, if necessary.

**Comment by aarshkshah1992** [comment]
@anorth Wha's blocking this ?

**Comment by aarshkshah1992** [comment]
Had a good discussion with @anorth today on solving this. One solution we discussed is mandating that all `Verifiers` and `VerifiedClients` be resolvable to ID address (we fail the corresponding calls if they are NOT resolvable).

We can then go and do _something_ like https://github.com/filecoin-project/specs-actors/issues/730 for the the `Verifiers` and `VerifiedClients` as well.
