### ISSUE TITLE
Better handle DetectFaultsThisPeriod edge case 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#593]
`detectFaultsThisPeriod` handles an edge case with the following comment 
```
// A cron event has not yet processed the previous proving period and established the next one.
// This is possible in the first non-empty epoch of a proving period if there was an empty tipset on the
// last epoch of the previous period.
// The period must be reset before processing missing-post faults.
```
it then aborts with `exitcode.ErrIllegalState`.  Two potential issues with this:

1.  The exitcode is inaccurate to my understanding of what `ErrIllegalState` means.  This state is legal and possible, it's just not possible to `processMissingPoStFaults` given the state.
2. It may be desirable for the message (submitPoSt, declareFault, declareRecovery) to proceed with other tasks even if it can't process missing post faults from previous deadlines.  AFAIK missing PoSt processing is convenient to add to these miner actor invocations but is separate from the main point of submitting a proof or declaring a fulat or recovery.

**Comment by anorth** [comment]
For (1), see #597
