### ISSUE TITLE
Cover each exported actor method with at least one test

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#596]
As a basic minimum milestone to reach for testing, we should exercise each exported actor method at least once. 

Of course, many methods need much more testing in order to know they're robust, but a basic happy path still ensures that the code is executable.

- [x] system.Constructor
- [x] reward.ThisEpochReward
- [x] miner.ChangeWorkerAddress
- [x] miner.ChangePeerID
- [x] miner.ChangeMultiaddrs
- [x] miner.CheckSectorProven
- [ ] miner.CompactPartitions
- [x] miner.CompactSectorNumbers

**Comment by anorth** [comment]
Some of these are covered by #479

**Comment by aarshkshah1992** [comment]
@anorth Picking up `miner.ChangeWorkerAddress`.
