### ISSUE TITLE
Market withdraw allows anyone to trigger withdrawals

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#602]
From bug report on slack

>As far as I can tell, market_actor.WithdrawBalance makes no requirements on Caller's identity when withdrawing from a non-miner actor.
Assuming Caller and params.ProviderOrClientAddress are both account actors, this function: https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_actor.go#L79
returns the resolved params.ProviderOrClientAddress, and just checks that Caller is a "signable" type address. I'm pretty sure this means any account/multisig actor can withdraw unlocked, escrowed balance from any non-miner actor. (edited) 

Investigate this and if the above is true come up with a fix

**Comment by wadeAlexC** [comment]
Looking again, I still don't think this is correct, but I don't think this is a doomsday scenario.

`escrowAddress` defines the recipient of the withdrawn funds as the passed-in param address. So I think anyone can trigger a withdrawal, but they don't get to take the funds.

**Comment by ZenGround0** [comment]
It definitely feels off that we check identity permissions when addr belongs to a miner actor but not when it is a signable addr.  Miner actor withdraws and adds can only be issued by worker/owner but signable addrs can be issued by any signable addr.

The asymmetry suggests we are being inconsistent and should think through the right way to do this and do it in both places.  From recent discussions about applying principle of least privilege I'm guessing we would prefer to tighten up signable addr conditions (normalized caller must be recipient) rather than loosen miner restricitions.

@anorth is there anything that goes wrong if we restrict the caller to be the recipient?

**Comment by whyrusleeping** [comment]
Yeah, we should check that the caller is the recipient if the caller is not a miner.

**Comment by anorth** [comment]
This may have been intended as general flexibility for users, e.g. being able to withdraw to a cold wallet, multisig etc. But arbitrary triggering of withdrawals of other accounts is probably going to cause problems, so +1 let's restrict it.
