### ISSUE TITLE
Market WithdrawBalance never slashes

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#603]
There is either dead logic or a feature we have forgotten to keep track of in market actor `WithdrawBalance`.  Before making the withdraw update to the balance table we initialize a variable `amountSlashedTotal` to 0.  We then do no assignments to this variable during the state transaction making the update.  After the update we burn slashed funds if `amountSlashedTotal` is greater than 0 which is never hit.  

Either we should remove the calculations for the dead logic or we should track and do the work introducing slashing to market balance withdraw.

**Comment by aarshkshah1992** [comment]
@ZenGround0 I'd discussed this with @anorth . 

1. The funds to slash are locked and the user can't withdraw such that the user's balance goes below the collateral/funds to be slashed. 
2. We slash funds in `OnCronTick`

Basically, this is dead code and we can remove it. I'll create a PR.

**Comment by aarshkshah1992** [comment]
This is done.
