### ISSUE TITLE
Strict parameter validation

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#604]
In all methods that take _slices_ of things, we should be validating that all elements in the slice are unique. Even better, we should consider validating that they're unique and sorted.

Usually duplicate elements will just end up costing the caller more, but there could be some cases where batching causes us to actually process the duplicate element multiple times, penalizing or rewarding the caller multiple times.

A simple solution here would be to have all method parameters implement a `Validate` method that must be called before passing the parameters to the actor itself.

**Comment by Stebalien** [comment]
Examples:

* We don't validate that the partitions passed in SubmitWindowedPost are unique.
* We don't validate that the number of proofs in SubmitWindowedPost before passing them to the runtime.
* We don't validate that deal IDs are unique in PreCommitSector?

**Comment by anorth** [comment]
Related to #416 , perhaps do them together.

**Comment by Stebalien** [comment]
It would be really nice to be able to do this via codegen:

1. Codegen a `Validate` method that validates all fields.
2. Allow for tags like `validate:"ordered,nonempty"` for slices, etc.

**Comment by Stebalien** [comment]
I've done a first pass, but one thing I know I've missed is non-nil validation. Especially for bitfields.

Options:

* Check everywhere. I'd consider this a non-option.
* Make bitfields nil-safe for reading. That's better than nothing, but still sketchy.
* Bitfields by value? There's no reason we _can't_ do this.
* Validate non-nil in cbor-gen. We can explicitly tag fields that _can_ be nil. This will require a signoff from @whyrusleeping. We could easily extend this to additional validation (max, etc.) but I'm not sure if this is the right place...

**Comment by anorth** [comment]
> Bitfields by value

The bitfield class doesn't play nice with use as a value. We used to do that, and changed everything a while back. I would love to have an implementation that does, though.

**Comment by Stebalien** [comment]
What was the problem? It looks like it should work.

**Comment by anorth** [comment]
I haven't gone in depth (@whyrusleeping made the change), but from a quick glance the set/unset map overlays will shallow-copy, so mutating a copy of a bitfield will then cause an unexpected mutation in the original.

**Comment by Stebalien** [comment]
> I haven't gone in depth (@whyrusleeping made the change), but from a quick glance the set/unset map overlays will shallow-copy, so mutating a copy of a bitfield will then cause an unexpected mutation in the original.

Eh, that's no different from copying a `map` or our `adt.Array` structure. I'll bug @whyrusleeping for context.

**Comment by Stebalien** [comment]
Another solution is to just make bitfields immutable and use the batch union/subtract operations to set/unset bits.

**Comment by Stebalien** [comment]
> We don't validate that deal IDs are unique in PreCommitSector?

Try this one weird trick to _100x_ your verified deal allowance!

**Comment by Stebalien** [comment]
Closing in favor of #979.
