### ISSUE TITLE
Market: ComputeDataCommitment should use ReadOnly, rather than Transaction

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#607]
https://github.com/filecoin-project/specs-actors/blob/015cbe775889749b12ae404a0bce86ff5246b588/actors/builtin/market/market_actor.go#L400-L409

No state changes happen in this block. This should be changed to use `ReadOnly`.

**Comment by aarshkshah1992** [comment]
@anorth Request for labels.

@wadeAlexC Thank you so much for all this.
