### ISSUE TITLE
Market: ComputeDataCommitment loads identical AMT for each passed-in DealID

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#608]
https://github.com/filecoin-project/specs-actors/blob/015cbe775889749b12ae404a0bce86ff5246b588/actors/builtin/market/market_actor.go#L401-L407

`st.mustGetDeal` loads `st.Proposals` while looping over `params.DealIDs`, which is inefficient.

Instead, use a method that accepts a deal proposal array as a parameter and only loads the AMT once.

**Comment by aarshkshah1992** [comment]
@anorth Please give the labels when you can.

**Comment by anorth** [comment]
This could be an instance of the general problem/opportunity in #278, but it probably behooves us to resolve this one directly as part of discovering better patterns.
