### ISSUE TITLE
Market: CronTick loads identical AMT for each processed deal

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#609]
https://github.com/filecoin-project/specs-actors/blob/015cbe775889749b12ae404a0bce86ff5246b588/actors/builtin/market/market_actor.go#L532

`mustGetDeal` loads `st.Proposals`, and is performed in a loop. If possible, this should only be done once. Related issue: #608

**Comment by aarshkshah1992** [comment]
@anorth Please give the labels when you can.
