### ISSUE TITLE
PaymentChannel: Vouchers can be replayed across channels

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#612]
`UpdateChannelState` allows either party of a PaymentChannel to submit a voucher signed by their counterparty in order to redeem channel funds. 

Signed vouchers do not include any unique information to link the voucher to a specific channel between the two parties, meaning that a voucher signed by either of a channel's parties may be submitted to any channel that party is a member of.

In order to ensure signed vouchers only apply to a single channel, the address of the PaymentChannel actor should be included in the signed payload. When validating a submitted signature, `UpdateChannelState` should check that this address matches `Message().Receiver()`.

**Comment by aarshkshah1992** [comment]
@anorth Request for labels.
