### ISSUE TITLE
Market: How can a timed-out deal occur in a cron tick

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/specs-actors#614]
We mark a deal as timeout in the `CronTick` call if the `SectorStartEpoch` of the Deal State is undefined. Take a look here:

https://github.com/filecoin-project/specs-actors/blob/a0ab84303c0ec6694001929e5442f1d7b9c2491e/actors/builtin/market/market_actor.go#L541.

However, this looks _like_ dead code. We create a state for the deal and ALSO set the `SectorStartEpoch` to the current epoch in `ActivateDeals` here:

https://github.com/filecoin-project/specs-actors/blob/a0ab84303c0ec6694001929e5442f1d7b9c2491e/actors/builtin/market/market_actor.go#L374

Note that we never mutate the `SectorStartEpoch` to set it to undefined post this. 

We also abort in `CronTick` if we are unable to find a state for the deal. This means that if a state exists, the `SectorStartEpoch` has to be defined. So, what's the point of this code ?

**Comment by aarshkshah1992** [comment]
@anorth @whyrusleeping Please can you comment ?

**Comment by aarshkshah1992** [comment]
We need to write tests for this scenario if it turns out that it's a valid scenario.

**Comment by whyrusleeping** [comment]
@aarshkshah1992 I think youre right in that this is dead code, we used to depend on states.Get returning an object with all fields set to 'undefined' if the object wasnt found. Now that its changed to return an explicit 'found' bool, i don't think we will ever hit this...

**Comment by aarshkshah1992** [comment]
Need to discuss how to handle timed out deals now and write tests accordingly.

**Comment by aarshkshah1992** [comment]
@anorth This is now a bug and so am changing the labels.

**Comment by aarshkshah1992** [comment]
@whyrusleeping After thinking through this, turns out our deal timeout logic is wrong as well in order to this being dead code. A deal is timed-out if on a cron tick for it, there is no activation state for it. Have fixed this in the PR.
