### ISSUE TITLE
Handle miners going bankrupt from fees

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#627]
The initial pledge locked by a miner doesn't necessarily cover the maximum fee for terminating all their sectors. Also it's possible for locked funds to decrease below the initial pledge requirement (though we could change that). We need to handle bankruptcy. In general the approach will be to claim all locked funds and de-register the miner permanently.

cc @zixuanzh do you have any detail to add?

**Comment by Stebalien** [comment]
Unfortunately, we _currently_ just pay whatever fines we can and ignore the rest:

https://github.com/filecoin-project/specs-actors/blob/e5b62bf0f506ec6ea3899fa94dcd4dd701ad51e5/actors/builtin/miner/miner_actor.go#L2147-L2173

**Comment by anorth** [comment]
Replaced by #888
