### ISSUE TITLE
Change paych actors lane state tracking to use an AMT

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs-actors#628]
this is currently an array, which isnt great. It should be either a HAMT or an AMT (likely AMT makes the most sense here, but a HAMT wouldnt be bad either).

**Comment by aarshkshah1992** [comment]
Note: As and when we introduce a H/AMT, please use the new pattern for state mutations introduced here to avoid duplicated H/AMT reads:

https://github.com/filecoin-project/specs-actors/pull/665.

**Comment by anorth** [comment]
Closed by #959
