### ISSUE TITLE
Should `validateDealCanActivate()` be allowed after `StartEpoch`?

### ISSUE THREAD

**Issue by kirk-baird** [filecoin-project/specs-actors#629]
# What is the issue

I'm just looking for clarification between the specifications and the code about whether progressing a deal from `Published` to `Active` may occur after `StartEpoch`.

The [specifications](https://filecoin-project.github.io/specs/#systems__filecoin_markets__storage_market__storage_deal__storage_deal_states) fort `Published -> Active` says `StartEpoch` may have passed before becoming active. i.e. `StartEpoch <= CurrEpoch` (and as I understand also allows `StartEpoch > CurrEpoch`)

The code requires `StartEpoch >= CurrEpoch` [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_actor.go#L716).

**Comment by anorth** [comment]
The spec doesn't sound right to me. @hannahhoward ?
