### ISSUE TITLE
PaymentChannel: Reject equal-nonce voucher submissions

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#660]
`UpdateChannelState` currently allows a voucher with equivalent nonce to the last-seen nonce to be submitted and processed:

https://github.com/filecoin-project/specs-actors/blob/1b19d168503d7401e10c94632a3e1dbdede5d692/actors/builtin/paych/paych_actor.go#L205-L207

While this may not result in a loss of funds, this replayability complicates the possible operations of `UpdateChannelState` significantly.

**Comment by aarshkshah1992** [comment]
@anorth Should I be removing my assignment from this ?
