### ISSUE TITLE
Accurate Reward after Null Rounds

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#670]
From discussion on #317 here is a description of our current reward tracking in the presence of null rounds

> Because cron runs at the end of epochs, in a sequence of epochs 1000, 1001(null), 1002, at the end of 1000 the reward for 1001 is calculated. It is never used and not recalculated at the end of 1001, and so the reward for 1001 is paid in epoch 1002 (and then the reward for 1003 is calculated).

This isn't too bad and will be solved immediately if we get null round cron ticks

If we don't get null round cron ticks we could compute reward for post null tipsets exactly accurately by lazily updating KPIs in a way that updates calculations through null rounds.  This approach relies on the fact that power never changes during null epochs (at least as long as we still don't have null epoch cron ticks).  

Closed spike PR #669 has the first ~40% of work, and tracks that this relies on #495 to get an accurate power accounting number no matter which messages are processed before the first block reward / current reward query.

**Comment by anorth** [comment]
As of https://github.com/filecoin-project/lotus/pull/2617, cron is executed for empty tipsets, so this problem has disappeared.
