### ISSUE TITLE
Implement compaction of partitions, removing terminated sectors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#673]
This is a follow-up to the partition-wise miner state refactor (#648), which leaves a stub implementation for compaction of partitions.

**Comment by Stebalien** [comment]
Plan:

1. Remove partitions to compact from the deadline's partition array.
2. _Move_ any remaining partitions down (i.e., when compacting N partitions, partition N -> 0, N+1 -> 1, etc.).
3. Re-add sectors from compacted partitions.

**Comment by Stebalien** [comment]
Actually, we can reduce memory usage by constructing new partitions as we go, keeping a rolling "remainder". This really depends on how much we care about having runs of sequential sectors.

**Comment by Stebalien** [comment]
This has been implemented, Follow up in #756.
