### ISSUE TITLE
Pay part of early-termination fee on termination, defer the rest for async processing

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#674]
The fee calculation for early terminations depends on information stored in `SectorOnChainInfo`, so for terminations that result from a long fault, we can't calculate the fee (because we don't load all those infos in cron). The fee is instead calculated and paid as the early termination queue is processed (either manually or in small-batch cron).

However, we know the fee is at least equal to the undeclared fault penalty, so we could charge that amount immediately, and defer the rest. This would require recording the amount paid, since the calculation changes with time.

**Comment by Stebalien** [comment]
I think we'd need to record this per-sector (no bitfields).

**Comment by anorth** [comment]
Manual termination now does this when it processes the expiration queue synchronously.

**Comment by Stebalien** [comment]
Well, sort of. We don't guarantee that the queue will all be processed immediately.
