### ISSUE TITLE
Miner termination from consensus fault has scale limitation

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#675]
`ReportConsensusFault` attempts to terminate all deals for the miner's sectors. This is a potentially unbounded computation and could fail in multiple ways, preventing the fault report.
- An arbitrary number of deals are packed into a single message to the market actor, which will hit the serialization limit
- An arbitrary amount of sector state is loaded, which could hit the (block?) gas limit

We need to spread this termination out over time.

One way might be to defer the sector termination to be processed over time like the new per-partition early termination queues. This would require not deleting the actor from state until that's complete. The "network" would pay the gas cost.

Another way might be to have `ReportConsensusFault` do partial work and "succeed" even if the miner is not gone yet. It wouldn't pay the reward yet, but remember who called it first successfully, and require them to call it again until all the sectors are terminated, before paying out the reward. This makes the reporter pay the gas cost.

**Comment by Stebalien** [comment]
>  It wouldn't pay the reward yet, but remember who called it first successfully, and require them to call it again until all the sectors are terminated, before paying out the reward. This makes the reporter pay the gas cost.

I like this idea, but I worry about what would happen if the miner _doesn't_ do that. We could also let anybody that cares do it (e.g., clients) but then the reporter is incentivized to wait to get _others_ to act on their behalf.

**Comment by anorth** [comment]
A nice idea from @nicola: in all cases where we want to terminate a miner, we can:
- remove all power
- set a flag indicating the miner is terminated, which prevents sector commitment and Window PoSt
- wait 14 proving periods for all the sectors to terminate naturally

After sufficient delay, the miner will have no power, no sectors etc, just a deadline cron doing nothing. At this point we're in the same AWOL situation (#277) as could be reached by a miner letting their sectors expire without faulting.

We might relax consensus fault penalties even further, but could do this now. So long as power is removed immediately, sector termination is not urgent.

**Comment by anorth** [comment]
We will probably change to not terminate a miner for consensus fault. When that's confirmed, I'll close this issue and replace with another one specifying the penalties.

**Comment by anorth** [comment]
Replaced by #933 and #934 🎉
