### ISSUE TITLE
Increase cbor-gen max bytearray length to support maximum partition sectors bitfield

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#676]
With current parameters, a partition may have up to 2350 sectors. This issue tracks changing the maximum in the cbor-gen project so that we can store a full partition of maximally-spaced, maximum-magnitude sector numbers safely.

**Comment by Stebalien** [comment]
Looking at the code

**Comment by Stebalien** [comment]
As of https://github.com/filecoin-project/go-bitfield/pull/41, we now use cbor-gen's byte array limit (2MiB). But this is too much (it can force us to allocate 128MiB of memory to expand the runs). That's obviously not OK.

We need at least 20KiB to encode a partition's sectors. Let's bump to 32 to be safe. 32KiB can encode at most 256Ki runs = 4MiB of memory expanded. We can reduce this to 2MiB with https://github.com/filecoin-project/go-bitfield/issues/24 if necessary.

New PR: https://github.com/filecoin-project/go-bitfield/pull/42
