### ISSUE TITLE
VerifReg actor: Write tests

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/specs-actors#682]
This actor has absolutely no tests.

@anorth.

@acruikshank Would you be interested in picking this up since you are working on tests currently ?
Let me know if you are busy and I can pick this up next week.

**Comment by mrsmkl** [comment]
@josepablofm78 has written unit tests for this actor, they are in this branch, should open a PR soon https://github.com/keyko-io/specs-actors/tree/feat/add_test_verifiedRegistryActor

**Comment by aarshkshah1992** [comment]
@josepablofm78 This is cool. When do you plan to open a PR ?

**Comment by josepablofm78** [comment]
hey @aarshkshah1992 sorry it took me so long to answer you. 

We are working in the verified client functionality, and we are planning to PR our work in lotus and spec actors, including this unit tests,  during this week, if it's ok with Juan. I'll let you know.
