### ISSUE TITLE
Latest CryptoEcon InitialPledge 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#688]
Latest initial pledge calculation has changed to include an additionalIP term 
```
let lock_target = percent_lock_target * fil_circulating_supply
let storage_to_cover = max(network_qa_power, target_power)
let pledge_share = sector_qap / storage_to_cover
let additional_ip = lock_target * pledge_share
```

`IP = 20BR + additional_ip`

Additionally BR 
1. should add new sector qa power in denominator along with network qa power
2. should use consistent network qa power for entire tipset (#495)

**Comment by ZenGround0** [comment]
Condition 1 on BR appears to violate the linearity (BR(p1) + BR(p2) = BR(p1 + p2)) that we rely on for computing fault fees for groups of sectors.  I need help resolving which constraint should go @zixuanzh @anorth.

**Comment by anorth** [comment]
I think we determined that we could implement a different BR calculation for this pledge calculation, but that we shouldn't burn time with it right now given likely changes to using a moving average or similar.
