### ISSUE TITLE
StoragePower: OnConsensusFault incorrectly zeroes out miner power

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#692]
`st.AddToClaim` parameter order is flipped: https://github.com/filecoin-project/specs-actors/blob/13c932208e8c2eeedee3c5491fbdc28c04fb973b/actors/builtin/power/power_actor.go#L251

This method either always fails, or may leave a Miner with a non-zeroed-out Claim.

**Comment by ZenGround0** [comment]
Woops, thanks for catching!
