### ISSUE TITLE
MultiSig | what happens when threshold is reduced below the number of approvers an existing transaction already has

### ISSUE THREAD

**Issue by frrist** [filecoin-project/specs-actors#71]

**Comment by anorth** [comment]
@whyrusleeping thoughts?

I don't think executing all the transactions that now meet the threshold is likely a good outcome (we'd need all their exit codes in the receipt value, for one thing). But some other way to bump a now-released transaction. Maybe letting an already-approving signer approve again?

**Comment by whyrusleeping** [comment]
How about adding a check to 'Approve' that runs before anything else, that checks if the given transaction is above the threshold already, and just executes it then

**Comment by anorth** [comment]
That sounds good to me.
