### ISSUE TITLE
Limit the size of miner metadata

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#712]
Currently, miners can encode an arbitrary amount of data in their multiaddr and peer ID fields. Unfortunately, we don't have any concept of "rent" for on-chain space, so it would be nice to limit the size of these fields.

On the other hand, the miner _does_ pay for state access and there are likely other ways to store arbitrary amounts of data. It may not be worth limiting this.

**Comment by ZenGround0** [comment]
@Stebalien now that `checkPeerInfo` rejects peer peer ID and multiaddr writes that exceed limits I think we can close this.
