### ISSUE TITLE
Verifreg.UseBytes: newVcCap is permanently lost if it's smaller than MinVerifiedDealSize

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#727]
From the code: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L165-L172

The comment implies that this should somehow be restored via `RestoreBytes`, but I don't think that happens. Rather than deleting the verified client, consider keeping them active so that `newVcCap` is still usable if `RestoreBytes` is called.

**Comment by aarshkshah1992** [comment]
@whyrusleeping @anorth I agree with @wadeAlexC here.

Do you guys have any objections before I make this change ?

**Comment by whyrusleeping** [comment]
This was an explicit design choice. We are prioritizing easy cleanup of the structures involved.

> The comment implies that this should somehow be restored via RestoreBytes, but I don't think that happens.

It does, see the `RestoreBytes` method, its called by the storage market actor near the end of its cron tick if a verified deal does not get activated in time.

**Comment by wadeAlexC** [comment]
To be clear, I'm referring to the edge case where `newVcCap < MinVerifiedDealSize` - in this case, the entry is deleted, and `newVcCap` is permanently lost - it won't be recovered in `RestoreBytes`. 

I can understand why it would be a design decision to just drop this remainder, though.

**Comment by aarshkshah1992** [comment]
@whyrusleeping Question is, do we want to drop the remainder or keep the verified client around in case it's balance is replenished later via `RestoreBytes` ?

**Comment by whyrusleeping** [comment]
Yeah, dropping the remainder is fine. Its an edge case thats probably not worth handling. Getting more verified datacap (especially at those low of sizes) should be relatively easy if you need it.
