### ISSUE TITLE
Verifreg.UseBytes: Consider never deleting a VerifiedClient entry

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#728]
As I understand, VerifiedClients should only ever be given one allowance, and this should never change. From code comments:

https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L116-L119

However, deleted VerifiedClients can be re-added by a Verifier via `AddVerifiedClient`.

Additionally, `RestoreBytes` has the authority to create VerifiedClients:

https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L192

In the event of a significant issue with StorageMarket code, this authority may provide an attacker with an additional vector into the Verifreg system.

#### Recommendation

Don't delete VerifiedClient entries.

(Related to #727)

**Comment by whyrusleeping** [comment]
Theres no requirement that we never delete entries. We just don't allow you to add more allowance to an existing actor just to simplify the system. Using up your whole allowance and getting a new one is fine.

**Comment by wadeAlexC** [comment]
Sounds good! I still think the edge case in `RestoreBytes` is a good reason to not delete entries.

Either way, the code comments should be clarified!

**Comment by aarshkshah1992** [comment]
@wadeAlexC Closing this via a documentation change in https://github.com/filecoin-project/specs-actors/pull/758.
