### ISSUE TITLE
Verifreg: All methods should resolve addresses to ID-addresses before interacting with state

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#729]
List of relevant locations:

* `Constructor` - `rootKey`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L42

* `AddVerifier` - `params.Address`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L52

* `DeleteVerified` - `verifierAddr`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L68

* `AddVerifiedClient` - `params.Address`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L89

* `UseBytes` - `params.Address`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L144

* `RestoreBytes` - `params.Address`: https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L193

**Comment by anorth** [comment]
Duplicate of #556
