### ISSUE TITLE
Multisig, verifreg, paych actors create accounts that don't already exist

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#730]
From discussion here #325:

> I don't think we can resolve to pubkey/stable addresses because there is no mapping from ID->stable address for actors. The reverse exists in the init actor, and account actors have a workaround of storing their pubkey in state, but other actors don't.

If it's not too much work, I propose that the Multisig actor creates an account in state if it doesn't already exist. The goal of this change is to make it easier to reason about the properties of the Multisig by enforcing that all addresses may be referenced by an ID address.

Edit: To be more clear, the proposed solution is that the Multisig (and verified registry, and payment channel) only store ID addresses in state. At construction (or relevant methods where addresses are accepted from outside), if provided with an address that does not resolve to an ID address, the actor should make a 0-value Send to the address, triggering its creation in state. Then resolve the address to an ID address again, which we can expect to succeed.

**Comment by anorth** [comment]
This is a great solution, for both multisig and verified registry actor. I expect it to simplify the code, and certainly the tests.

**Comment by anorth** [comment]
And the payment channel actor too!

**Comment by aarshkshah1992** [comment]
The PRs for MultiSig, Verifreg and Payment Channel actors have been merged,
