### ISSUE TITLE
PayCh.Collect: Clarify whether Collect implies the channel should be terminated

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#733]
Currently, `Collect` sets `st.ToSend` to 0, implying that the PaymentChannel may continue to be used. Further submission of higher-nonce vouchers via `UpdateChannelState` will continue to increment `st.ToSend` with the same behavior as before.

However, after calling `Collect`, `Settle` no longer functions properly due to `st.SettlingAt` being nonzero. Further updates to `UpdateChannelState` will allow either party to instantly `Collect` `st.ToSend`.

#### Recommendation

Clarify semantics of `Collect`: 

* If, after `Collect`, a channel should still be usable, set `st.SettlingAt` to zero.
* If `Collect` terminates the channel, consider nullifying state in some other way - like deleting the actor.

**Comment by anorth** [comment]
Collect should probably terminate the channel. Delete the actor to remove from state tree.

(Somethign fancier would be nice, but out of scope)
