### ISSUE TITLE
Exponential smoothing for parameters

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#737]
Implement a general alpha beta filtering method.  Use it to get smooth estimates for 1. TotalQAPower 2. ThisEpochReward

**Comment by davidad** [comment]
Pseudocode for filtering method & the use of estimates for extrapolations is available in [this doc](https://docs.google.com/document/d/19RRp75CCJc_qxpuPHGZCzuOx6iirHRPRRlkecCOTbjM/)
