### ISSUE TITLE
FF and SP dependent on proof type

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#743]
From the Parameter Audit:

> **Possible Change:** The fees of `FF` and `SP` are dependent on the soundness of the PoSt proof that we are using. This means that a future improvement for a PoSt for SDR (or a new PoSt for a new proof like NSE) could lead to a different soundness, which implicitly will lead to a different FF and SP.
> 
> Status quo and no change:
> We could have an overly punitive FF and SP and set the highest FF and SP as system wide parameters, however future optimization/proof changes could really minimize FF and SP.
> 
> Possible change:
> The proposal here is to make FF and SP proof dependent - for example with NSE, SP could be drastically reduced (and made as close to FF) and also FF could be reduced.

From @anorth

> This is a significant change and would need careful thought, especially with regard to potential changed proof algorithms. We probably don't have time for it.

---

Since we have one proof today (SDR) - and we could even in an NSE proof upgrade re-use the same FF and SP (they will be overly punitive), I believe this is something that could be done later.

Leaving this issue here to track future effort.

**Comment by anorth** [comment]
Right, we can do this later when introducing a new proof type, with full backwards compatibility.

**Comment by ZenGround0** [comment]
New parameters for FF and SP should be revisited in future FIPs that propose new proof types.  We won't refactor these parameters to depend on proof type until different proof types correspond to different values.  We can either reopen this when such a FIP arrives, or likely track this work in a new issue.
