### ISSUE TITLE
Change epoch duration to 30s, confirm that cryptoecon params align

### ISSUE THREAD

**Issue by davidad** [filecoin-project/specs-actors#748]
If we are planning to switch from 25s back to 30s for block time, some cryptoecon constants may need to be recomputed by manual intervention (if their dependence on block time isn't captured in code). These include:
* the `lambda` parameter in the minting function that computes perEpochReward
* a similar decay parameter in the baselinePower function

There may be a couple others that I'm not thinking of at the moment.

**Comment by anorth** [comment]
@davidad @zixuanzh could you calculate those numbers for us so we have them ready for the change?

FYI @whyrusleeping us changing the actors is dependent on these calculations being ready first.

cc @ZenGround0

**Comment by zixuanzh** [comment]
@ZenGround0 

We will use [37371474310496084838972020690291](https://www.wolframalpha.com/input/?i=Round%5B2%5E128*Log%5B2%5D%2F%286+tropical+years+%2F+30+seconds%29%5D) for https://github.com/filecoin-project/specs-actors/blob/927d2adfe03fc01d18898e5d70cd5dd573ca58bb/actors/builtin/reward/reward_logic.go#L44

and [37371476362655231235035415387185](https://www.wolframalpha.com/input/?i=Round%5B2%5E128*%28e%5E%28Log%5B2%5D%2F%286+tropical+years+%2F+30+seconds%29%29-1%29%5D) for https://github.com/filecoin-project/specs-actors/blob/927d2adfe03fc01d18898e5d70cd5dd573ca58bb/actors/builtin/reward/reward_logic.go#L46

**Comment by ZenGround0** [comment]
Thanks, I will recompute new baseline power function exponent with 30s blocktime and land directly in #704

**Comment by anorth** [comment]
When changing epoch duration, also change epochsPerYear := 1_262_277 in abi/sector.go.

**Comment by ZenGround0** [comment]
Note: #704 didn't recompute baseline exponent so that is still todo as part of this issue
