### ISSUE TITLE
Miner: Duplicate invocations of notifyPledgeChanged in processEarlyTerminations

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#752]
`processEarlyTerminations` has two calls to `notifyPledgeChanged`, back-to-back:

https://github.com/filecoin-project/specs-actors/blob/84de6c6a21972a2b03b2c6c0a80cfec0d83ed11c/actors/builtin/miner/miner_actor.go#L1598-L1602

**Comment by anorth** [comment]
Right, the `burnFundsAndNotifyPledgeChange` helper should not be used, in favour of aggregating the burn and pledge changes separately.

**Comment by anorth** [comment]
Fixed by #808
