### ISSUE TITLE
Market.PublishStorageDeals: Validate each deal's PieceSize

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#755]
Whether deals are valid or not is primarily decided in `validateDeal`: 

https://github.com/filecoin-project/specs-actors/blob/84de6c6a21972a2b03b2c6c0a80cfec0d83ed11c/actors/builtin/market/market_actor.go#L647

However, the method appears to be missing a validation check for `proposal.PieceSize`, as currently, 0-length pieces seem to be accepted. I suggest using the `Validate` method in `/abi/piece.go`, or something similar:

https://github.com/filecoin-project/specs-actors/blob/84de6c6a21972a2b03b2c6c0a80cfec0d83ed11c/actors/abi/piece.go#L35-L45

**Comment by aarshkshah1992** [comment]
@anorth Please can you put labels/priority on this one ?
