### ISSUE TITLE
Market.CronTick: Remove RequireSuccess for interaction with VerifiedRegistry and BurntFundsActor

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#767]
The CronTick finishes by invoking the Verifreg in a loop, as well as sending burnt funds to the BurntFundsActor:

https://github.com/filecoin-project/specs-actors/blob/25409283f9bf5d6d80b80797e7a6f8415d05d00d/actors/builtin/market/market_actor.go#L567-L584

Given that this is the Market's cron tick method, these calls should not use `RequireSuccess`.

**Comment by anorth** [comment]
If sending to burnt funds fails then we're in deep doodoo. But agree we should probably let the verified registry call fail, and log it.
