### ISSUE TITLE
Market: fix use of unresolved Proposal client address when checking verified deals

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#768]
The market actor resolves a deal's provider and client address when the deal is published, and stores the resolved addresses in state so that they are thenceforth always ID addresses. The implementation of the verified registry actor and its interactions violated this invariant by calling to `UseBytes` before resolving the client address.

The simplest way to resolve this would be to move the calls to UseBytes below the state transaction (which will be rolled back anyway if UseBytes aborts).

FYI @wadealexc

**Comment by wadeAlexC** [comment]
Shoot, I totally missed that. Nice catch!
