### ISSUE TITLE
CryptoEcon Param audit

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#793]
As part of the audit #695, we have already reviewed the high level correct usage of these constants.
However, we could not verify the correctness of the following values. Ping @zixuanzh, @davidad.

- ProvCollateralPercentSupplyNum
  - [ ] Check value (seems too high)
  - [ ] Correct usage (seems that it is proportional to QA power, but it should not be)
- MaxSectorExpirationExtension
  - [ ] Check value (clarification requested)
  - [x] [ValidateExpiration](https://github.com/filecoin-project/specs-actors/blob/60a2ae96d2e656e2c4536a8f1ee905834e758912/actors/builtin/miner/miner_actor.go#L1802-L1815)
- consensusFaultReporterInitialShare
  - [ ] Checked value
  - [x] Correct usage in RewardForConsensusSlashReport
- consensusFaultReporterShareGrowthRate
  - [ ] Checked value
  - [x] Correct usage in RewardForConsensusSlashReport
- PledgeVestingSpec
  - [ ] Checked value 
  - [x] [AddLockedFunds](https://github.com/filecoin-project/specs-actors/blob/dc42e57ca985d27a4a5f1cc357f642551ea2668f/actors/builtin/miner/miner_state.go#L892-L940)
- RewardVestingSpec
  - [ ] Checked value
  - [x] [AddLockedFunds](https://github.com/filecoin-project/specs-actors/blob/dc42e57ca985d27a4a5f1cc357f642551ea2668f/actors/builtin/miner/miner_state.go#L892-L940)
- LockTargetFactorNum
  - [ ] Checked value
  - [x] Usage

**Comment by anorth** [comment]
@nicola what's the state of this issue? Are you still working on it? Will it be closed by #695?

**Comment by nicola** [comment]
No, I am expecting @zixuanzh to provide final params that I will then audit with the rest of the team next week.

**Comment by anorth** [comment]
I'm closing this issue. New changes to parameters will require new issues.
