### ISSUE TITLE
Miner: Sector activation at ProveCommit may allow proving expired/expiring sectors, leading to panic during cron tick

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#795]
#787 re-calculates the sector initial pledge, and moves sector activation to the epoch in which a successful ProveCommit is made.

This change may allow `precommit.Info.Expiration - rt.CurrEpoch()` to have a negative result: https://github.com/filecoin-project/specs-actors/blob/0dcd04ea4dca004872a4984d40179a67765f2544/actors/builtin/miner/miner_actor.go#L700-L701

This was not possible before, as duration was calculated in `PreCommitSector`, where a bounds check implies that a sector's activation epoch cannot come before its expiration: https://github.com/filecoin-project/specs-actors/blob/0dcd04ea4dca004872a4984d40179a67765f2544/actors/builtin/miner/miner_actor.go#L447-L449

#### Recommendation

Because `ConfirmSectorProofsValid` needs to consider null rounds, I think the best way to handle this would be to simply add a check here: https://github.com/filecoin-project/specs-actors/blob/0dcd04ea4dca004872a4984d40179a67765f2544/actors/builtin/miner/miner_actor.go#L701

If the result is zero, or negative, this function should probably `Abortf`

**Comment by wadeAlexC** [comment]
In particular, I think a duration of zero will cause a panic during the cron tick due to division by zero here:

https://github.com/filecoin-project/specs-actors/blob/0dcd04ea4dca004872a4984d40179a67765f2544/actors/builtin/miner/policy.go#L144

**Comment by anorth** [comment]
I think constraints on minimum sector lifetime will make this practically impossible, but we should structure the code to be robust anyway. I propose:

- Change [this pre-commit constraint](https://github.com/filecoin-project/specs-actors/blob/0dcd04ea4dca004872a4984d40179a67765f2544/actors/builtin/miner/miner_actor.go#L447) to require expiration strictly after activation + max prove-commit delay (see also #672), in addition to also constraining it to be at least the minimum sector lifetime policy (#794).
- Add the prove-commit check that @wadealexc suggests and ignore the sector if it fails

**Comment by anorth** [comment]
@acruikshank sending this your way since you have been working with that code.
