### ISSUE TITLE
Reward.AwardBlockReward: Miner may be able to cause abort during block processing

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#797]
`Reward.AwardBlockReward` relies on a successful Send to the Miner that produced the block:

https://github.com/filecoin-project/specs-actors/blob/70a18dfa12d7a0bc7981e73c6021c11d7de14cb3/actors/builtin/reward/reward_actor.go#L92-L93

The Miner's strategy is as follows:
* Wait until leader election allows the Miner to produce a block
* Intentionally create a consensus fault
* Create a transaction to Miner.ReportConsensusFault, and include it in the block

A valid ReportConsensusFault will end with a call to `terminateMiner`:

https://github.com/filecoin-project/specs-actors/blob/70a18dfa12d7a0bc7981e73c6021c11d7de14cb3/actors/builtin/miner/miner_actor.go#L2153-L2161

After terminating a Miner's deals, this invokes the runtime method `rt.DeleteActor`, which will remove the Miner from the state tree and cause subsequent Sends to the Miner to fail.

#### Recommendation

Remove the `RequireSuccess` condition from `Reward.AwardBlockReward`. This should never fail - and if it does, we should assume the miner is responsible.

**Comment by anorth** [comment]
SGTM
