### ISSUE TITLE
Miner.ReportConsensusFault: possible incorrect constraints on faultAge

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#801]
https://github.com/filecoin-project/specs-actors/blob/70a18dfa12d7a0bc7981e73c6021c11d7de14cb3/actors/builtin/miner/miner_actor.go#L1448-L1452

This should abort if `faultAge < 0`, rather than `faultAge <= 0`

**Comment by ZenGround0** [comment]
We might want to prevent slashing at the current epoch (keep <= 0) as a preventative measure against #797.  I'm not sure what we gain from allowing this-epoch faults.

**Comment by anorth** [comment]
I don't think a zero-age fault makes a lot of sense. That would mean providing a block header with an epoch number that's the same as the epoch currently being evaluated? I'm going to close this, but please re-open if we're missing something serious.
