### ISSUE TITLE
Miner control functions should abort on no-op

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#803]
* `ChangeWorkerAddress` should abort if `params.NewWorker` is the same as the existing Worker address

* `ChangePeerId` should abort if `params.NewID` is the same as the existing PeerID

* `ChangeMultiaddrs` should abort if `params.NewMultiaddrs` is the same as the existing Multiaddrs

**Comment by anorth** [comment]
> ChangeWorkerAddress should abort if params.NewWorker is the same as the existing Worker address

Not if there is a pending change to some other worker address. The miner needs to be able to change it back. I suggest just not attempting any special case here, unless there's an identified problem with setting it.

Similarly for others, I don't see why they should add code to handle no-op? To me, robust code means that edge cases are handled naturally by the existing code and don't need special handling. I can't see the problem with these as they are.

**Comment by wadeAlexC** [comment]
That's fine with me. This can be closed if there are no more comments!
