### ISSUE TITLE
Miner control functions should abort for empty params

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#804]
* `ChangePeerID` should check that `params.NewID` is not empty

* `ChangeMultiaddrs` should check that `params.NewMultiaddrs` is not empty

**Comment by anorth** [comment]
I'm not sure that the chain should be enforcing this. They're both opaque values as far as the rest of the chain state is concerned. If a miner doesn't want to advertise one of them for some reason, do we want to force them to put junk in there? 

@whyrusleeping do you have an opinion here?

**Comment by anorth** [comment]
I'm going to close this in favour of #804. FYI @Stebalien please consider any _minimum_ lengths we should also be enforcing.
