### ISSUE TITLE
Miner: NewDeadlineInfo may calculate negative Challenge and FaultCutoff epochs during first ~70 epochs

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#805]
https://github.com/filecoin-project/specs-actors/blob/70a18dfa12d7a0bc7981e73c6021c11d7de14cb3/actors/builtin/miner/deadlines.go#L84-L92

This method should ensure these epochs are at least "0"

**Comment by anorth** [comment]
Why?

**Comment by ZenGround0** [comment]
Another angle to this issue: validate that lotus handles negative epoch randomness sampling correctly as part of audit.

**Comment by wadeAlexC** [comment]
My main concern is how runtime methods may handle negative epochs, as ZenGround mentioned. 

Not having reviewed the whole of the miner yet, I was also concerned with how the rest of the miner actor handles these negative values, but maybe that's not an issue.

**Comment by anorth** [comment]
I think this is fine. Also, mainnet will never experience the first 70 epochs.
