### ISSUE TITLE
Miner.Constructor: Additional input validation

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#807]
The Miner constructor should check that:

* `OwnerAddr != WorkerAddr`

* `PeerId != nil`

* `Multiaddrs != nil`

**Comment by ZenGround0** [comment]
Where does "OwnerAddr != WorkerAddr" come from?  I haven't been caught up on this for a while but last time I checked in it was the common case that these two would be the same.

**Comment by anorth** [comment]
I disagree with requiring OwnerAddr != WorkerAddr. It's indeed a common case for small scale miners, or in transition.

We should normalize those nils to empty arrays though.

**Comment by anorth** [comment]
From #806, you might have been also suggesting that empty values should not be acceptable; I think they should be allowed unless we resolve something else over there.

**Comment by anorth** [comment]
Our CBOR-gen code normalizes `nil` Go slices to empty CBOR arrays and vice versa. This means that, when invoked from a deserialized message
- `PeerId` will always be `nil` or non-empty
- `Multiaddrs` will be `nil` or non-empty, as will each entry

`nil` is a canonical representation for an empty slice in Go so doesn't present a particular safety risk.

@wadeAlexC I think there's nothing to do here. We can't constrain those things to be non-`nil` but neither do I think there's any value in constraining them to be non-empty (if not `nil`): they will be serialized as empty arrays in either case.
