### ISSUE TITLE
Bound potential work in market actor processing timed-out deals

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#814]
The market actor can end up with an unbounded number of deals expiring un-committed in the same epoch, processed by the cron with no party paying gas. Since deal StartEpochs are chosen by the clients, this could easily be abused to cause a very expensive tipset evaluation.

A payment in advance for presumed expiry (even though it usually won't happen) could make this attack more expensive, but probably not enough, and at the price of making all deals more expensive.

Related: #813

**Comment by anorth** [comment]
#889 may resolve this, but may not do so fully.

**Comment by anorth** [comment]
It now looks to me like #889 may be enough, but @Stebalien could you please try to break this with your mind and think about further solutions? Close if you think we're good.

**Comment by Stebalien** [comment]
I can't think of a way to break this intentionally (cost effectively).

However, it looks like null blocks can cause deal ticks to batch up. That is, every time we have a null block, we'll defer processing deals till the next epoch. However, in that epoch, we'll schedule all deals to be processed in `epoch+DealUpdatesInterval`. This means every null block will punch a hole in deal processing, _permanently_ bunching deals that should have been processed in that epoch up with deals in the next epoch.

Given an assumed 20 null blocks per day (a number I heard somewhere...), it'll take ~144 days for all deals to bunch up on a single epoch (it'll actually take longer, but I hate probability and that's the right order of magnitude).

So we need some way to redistribute them, or we need to process them _as if_ we processed them in the past.

**Comment by anorth** [comment]
Great catch. In the market `CronTick` we need to remember the queue key (`i`) and be sure to reschedule based on each deal state's key, not the current epoch. We want to reschedule for the next largest epoch `== currEpoch % i`.

I'll re-assign this to @aarshkshah1992 to follow up (and test).

**Comment by anorth** [comment]
@Stebalien I think you and I were both thinking in the world where cron is not invoked for empty tipsets. But cron now _is_ invoked for every epoch, empty or not, so the batching that you fear won't in fact happen.

**Comment by Stebalien** [comment]
Hm. I agree, but given all the code we have to "catch up", I'm going to see if I can push this change through anyways.

**Comment by Stebalien** [comment]
Ok, so, fixing this isn't worth it and could potentially introduce worse issues. So I'm going to leave as-is.
