### ISSUE TITLE
Alphabeta filter can configure initial values

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#823]
[Context here](https://github.com/filecoin-project/specs-actors/pull/762#discussion_r461157748)

Currently filter position and velocity are only easily configured to zero.  Make this more ergonomic for actor constructors.  

Also add the actor constructor parameters that we will feed into filter values.  FYI @magik6k we'll need genesis power as an input to the power actor constructor for proper setup during genesis construction.  Will there be any trouble getting that?

FYI @zixuanzh @davidad

**Comment by ZenGround0** [comment]
Initial qa power velocity = prove commit throughput = 3840*2^30 B/epoch

**Comment by ZenGround0** [comment]
@zixuanzh confirming (genesis power, prove commit throughput) is the (x0, v0) for power smoothing.

When you have a good estimate for (x0, v0) for reward smoothing please leave them here.

**Comment by zixuanzh** [comment]
@ZenGround0 for (x0, v0) of per epoch reward, we can use the first epoch reward from simple minting as x0 and e^-lambda - 1 (decay rate - 1) as v0.
