### ISSUE TITLE
Encapsulate miner state manipulations as state methods

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#828]
Since the miner state refactor there have been at least two bugs caused by the miner's state being inconsistent after direct manipulation from the actor code. The miner state should instead be able to enforce its own invariants as far as possible, and be testable. The partition and deadline state already enjoy this property, along with lots of tests.

Move some of the manipulations of miner state into methods or functions of miner state or its constituents, like #761. Add tests.

**Comment by Stebalien** [comment]
The only remaining function that modifies internals of another piece of state is `Actor.ExtendSectorExpiration`.
