### ISSUE TITLE
When extending sectors, power delta/pledge delta is not summed

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#865]
https://github.com/filecoin-project/specs-actors/blob/22561695558be820d7b994a4909d724aa9958973/actors/builtin/miner/miner_actor.go#L857

It's repeatedly set, but never summed.

Also, there's a stray commented out line that should probably be removed:

https://github.com/filecoin-project/specs-actors/blob/22561695558be820d7b994a4909d724aa9958973/actors/builtin/miner/miner_actor.go#L847

**Comment by Stebalien** [comment]
Actually, I think stray commented line is supposed to be updating the pledge, right?

**Comment by Stebalien** [comment]
cc @anorth?

**Comment by anorth** [comment]
The `powerDelta` overwriting is definitely a bug, thanks for finding.

No, I think the commented line is subsumed by the return from `partition.ReplaceSectors`. The pledge is not expected to change, so there's nothing to update, though we should accumulate the pledgeDelta in the same way for completeness (but expect it to be zero, as commented below).
