### ISSUE TITLE
the dealDurationBounds of  orders from robot isn't match the markert-actor

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/specs-actors#867]
the endEpoch = 609854 and the startEpoch =5981
(609854-5981)*3456 <  180 *3456 = 622,080 
![image](https://user-images.githubusercontent.com/25957795/89030873-f4c51080-d363-11ea-8af9-921d032307d3.png)

Refer to:
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/policy.go#L22

```
func dealDurationBounds(size abi.PaddedPieceSize) (min abi.ChainEpoch, max abi.ChainEpoch) {
	return abi.ChainEpoch(180 * builtin.EpochsInDay), abi.ChainEpoch(540 * builtin.EpochsInDay) // PARAM_FINISH
}
```

**Comment by mishmosh** [comment]
Thanks @waynewyang for the report and @ZenGround0 for flagging this.

@arajasek @georgestefanorobert was this addressed in recent updates to minimum deal length, or still an open issue?

**Comment by anorth** [comment]
Since this can't be resolved in the actor code, I'm closing this issue for now. The new bounds took a lot of people by surprise - I'm sorry they weren't communicated more clearly in advance.
