### ISSUE TITLE
PledgePenaltyForTermination should be negatively correlative to SectorAge

### ISSUE THREAD

**Issue by steven004** [filecoin-project/specs-actors#871]
See the implementation of `PledgePenaltyForTermination` from [here](https://github.com/filecoin-project/specs-actors/blob/866b3a6274eff7679d8de6d97d1846eec3fe509a/actors/builtin/miner/monies.go#L62-L75)

Sadly, the penalty is the most at the last day of a sector life, while the least at the first day. It looks the SectorRestOfLife should be used instead of SectorAge in this function.

**Comment by zixuanzh** [comment]
hey @steven004, the reason why termination fee is lower in the first few days is that the protocol wanted to lower the initial storage pledge for miners. The goal of the network is to provide useful storage and it is thus important to maintain sectors until the end of their promised lifetime. There is a negative externality associated with sectors that are terminated early and that cost needs to be internalized. Moreover, termination fee actually plateaus in the current construction to not discourage sectors of longer lifetime.

**Comment by steven004** [comment]
@zixuanzh , thanks for the explanation. Understood that this is to encourage miners to maintain sectors until the end of their promised lifetime. The concern I have is that the formula is kind of counter intuitive - **the more time you serve, the more penalty you will pay** in some period, which is really annoying. 

This is just termination fee calculation. This part `BR(StartEpoch, 1d)*min(SectorAgeInDays, 70)`  is actually nothing to do with the initial pledge collateral. We can still keep the IP low, while keep the terminate fee high enough to make it work. A simple way is to keep fixed.

**Comment by anorth** [comment]
I understand this to be functioning as intended by the crypto-econ team. I'm leaving this issue open for discussion since there's a legitimate request for policy motivation, but not expecting any code to change without a concrete resolution here.

**Comment by zixuanzh** [comment]
> The concern I have is that the formula is kind of counter intuitive - the more time you serve, the more penalty you will pay in some period, which is really annoying.

The value of a short-lived and unreliable sector is quite limited to both the network and clients who need reliable and useful storage. When a sector terminates early, most of its value for the network is canceled out. The reason why it is increasing and then plateaus is to make onboarding cheaper for miners as miners can build up the termination fee over time.

> This is just termination fee calculation. This part BR(StartEpoch, 1d)*min(SectorAgeInDays, 70) is actually nothing to do with the initial pledge collateral. We can still keep the IP low, while keep the terminate fee high enough to make it work. A simple way is to keep fixed.

`BR(StartEpoch, 1d)*min(SectorAgeInDays, 70)` intends to approximate how much a sector would have earned, up to some limit, before it is terminated. We have explored some fixed termination fee but to ensure that the sector has enough to pay for its termination fee, initial pledge will be much higher. More work is still being done to improve the approximation of how much the sector would have earned. This is also a partial result of per sector accounting being too expensive to the chain. We are working on a more complete Cryptoecon documentation and hope to answer many of these questions there.

**Comment by anorth** [comment]
We're not planning to change this.
