### ISSUE TITLE
Defer power for new sectors until first Window PoSt

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#884]
The research team have indicated desire to defer the power for a new sector until its first Window PoSt. This mitigates some PoRep replay attacks across chains.

If/when we do this, be sure to notify @whyrusleeping @magik6k because it changes the sectors with power for Winning PoSt. The node must exclude the new sectors from the set eligible set.

We'll need a good story about how genesis miners have power while their first proving period hasn't started yet. Probably that means exporting the appropriate sector allocation Go functions so that genesis construction can call them easily after initially adding sectors to partitions.

Some policy questions:
- What happens if a sector is declared faultly before the first post
- What if it's skipped for the first post?
- What if undeclared fault?
- What if it's terminated?
- How would semantics differ from marking the sector as both faulty and recovering upon porep, if at all? Which penalties would/n't b e charged?

**Comment by Stebalien** [comment]
For context, the current (as of today) policy in #883 is:

> What happens if a sector is declared faultly before the first post

The sector is marked faulty and can be recovered using the normal recovery flow. The miner will be penalized as usual for the faulty sector.

Note: this _does_ mean that the miner will be penalized for a sector that had no actual power.

> What if it's skipped for the first post?
> What if undeclared fault?

In #883, the sector will go directly from "unproven" to faulty.

> What if it's terminated?

Currently, in #883 the sector can be terminated like any other sector, paying the same fines.

> How would semantics differ from marking the sector as both faulty and recovering upon porep, if at all? Which penalties would/n't b e charged?

Currently, in #883, penalties are charged as if the sector had real power.

**Comment by nicola** [comment]
The answers from @Stebalien are correct.

The understanding that we are overly penalizing (via FF or SP) a miner that has not gotten power yet is correct. We will add this to the list of fault fees optimizations but we should leave this as if the sector had real power.

**Comment by Stebalien** [comment]
Fixed.
