### ISSUE TITLE
Restrict miner capabilities while in IP debt

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#886]
A miner is considered in "IP debt" when their unlocked balance does not cover the initial pledge requirements for all committed and non-terminated sectors. 

At present, when in IP debt, the following methods are disallowed:
- ProveCommitSector
- WithdrawFunds

It's also my understanding that the miner should become ineligible to win leader election though that it outside actors scope (though we could help by adding a static helper method similar to `MinerNominalPowerMeetsConsensusMinimum`)

IP debt should be a bad enough state that a miner is incentivised to top-up pledge collateral, without triggering a cascading failure that makes the situation worse. In particular, we definitely want to continue allowing Window PoSt so the miner does not necessarily incur more penalties.

Which other methods should be restricted in order to make repayment the miner's top priority? I propose:
- PreCommitSector ("no growth while in debt")
- DeclareFaultsRecovered ("pay penalties as condition of recovery")

Methods we should explicitly still allow:
- DeclareFaults (don't exacerbate the cost of miner operational issues)
- TerminateSectors (ditto)
- ReportConsensusFault (called by someone else, not the miner operator)

Other candidates that don't seem high value, so default to allowing normal operation:
- ExtendSectorExpiration
- CompactPartitions

@zixuanzh @nicola Please ack or add your opinions.

**Comment by nicola** [comment]
We made a list that is still in progress. I am happy to continue here.

Our proposal was to leave `DeclareFaultsRecovered` as is, but disable recovery on WindowPoSt if in debt - both ways achieve the same goal.

Will update this post once we have more clarity (@irenegia)

**Comment by anorth** [comment]
We should remove ProveCommit from being restricted (but restrict PreCommit), else the miner may lose a pre-commit deposit, which is too harsh.

**Comment by nicola** [comment]
Strict approach
- Disallow `PreCommit`, `ProveCommit`, `DeclareFaultsRecovered`
- Allow `DeclareFault`, `TerminateSectors`, `ReportConsensusFault`

- We need to clarify `WithdrawFunds` with @zixuanzh since a miner could be using these funds to repay debt (or we can have a new method called e.g. Refinance where a miner can move unlocked funds to locked funds)

Lenient approach
- Allow everything as long as the miner debt increases (except `WithdrawFunds` to be clarified)
  - This has implications to power table inflations, however if considered not problematic, we can do this.

**Comment by anorth** [comment]
@nicola what we call locked funds cannot be "in debt". If a miner is in debt, then their balance (above the amount "locked") is not covering IP, so should not be withdrawn.

**Comment by anorth** [comment]
I think @nicola listed `ProveCommit` as disallowed in error, since they are the one that suggested to me we should not cause a miner to lose a pre-commit deposit for this.

So final listing:
- Disallow WithdrawFunds, PreCommitSector, DeclareFaultsRecovered (or processing of declared recoveries at WPoSt)
- Allow DeclareFaults, TerminateSectors, ReportConsensusFault, the rest

**Comment by nicola** [comment]
Hey @anorth I don't think we will have time to do a proper analysis on this one, and we should start with the strict approach, so we should have ProveCommit sector in the disallow set. This has to do with the inability of a miner to be able to repay their PreCommitDeposit.

We believe that as we will have time to find edge cases, we should be able to prove that the lenient approach will work too. If successful, this would remove ProveCommit from the disallow list too.

**Comment by ZenGround0** [comment]
Moving forward with the following disallow list:

- WithdrawFunds
- PreCommitSector
- ProveCommitSector
- DeclareFaultsRecovered

**Comment by nicola** [comment]
If this is true "there's no room for an explicit "refinance" operation: their funds are automatically financing obligation in the right order", then it seems that there is no need for a check on "WithdrawFunds" since they are locked already, no?

**Comment by ZenGround0** [comment]
> Refinance where a miner can move unlocked funds to locked funds

@nicola I think there is some confusion about how pledge collateral is tracked.  The unlocked balance covers pledge requirements, not the locked balance.

**Comment by anorth** [comment]
> This has to do with the inability of a miner to be able to repay their PreCommitDeposit.

I think there might be confusion here too. There is no way for a miner to ever get to a state where they cannot repay precommit deposit. We _always_ hold that balance, even if they go into fee debt. We maintain an invariant that balance >= PCD, and the balance covering PCD cannot be used for anything else.

**Comment by nicola** [comment]
@irenegia and I had the assumption that PCD was part of the pledge pool and there may be scenario where miner may not have enough to pay PCD. Since PCD is always guaranteed, then we should allow for ProveCommit.
