### ISSUE TITLE
Record miner fee debt when penalties exceed unlocked balance

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#888]
Since #808, a miner pays fees first out of locked funds, then from the unlocked funds covering their initial pledge. When they reach the point where only funds covering pre-commit deposit (if any) remain, they are out of money to pay any subsequent penalty.

Issue #627 proposed terminating the miner at this point, but we don't need to be that harsh. We can allow a distressed miner to go into fee debt (not to be confused with IP debt), so long as they repay the debt before recovering full capabilities (see #886). As an example, if a miner with one sector has a fault, and runs out of funds after 7 days of consecutive fees, we allow them to stay faulty and accumulate fee debt, but recover the sector on the 13th day if they repay all fees. The miner would need to pay back the fee debt, and additionally restore the IP requirement.

- Add a new field to miner state recording the amount of fee debt
- When a miner needs to pay fees in excess of available balance, record that as fee debt, instead of ignoring it as we currently do
- When evaluating the condition of IP debt
    - If the miner has fee debt and any unlocked balance, burn the balance and reduce the fee debt appropriately
    - Consider a miner to be in IP debt if they have any fee debt, even if IP requirement is zero (thus restricted in capabilities as for #886)

I don't think we need a method for the miner operator to call explicitly to inspect the fee repayment, but there might turn out to be a case where we can't do it automatically.

An explicit flow to exercise in tests is a miner going into fee debt with a faulty sector, then calling DeclareFaultsRecovered in a message carrying enough balance to pay back the debt and recover IP requirements.

A miner in fee debt is not expected to receive any funds through `AddLockedFunds` because they can't win an election.

@zixuanzh @nicola @davidad please review and request any changes to this spec

**Comment by zixuanzh** [comment]
LGTM except I dont understand the statement

> I don't think we need a method for the miner operator to call explicitly to inspect the fee repayment, but there might turn out to be a case where we can't do it automatically.

**Comment by anorth** [comment]
Ok this is good to go.
