### ISSUE TITLE
Switch to bitfields by value

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#895]
Currently, we're passing around bitfields by reference. Unfortunately, we're not carefully checking for null pointers (see #604).

Plan:

* [ ] Switch all bitfields to by-value, both in specs actors and in lotus
* [ ] If reasonable, make bitfields immutable.

Pull requests:

* [x] Bitfield PR: https://github.com/filecoin-project/go-bitfield/pull/44
* [x] Specs actors PR: https://github.com/filecoin-project/specs-actors/pull/900
* [ ] Lotus PR: https://github.com/filecoin-project/lotus/pull/2839

**Comment by anorth** [comment]
@magik6k @arajasek we'll work to make this as easy for you to consume as possible. Please ping us on a sync channel when you eventually consume this if you encounter any friction or would like to recruit our help. 

We expect this change to eliminate a class of potential errors introduced by the possibility of nil pointers.

**Comment by anorth** [comment]
@Stebalien Done?

**Comment by Stebalien** [comment]
Ah, yes.
