### ISSUE TITLE
Bound length of strings and arrays in state

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#897]
A few items in state are strings or byte arrays that are provided from off chain. We should bound the length of these strings to a tight reasonable bound, else we could incur unwanted de/serialization cost as these things are read and written (potentially by parties other than the party controlling the value).

- [ ] DealProposal.Label: 100s of bytes?
- [x] MinerInfo.PeerID: 100s of bytes?
- [x] MinerInfo.Multiaddrs: array length of 10s? each value 100s of bytes?
- [ ] Multisig.Signers: array length of 100s?

The Address type is limited on CBOR decoding to 64 bytes, though it [should](https://github.com/filecoin-project/go-address/issues/9) also check on encoding.

BigIntegers are limited to 128 bytes, which is probably ok from a serde point of view (though maybe not for arithmetic, #866).

Related to #604

**Comment by Stebalien** [comment]
#920 currently deals with MinerInfo.PeerID and MinerInfo.Multiaddrs.

**Comment by anorth** [comment]
@Stebalien done?

**Comment by Stebalien** [comment]
Not quite. Still need deal label, and signers.

I'm picking 256 for the deal label, same for max signers.
