### ISSUE TITLE
Miner: Simplify sector number allocation during precommit

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#905]
`Miner.PreCommitSector` requires that `params.SectorNumber` has not been previously allocated, as sector numbers should not be reused:

https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L445-L461

As the comment states, the checks following the call to `AllocateSectorNumber` are not entirely necessary, but they may be helpful sanity checks.

Assuming they're being kept, I propose moving the existence checks to the `AllocateSectorNumber` method - they're functionally similar, and this would make PreCommitSector easier to parse.

**Comment by ZenGround0** [comment]
These duplicate checks have been removed

**Comment by ZenGround0** [comment]
* In v3 we modified HAMT to have `PutIfAbsent` which delegates a more efficient check to PutPrecommittedSectors
* At some point (I think also v3) we stopped the HasSectorNo check
