### ISSUE TITLE
Power: Process batch proof verifications before deferred cron events

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#909]
From OnEpochTickEnd: https://github.com/filecoin-project/specs-actors/blob/0f9f59a4a6c302014a4dddc12fdff4effe409885/actors/builtin/power/power_actor.go#L200-L201

This would also involve some changes to the Miner actor. For example, precommit expiry bound could remove the additional "+1": https://github.com/filecoin-project/specs-actors/blob/0f9f59a4a6c302014a4dddc12fdff4effe409885/actors/builtin/miner/miner_actor.go#L516-L520

**Comment by wadeAlexC** [comment]
`ConfirmSectorProofsValid` reschedules expirations for replaced sectors to the end of their next deadline window: https://github.com/filecoin-project/specs-actors/blob/8735710c0586c16054724aea77808860531096e5/actors/builtin/miner/miner_actor.go#L662-L665

If the sector to be replaced is in a deadline whose `Close` epoch is `CurrEpoch + 1`, the new expiration chosen is equal to CurrEpoch: https://github.com/filecoin-project/specs-actors/blob/8735710c0586c16054724aea77808860531096e5/actors/builtin/miner/miner_state.go#L442-L444

Because the power actor processes batch proof verification _after_ deferred cron events, the `handleProvingPeriod` cron event won't catch this expiry immediately: https://github.com/filecoin-project/specs-actors/blob/8735710c0586c16054724aea77808860531096e5/actors/builtin/miner/miner_actor.go#L1579-L1581

If I understand correctly, this means that the miner won't lose power for the replaced sector until the next day.

**Comment by anorth** [comment]
FYI @acruikshank an example of something for which we need a scenario test.
