### ISSUE TITLE
Miner: bubble up error in processEarlyTerminations

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#918]
https://github.com/filecoin-project/specs-actors/blob/8735710c0586c16054724aea77808860531096e5/actors/builtin/miner/miner_actor.go#L1451

This should probably return the error rather than aborting directly, so that the `RequireNoErr` outside the ForEach can catch this: https://github.com/filecoin-project/specs-actors/blob/8735710c0586c16054724aea77808860531096e5/actors/builtin/miner/miner_actor.go#L1465

**Comment by Stebalien** [comment]
We generally just abort in cases like this. We check the error "just in case" (some cases, like the bitfield, can fail to decode).

**Comment by wadeAlexC** [comment]
SGTM. Closing.
