### ISSUE TITLE
Unit tests for Partition.RecordSkippedFaults

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#927]
There's no test for this at the state level. Ensure that:
- declared sectors are in the partition
- already faulty sectors ignored
- recoveries are retracted (without being marked as new faulty power)

**Comment by aarshkshah1992** [comment]
@Stebalien Can I take this up if you don't have a WIP PR for this ?

**Comment by Stebalien** [comment]
I do not have a WIP PR. Feel free to take it.
