### ISSUE TITLE
Require minimum total initial pledge for leader election eligibility

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#933]
As part of simplifying and radically reducing the penalty for consensus faults, we wish to introduce a minimum initial pledge requirement as an eligibility condition for winning the leader election. (That the miner must also have enough funds to cover this pledge is captured in #888).

Implement a free function of miner and reward state that tests whether the miner has a total initial pledge requirement of at least `5.0 * epoch-whole-block-reward`.

The epoch whole block reward value refers to the reward paid to a winning miner per win count, irrespective of the miner's share of power. I.e. `reward.State.ThisEpochReward` [edit: `reward.State.ThisEpochReward / ExpectedLeadersPerEpoch`].

@zixuanzh should this use the `ThisEpochRewardSmoothed`?

**Comment by zixuanzh** [comment]
The "real" consensus fault penalty should be the epoch whole block reward when the consensus fault happens but we dont record that. Given that, it will make more sense to use the `ThisEpochRewardSmoothed`. cc @nicola @davidad

**Comment by davidad** [comment]
Be careful with the factors of 5 here; the amount `epoch-whole-block-reward` is, I think, not stored anywhere; `ThisEpochReward` is [divided by 5 in `AwardBlockReward`](https://github.com/filecoin-project/specs-actors/blob/2817d408e90757cd12b3f011fd71b0dcda60597e/actors/builtin/reward/reward_actor.go#L86) to obtain it. To add to the confusion, if I understand correctly, the factor of 5 that @nicola is specifying is _not_ ExpectedLeadersPerEpoch, but by numerical coincidence it cancels out. The bottom line is that `5.0 * epoch-whole-block-reward` really means `(5.0 * ThisEpochReward) / ExpectedLeadersPerEpoch`.

**Comment by ZenGround0** [comment]
> whether the miner has a total initial pledge requirement

@anorth do we still want this to be a constraint on IP requirement or are we moving to unlocked balance as @nicola suggested yesterday?  

If we want it to be a constraint on IP requirement I want to make sure we are all in agreement that this is equivalent to specifying a minimum miner size.  The size now just fluctuates with changes in block reward.

**Comment by ZenGround0** [comment]
Moving forward with requiring `(5.0 * ThisEpochReward) / ExpectedLeadersPerEpoch` of funds not pledge requirement so that it is possible for precommits to run when a miner has zero power.

**Comment by anorth** [comment]
There is some confusion between this requirement about leader election eligibility, and a related but different requirement about restrictions on miners' ability to PreCommitSector while in IP debt. I understand @nicola's suggestion to be relevant only to the latter.

> If we want it to be a constraint on IP requirement I want to make sure we are all in agreement that this is equivalent to specifying a minimum miner size. The size now just fluctuates with changes in block reward.

Exactly.

> Moving forward with requiring (5.0 * ThisEpochReward) / ExpectedLeadersPerEpoch of funds not pledge requirement so that it is possible for precommits to run when a miner has zero power.

Maybe ok, but I'm not confident. Discussion about PreCommitDeposit should not lead us astray here. Even if we end up using the same calculation for two different things, the code needs to clearly separate them so that we can change them independently.

A consensus fault is generally reported after the height at which the offending miner produces blocks. An offender with low IPR but high balance could withdraw from their balance immediately after committing a fault and likely receive their funds before the consensus fault report message is processed. But if we require IPR to be above a minimum, they can't withdraw that balance. We accept, though, that it's not perfect, since IPR could decrease with a sector expiration.

The condition for leader election eligibility is most clearly expressed in terms of IPR. It doesn't make sense for the PreCommit restriction, but that's a different issue.
