### ISSUE TITLE
suggestion！export more infomation for checking method in one place， give avalable message after message executed

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/specs-actors#94]
1. It would be better to export a struct include method function and some extra filed  like below

```go
type ActorMethod struct {
	MethodFunc interface{}
	ImmediateCaller   addr.Address
	CallerType    []cid.Cid
	AccessRole   int
	//  ... etc
}
```
In this way, we can control all method check in the same code, instead of writing sanity-checking code in every method once

2. noticed that the return value of the publishstoragedeals method has become null.
```go
// this project
func (a *StorageMarketActor) PublishStorageDeals(rt Runtime, params *PublishStorageDealsParams) *adt.EmptyValue {
```

```go
//lotus
func (sma StorageMarketActor) PublishStorageDeals(act *types.Actor, vmctx types.VMContext, params *PublishStorageDealsParams) ([]byte, ActorError) {
```

hope some methods can give some valuable information instead of becoming adt.emptyvalue

**Comment by anorth** [comment]
I interpret the first request as talking about a declarative form for caller and other validation, as opposed to the current procedural form.

I agree that would have some benefits. I'm marking this non-urgent for now. We should be able to improve this later without breaking compatibility (unless it reveals bugs).

**Comment by anorth** [comment]
Folding in to #178.
