### ISSUE TITLE
Miner: Limit max number of partitions per deadline

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#945]
From Slack: 

> [There is] not a hard limit, but the expectation is that no miner will have more than 1EiB of storage. Although we should probably set a hard limit just in case.

**Comment by aarshkshah1992** [comment]
@Stebalien 


What would be a sensible upper bound here ?

**Comment by anorth** [comment]
Sorry I'm coming late to this, but

> expectation is that no miner will have more than 1EiB of storage

... is incorrect. The 1EiB we throw around is a _minimum_ we should aim to support. Anything that prevents this is a problem that needs fixing. We should not impose an upper limit anywhere near this value.
