### ISSUE TITLE
Prove Commit before ProvingPeriodStart

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#946]
Currently, if a miner tries to prove commit a sector before their proving period starts, they won't be able to actually _prove_ it till after their proving period starts.

One fix is to set the proving period start in the past instead of in the future. This _shouldn't_ have any negative repercussions as far as I know.

**Comment by anorth** [comment]
Works for me

**Comment by anorth** [comment]
From @nicola in #1057:
> RegisterMiner sets the proving period in the future, but the miner could on-board sectors that should be challenged in <24h but end up being challenged in 24-48h instead.

I think that's asking for the same thing.
