### ISSUE TITLE
Miner: Remove state.Transaction where not needed

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#955]
A recent [commit](https://github.com/filecoin-project/specs-actors/commit/249b74c92fabbaf47c1eafab1ffeecd89424c300) added `rt.State().Transaction(...)` where `State().ReadOnly()` should have been used instead: https://github.com/filecoin-project/specs-actors/blob/249b74c92fabbaf47c1eafab1ffeecd89424c300/actors/builtin/miner/miner_actor.go#L550-L563

**Comment by wadeAlexC** [comment]
CC @Stebalien

**Comment by wadeAlexC** [comment]
CC @ZenGround0

**Comment by anorth** [comment]
This was explicitly in preparation for doing a state mutation when checking pledge coverage, coming soon.
