### ISSUE TITLE
Multisig Actor - spend more funds than locked at the moment

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/specs-actors#96]
MultisigActorState doesn't save initial amount spent. Here is an example how to spend 150% of initial amount in 3 transactions after 50% of locked period has past.

IMO MultisigActor logic is overloaded with vesting logic, i'd split into MultisigActor and VestingActor if locked amount is needed, so MultisigActor could send msgs to VestingActor to unlock amount with multisig.

See for example:
 https://github.com/filecoin-project/specs-actors/pull/90

**Comment by anorth** [comment]
I believe that #91 resolves this symptom (the problem was in the test code, not the actor). Would you please rebase and confirm?
