### ISSUE TITLE
Payment channel's "extra" feature is broken

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#971]
This feature was designed to allow a miner to withdraw from a payment channel once some "saved method invocation" (saved miner, actor, params tuple) returns success.

However, it cannot be used in practice unless the target method accepts a struct with two parameters that are either strings or byte arrays.

I believe the saved parameters were _supposed_ to be treated as "encoded CBOR".

**Comment by anorth** [comment]
@Stebalien could you please say more on what's wrong and how it might be fixed? If it's not good in it's current form, we should nuke the code, and a future payment channel v2 can re-implement something. Or if we can fix it easily and can justify that effort (?), we can do that.

@whyrusleeping I don't believe this behaviour is needed at all in the current system, with on-chain deals, so I'd err on removing it lest it be misused or buggy.

**Comment by Stebalien** [comment]
Basically, the "extra" field was designed to make it possible to make payment channel settlement contingent on some method invocation succeeding.

The one use-case I know of is paying a third-party to submit a seal proof. The payment channel would "pay out" only if `CheckSectorProven(CheckSectorProvenParams)` returns true.

However, the current payment channel logic invokes the target method with `PaymentVerifyParams` and `PaymentVerifyParams` cannot be unmarshalled into `CheckSectorProvenParams`.

This should be pretty easy to fix.

**Comment by Stebalien** [comment]
Fix in #987.
