### ISSUE TITLE
Check deferred method "params" when proposed

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#973]
When a miner proposes a method invocation, we can, and probably should, validate that:

1. The target actor & method exist.
2. The passed parameters are valid for the target actor & method.

This isn't necessary, but it would help guard against potential issues with invalid parameters.

**Comment by anorth** [comment]
What do you mean by "propose" here? Are you talking about actors, or the VM?

**Comment by anorth** [comment]
I think you're talking about when block producers are putting messages in blocks. That's outside the scope of the actors project, but, in brief:
- the target actor doesn't need to exist if it will be an account actor
- the VM checks that the method exists
- the VM decodes into the target method's structure (*)

This last point is a fact of convenience, not design. Logically, an actor method should receive raw bytes and inspect or decode them as it wishes. We happen to (a) always use CBOR and (b) lean on the VM to decode this for us, but it's not a design goal. "Are valid for the target method" is 100% subjective for the method in question.

**Comment by anorth** [comment]
Basically the VM what is necessary, in fact does more than is necessary, and I don't think we should change anything.

**Comment by anorth** [comment]
@Stebalien is there still an actors-side change that you'd propose here?

**Comment by Stebalien** [comment]
No, thanks, this has been resolved.
