### ISSUE TITLE
Miner: Limit size of ControlAddresses slice

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#977]
When the Miner's info struct is loaded, it must load the entire `info.ControlAddresses` slice, which has no upper bound on size.

In particular, this may increase strain on the reward actor during its invocation of `Miner.AddLockedFund`:

https://github.com/filecoin-project/specs-actors/blob/0d2ebd356c45acb4c3d340ab9d81b20eb65fea03/actors/builtin/miner/miner_actor.go#L1365-L1375

**Comment by anorth** [comment]
The implementation overlapped with #920 such that it was not included.

@aarshkshah1992 please add limits, cc @Stebalien

**Comment by anorth** [comment]
Related to #604

**Comment by aarshkshah1992** [comment]
@anorth What is a reasonable limit on the size ?
