### ISSUE TITLE
Miner: Correct for potential overflow when iterating over multiaddresses

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#978]
`checkPeerInfo` iterates over the supplied `multiaddrs` and sums the length of each individual element. The total is compared against `MaxMultiaddrData` to create an upper bound on the amount of data the miner can place in their info struct:

https://github.com/filecoin-project/specs-actors/blob/0d2ebd356c45acb4c3d340ab9d81b20eb65fea03/actors/builtin/miner/miner_actor.go#L2322-L2331

Iteration uses unchecked addition, which could potentially overflow.

**Comment by Stebalien** [comment]
We'd need to have more memory than can be addressed by an int.

**Comment by wadeAlexC** [comment]
I figured that may be the case, but filed an issue anyway as I wasn't sure. Feel free to close if you're confident this isn't an issue!

**Comment by Stebalien** [comment]
I'm confident this one isn't an issue.
