### ISSUE TITLE
Miner/Market: Clean up deal weight calculation during precommit

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#981]
`Miner.PreCommitSector` invokes `Market.ValidateDealsForActivation` in order to calculate the total deal weight for all referenced deal:

https://github.com/filecoin-project/specs-actors/blob/0d2ebd356c45acb4c3d340ab9d81b20eb65fea03/actors/builtin/miner/miner_actor.go#L503

`ValidateDealsForActivation` is provided an incorrect `SectorStart` epoch by the miner (`CurrEpoch`), as the sector's start epoch is not known at this point. This `SectorStart` is used to perform validation that the deal is in an acceptable state, but is irrelevant to the calculation of `DealWeight`:

https://github.com/filecoin-project/specs-actors/blob/0d2ebd356c45acb4c3d340ab9d81b20eb65fea03/actors/builtin/market/market_actor.go#L630-L642

#### Recommendation

Given that this validation doesn't accomplish much, I propose removing validation from `Market.ValidateDealsForActivation` in favor of a dead-simple deal weight calculation.

**Comment by anorth** [comment]
We've determined that this isn't high importance for network launch. It's a nice clean-up that we'll implement in a discretionary upgrade later.

cc @wadeAlexC
