### ISSUE TITLE
Miner: reduce operations performed in handleProvingDeadline where possible

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#983]
Each Miner represents at least 48 `CronEventProvingDeadline` callbacks per-day. This callback executes `Miner.handleProvingDeadline`, which performs many operations that may not always be necessary. Especially for small / newly-created miners, this should be avoided to circumvent potential DoS vectors.

#### Recommendation

`handleProvingDeadline` should implement short-circuit logic where possible. Here are some possibilities:

* `len(st.AllocatedSectors) == 0`: the entire method may be skipped
* `st.InitialPledgeRequirement == 0`: most of the method may be skipped. precommit expiries should still be handled.
* `st.PreCommitDeposits == 0`: precommit expiries can be skipped
* If the current deadline has no proven sectors, most of the method can be skipped

**Comment by anorth** [comment]
Thanks, I think this is worthwhile, particularly in lieu of #277
